SET ROLE postgres;
-- ============================================================================
-- B.R.A.N.D 2.0 — Daily Quest manager readiness + Welfare manual spend
-- 2026-09-03
--
-- Goals
-- 1) Live Test Agent must not participate in Primary Job readiness / daily quest roster.
-- 2) Teacher can deduct an arbitrary welfare-fund amount with a mandatory reason.
-- 3) Welfare deductions are ledgered as DISTRIBUTE movements without deleting/changing
--    any source transaction history.
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- A. Patch Production-only daily quest / primary job functions in place.
--    Some of these functions are legacy objects whose original source file is not in
--    this repository. We preserve their exact current Production definition and only
--    inject the canonical is_official_participant(...) predicate beside active-student
--    transferred_at checks.
-- --------------------------------------------------------------------------
DO $patch$
DECLARE
  v_name text;
  v_oid oid;
  v_def text;
  v_patched text;
BEGIN
  FOREACH v_name IN ARRAY ARRAY[
    'ensure_daily_quest_report',
    'get_primary_job_admin_board',
    'teacher_save_primary_job_board'
  ]
  LOOP
    SELECT p.oid
      INTO v_oid
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = v_name
    ORDER BY p.oid
    LIMIT 1;

    IF v_oid IS NULL THEN
      RAISE EXCEPTION '[DQ/WELFARE] required function public.% was not found.', v_name;
    END IF;

    v_def := pg_get_functiondef(v_oid);

    IF position('public.is_official_participant' in v_def) > 0 THEN
      CONTINUE;
    END IF;

    -- Most Production functions qualify active students as <alias>.transferred_at IS NULL.
    -- Preserve everything else byte-for-byte as generated by pg_get_functiondef().
    v_patched := regexp_replace(
      v_def,
      '([A-Za-z_][A-Za-z0-9_]*)\.transferred_at[[:space:]]+IS[[:space:]]+NULL',
      E'\\1.transferred_at IS NULL\n      AND public.is_official_participant(\\1.id)',
      'gi'
    );

    IF v_patched = v_def THEN
      -- Fallback for functions that express the same scope via a role predicate.
      v_patched := regexp_replace(
        v_def,
        '(([A-Za-z_][A-Za-z0-9_]*)\.role(::text)?[[:space:]]+IN[[:space:]]*\([^)]*''STUDENT''[^)]*\))',
        E'\\1\n      AND public.is_official_participant(\\2.id)',
        'gi'
      );
    END IF;

    IF v_patched = v_def THEN
      RAISE EXCEPTION '[DQ/WELFARE] could not locate an active-student predicate in public.%; no changes applied.', v_name;
    END IF;

    IF position('public.is_official_participant' in v_patched) = 0 THEN
      RAISE EXCEPTION '[DQ/WELFARE] official participant guard injection failed for public.%', v_name;
    END IF;

    EXECUTE v_patched;
  END LOOP;
END;
$patch$;

-- --------------------------------------------------------------------------
-- B. Any non-official checks that may already exist in an unfinished report must not
--    block manager submission. They remain as audit rows but are marked FAIL and hidden
--    from the manager board by the official-participant filter below.
-- --------------------------------------------------------------------------
UPDATE public.daily_quest_checks c
SET result = 'FAIL',
    check_source = 'DAILY_QUEST_MANAGER',
    checked_at = coalesce(c.checked_at, now()),
    manager_note = coalesce(c.manager_note, 'SYSTEM: 비공식 테스트 계정은 일일퀘스트 공식 집계에서 제외'),
    updated_at = now()
FROM public.daily_quest_reports r
WHERE r.id = c.report_id
  AND r.status IN ('DRAFT','RETURNED','SUBMITTED')
  AND NOT public.is_official_participant(c.student_id)
  AND c.result = 'UNCHECKED';

-- Manager board: return only official participants and official summary counts.
CREATE OR REPLACE FUNCTION public.get_daily_quest_manager_board(p_date date)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_date date := coalesce(p_date, (clock_timestamp() AT TIME ZONE 'Asia/Seoul')::date);
  v_classroom_id integer := public.current_classroom_id();
  v_report_id bigint;
  v_report public.daily_quest_reports%ROWTYPE;
  v_students jsonb;
  v_summary jsonb;
BEGIN
  IF v_classroom_id IS NULL THEN
    RAISE EXCEPTION '[S3] 학급 정보를 찾을 수 없습니다.' USING ERRCODE='DQ311';
  END IF;
  PERFORM public._daily_quest_assert_manager_or_teacher(v_classroom_id, NULL);

  IF v_date = (clock_timestamp() AT TIME ZONE 'Asia/Seoul')::date THEN
    v_report_id := public.ensure_daily_quest_report(v_classroom_id, v_date);
  ELSE
    SELECT id INTO v_report_id FROM public.daily_quest_reports
    WHERE classroom_id=v_classroom_id AND quest_date=v_date;
    IF v_report_id IS NULL THEN
      RAISE EXCEPTION '[S3] 해당 날짜의 보고서가 없습니다.' USING ERRCODE='DQ312';
    END IF;
  END IF;

  SELECT * INTO v_report FROM public.daily_quest_reports WHERE id=v_report_id;
  PERFORM public._daily_quest_assert_manager_or_teacher(v_report.classroom_id, v_report.manager_student_id);
  PERFORM public._sync_daily_quest_attendance(v_report_id);
  SELECT * INTO v_report FROM public.daily_quest_reports WHERE id=v_report_id;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'student_id', s.id,
      'student_name', s.name,
      'brand_name', s.brand_name,
      'checks', (
        SELECT jsonb_agg(jsonb_build_object(
          'check_id',c.id,
          'quest_code',c.quest_code,
          'result',c.result,
          'reward_bv',c.reward_bv_snapshot,
          'reward_gold_gross',c.reward_gold_gross_snapshot,
          'job_name',c.job_name_snapshot,
          'job_wage',c.job_wage_snapshot,
          'checked_at',c.checked_at,
          'manager_note',c.manager_note,
          'teacher_override',c.teacher_override
        ) ORDER BY CASE c.quest_code
          WHEN 'ATTENDANCE' THEN 10 WHEN 'PRIMARY_JOB' THEN 20
          WHEN 'LEARNING_MATERIALS' THEN 30 WHEN 'CLEANING' THEN 40 END)
        FROM public.daily_quest_checks c
        WHERE c.report_id=v_report_id AND c.student_id=s.id
      )
    ) ORDER BY s.name, s.id
  ), '[]'::jsonb)
  INTO v_students
  FROM public.students s
  WHERE public.is_official_participant(s.id)
    AND EXISTS (
      SELECT 1 FROM public.daily_quest_checks c
      WHERE c.report_id=v_report_id AND c.student_id=s.id
    );

  SELECT jsonb_build_object(
    'total_checks', count(*),
    'pass_count', count(*) FILTER (WHERE c.result='PASS'),
    'fail_count', count(*) FILTER (WHERE c.result='FAIL'),
    'unchecked_count', count(*) FILTER (WHERE c.result='UNCHECKED'),
    'attendance_pass', count(*) FILTER (WHERE c.quest_code='ATTENDANCE' AND c.result='PASS'),
    'primary_job_pass', count(*) FILTER (WHERE c.quest_code='PRIMARY_JOB' AND c.result='PASS'),
    'learning_materials_pass', count(*) FILTER (WHERE c.quest_code='LEARNING_MATERIALS' AND c.result='PASS'),
    'cleaning_pass', count(*) FILTER (WHERE c.quest_code='CLEANING' AND c.result='PASS')
  ) INTO v_summary
  FROM public.daily_quest_checks c
  WHERE c.report_id=v_report_id
    AND public.is_official_participant(c.student_id);

  RETURN jsonb_build_object(
    'report', jsonb_build_object(
      'id',v_report.id,'classroom_id',v_report.classroom_id,'quest_date',v_report.quest_date,
      'manager_student_id',v_report.manager_student_id,'status',v_report.status,
      'submitted_at',v_report.submitted_at,'return_reason',v_report.return_reason
    ),
    'summary',v_summary,
    'students',v_students,
    'server_now',now()
  );
END;
$function$;

-- Submission guard should only consider official participants.
CREATE OR REPLACE FUNCTION public.daily_quest_manager_submit(p_report_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_report public.daily_quest_reports%ROWTYPE;
  v_unchecked integer;
BEGIN
  SELECT * INTO v_report FROM public.daily_quest_reports WHERE id=p_report_id FOR UPDATE;
  IF v_report.id IS NULL THEN RAISE EXCEPTION '[S3] 보고서를 찾을 수 없습니다.' USING ERRCODE='DQ320'; END IF;

  PERFORM public._daily_quest_assert_manager_or_teacher(v_report.classroom_id, v_report.manager_student_id);

  IF v_report.status NOT IN ('DRAFT','RETURNED') THEN
    RAISE EXCEPTION '[S3] 현재 상태에서는 제출할 수 없습니다: %', v_report.status USING ERRCODE='DQ321';
  END IF;

  PERFORM public._sync_daily_quest_attendance(v_report.id);

  SELECT count(*) INTO v_unchecked
  FROM public.daily_quest_checks c
  WHERE c.report_id=v_report.id
    AND c.result='UNCHECKED'
    AND public.is_official_participant(c.student_id);
  IF v_unchecked > 0 THEN
    RAISE EXCEPTION '[S3] 아직 확인하지 않은 일일퀘스트가 %건 있습니다.', v_unchecked USING ERRCODE='DQ322';
  END IF;

  UPDATE public.daily_quest_reports
  SET status='SUBMITTED', submitted_at=now(), updated_at=now(),
      returned_at=NULL, returned_by=NULL, return_reason=NULL
  WHERE id=v_report.id;

  RETURN jsonb_build_object('success',true,'report_id',v_report.id,'status','SUBMITTED','submitted_at',now());
END;
$function$;

-- --------------------------------------------------------------------------
-- C. Teacher welfare manual-spend RPCs
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_get_welfare_fund_board(p_classroom_id integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_fund public.welfare_funds%ROWTYPE;
  v_student_count integer;
  v_recent jsonb;
BEGIN
  PERFORM public.ensure_teacher_role();

  IF p_classroom_id IS NULL OR NOT public.is_classroom_member(p_classroom_id) THEN
    RAISE EXCEPTION '[WELFARE] classroom access denied.' USING ERRCODE='P0640';
  END IF;

  SELECT * INTO v_fund
  FROM public.welfare_funds wf
  WHERE wf.classroom_id=p_classroom_id;

  SELECT count(*)::integer INTO v_student_count
  FROM public.students s
  WHERE s.classroom_id=p_classroom_id
    AND public.is_official_participant(s.id);

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'movement_id', x.id,
    'amount', x.amount,
    'reason', regexp_replace(coalesce(x.note,''), '^\[복지기금 사용\][[:space:]]*', ''),
    'created_at', x.created_at
  ) ORDER BY x.created_at DESC, x.id DESC), '[]'::jsonb)
  INTO v_recent
  FROM (
    SELECT m.id, m.amount, m.note, m.created_at
    FROM public.welfare_fund_movements m
    WHERE v_fund.id IS NOT NULL
      AND m.fund_id=v_fund.id
      AND m.movement_type='DISTRIBUTE'
      AND m.transaction_id IS NULL
      AND coalesce(m.note,'') LIKE '[복지기금 사용] %'
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 12
  ) x;

  RETURN jsonb_build_object(
    'classroom_id', p_classroom_id,
    'fund_id', v_fund.id,
    'current_balance', coalesce(v_fund.current_balance,0),
    'total_collected', coalesce(v_fund.total_collected,0),
    'total_distributed', coalesce(v_fund.total_distributed,0),
    'official_student_count', v_student_count,
    'recent_spends', v_recent,
    'server_now', now()
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.teacher_spend_welfare_fund(
  p_classroom_id integer,
  p_amount bigint,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_fund public.welfare_funds%ROWTYPE;
  v_reason text := btrim(coalesce(p_reason,''));
  v_movement_id bigint;
  v_before bigint;
  v_after bigint;
BEGIN
  PERFORM public.ensure_teacher_role();

  IF p_classroom_id IS NULL OR NOT public.is_classroom_member(p_classroom_id) THEN
    RAISE EXCEPTION '[WELFARE] classroom access denied.' USING ERRCODE='P0640';
  END IF;

  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION '사용 금액은 1 이상이어야 합니다.' USING ERRCODE='P0641';
  END IF;

  IF char_length(v_reason) < 2 OR char_length(v_reason) > 200 THEN
    RAISE EXCEPTION '복지기금 사용 사유는 2~200자로 입력해주세요.' USING ERRCODE='P0642';
  END IF;

  SELECT * INTO v_fund
  FROM public.welfare_funds wf
  WHERE wf.classroom_id=p_classroom_id
  FOR UPDATE;

  IF v_fund.id IS NULL THEN
    RAISE EXCEPTION '복지기금이 아직 생성되지 않았습니다.' USING ERRCODE='P0643';
  END IF;

  IF v_fund.current_balance < p_amount THEN
    RAISE EXCEPTION '복지기금 잔액이 부족합니다. 현재 잔액: %', v_fund.current_balance USING ERRCODE='P0644';
  END IF;

  v_before := v_fund.current_balance;

  INSERT INTO public.welfare_fund_movements(
    fund_id, movement_type, amount, source_type, source_id, transaction_id, note
  ) VALUES (
    v_fund.id, 'DISTRIBUTE', p_amount, NULL, NULL, NULL,
    '[복지기금 사용] ' || v_reason
  )
  RETURNING id INTO v_movement_id;

  UPDATE public.welfare_funds
  SET total_distributed = total_distributed + p_amount,
      current_balance = current_balance - p_amount,
      updated_at = now()
  WHERE id=v_fund.id
  RETURNING current_balance INTO v_after;

  RETURN jsonb_build_object(
    'success', true,
    'movement_id', v_movement_id,
    'amount', p_amount,
    'reason', v_reason,
    'balance_before', v_before,
    'balance_after', v_after,
    'spent_at', now()
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.teacher_get_welfare_fund_board(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.teacher_spend_welfare_fund(integer,bigint,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.teacher_get_welfare_fund_board(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.teacher_spend_welfare_fund(integer,bigint,text) TO authenticated;

COMMIT;

SELECT jsonb_build_object(
  'daily_quest_primary_job_guards', jsonb_build_object(
    'ensure_daily_quest_report', position('public.is_official_participant' in pg_get_functiondef((
      SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='ensure_daily_quest_report' ORDER BY p.oid LIMIT 1
    ))) > 0,
    'get_primary_job_admin_board', position('public.is_official_participant' in pg_get_functiondef((
      SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='get_primary_job_admin_board' ORDER BY p.oid LIMIT 1
    ))) > 0,
    'teacher_save_primary_job_board', position('public.is_official_participant' in pg_get_functiondef((
      SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='teacher_save_primary_job_board' ORDER BY p.oid LIMIT 1
    ))) > 0,
    'manager_board', position('public.is_official_participant' in pg_get_functiondef('public.get_daily_quest_manager_board(date)'::regprocedure)) > 0,
    'manager_submit', position('public.is_official_participant' in pg_get_functiondef('public.daily_quest_manager_submit(bigint)'::regprocedure)) > 0
  ),
  'welfare_functions', jsonb_build_object(
    'get_board', to_regprocedure('public.teacher_get_welfare_fund_board(integer)') IS NOT NULL,
    'spend', to_regprocedure('public.teacher_spend_welfare_fund(integer,bigint,text)') IS NOT NULL
  ),
  'official_participants_classroom_1', (
    SELECT count(*) FROM public.students s
    WHERE s.classroom_id=1 AND public.is_official_participant(s.id)
  ),
  'live_test_agents_classroom_1', (
    SELECT count(*) FROM public.students s
    WHERE s.classroom_id=1 AND s.transferred_at IS NULL AND coalesce(s.is_test_account,false)
  ),
  'nonofficial_unchecked_open_daily_quest_rows', (
    SELECT count(*)
    FROM public.daily_quest_checks c
    JOIN public.daily_quest_reports r ON r.id=c.report_id
    WHERE r.status IN ('DRAFT','RETURNED','SUBMITTED')
      AND c.result='UNCHECKED'
      AND NOT public.is_official_participant(c.student_id)
  )
) AS daily_quest_welfare_postcheck;
RESET ROLE;
