-- =====================================================================
-- B.R.A.N.D 2.0 — Dimensional Gate Wave 1 Core Foundation
-- Prepared: 2026-09-15
--
-- Scope:
--   * core character relationship/content tables
--   * single relationship-stage SSOT helper
--   * student roster read RPC
--   * RLS + explicit function/table privileges
--
-- This file is designed to be idempotent for initial rollout where practical.
-- It does NOT modify existing character ownership, home showcase, guild, arcade,
-- or peer-review tables.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Character-specific Dimensional Gate content profile
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_character_profiles (
  character_id bigint primary key references public.characters(id) on delete cascade,
  daily_chat_limit smallint not null default 3 check (daily_chat_limit between 0 and 20),
  start_affinity smallint not null default 0 check (start_affinity between 0 and 100),
  ai_enabled boolean not null default true,
  system_prompt text,
  speaking_style text,
  expertise jsonb not null default '[]'::jsonb,
  deflect_rules text,
  imagery_rules text,
  warning_line_1 text,
  warning_line_2 text,
  lock_line text,
  story_scope text not null default 'STANDARD' check (story_scope in ('STANDARD','MAJOR')),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.dimensional_gate_character_profiles.story_scope is
  'Content-production guide only: STANDARD recommends 2-3 episodes, MAJOR recommends 4-6. It does not enforce episode count.';

-- ---------------------------------------------------------------------
-- 2. Student x character relationship SSOT
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_relationships (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  affinity smallint not null default 0 check (affinity between 0 and 100),
  warning_count smallint not null default 0 check (warning_count >= 0),
  status text not null default 'NORMAL' check (status in ('NORMAL','LOCKED')),
  chat_date date,
  chat_count smallint not null default 0 check (chat_count >= 0),
  first_interacted_at timestamptz,
  last_interacted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, character_id)
);

create index if not exists dimensional_gate_relationships_classroom_student_idx
  on public.dimensional_gate_relationships(classroom_id, student_id);
create index if not exists dimensional_gate_relationships_character_idx
  on public.dimensional_gate_relationships(character_id);

-- ---------------------------------------------------------------------
-- 3. Teacher-authored memories
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_memories (
  id bigint generated by default as identity primary key,
  character_id bigint not null references public.characters(id) on delete cascade,
  memory_no smallint not null check (memory_no between 1 and 3),
  unlock_affinity smallint not null check (unlock_affinity in (40,70,100)),
  title text not null,
  content text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (character_id, memory_no)
);

create index if not exists dimensional_gate_memories_character_idx
  on public.dimensional_gate_memories(character_id, sort_order, memory_no);

-- ---------------------------------------------------------------------
-- 4. One-way memory unlocks (affinity may later fall without revoking memory)
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_memory_unlocks (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  memory_no smallint not null check (memory_no between 1 and 3),
  unlocked_at timestamptz not null default now(),
  source text not null default 'AFFINITY_MILESTONE',
  unique (student_id, character_id, memory_no)
);

create index if not exists dimensional_gate_memory_unlocks_student_idx
  on public.dimensional_gate_memory_unlocks(student_id, character_id);

-- ---------------------------------------------------------------------
-- 5. System/Liminel progress (server-side; never localStorage SSOT)
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_system_progress (
  student_id integer primary key references public.students(id) on delete cascade,
  intro_seen_at timestamptz,
  last_liminel_view_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 6. Future story/gallery/reward foundations
--    Created now so content can be authored without another structural rewrite.
-- ---------------------------------------------------------------------
create table if not exists public.dimensional_gate_story_episodes (
  id bigint generated by default as identity primary key,
  character_id bigint not null references public.characters(id) on delete cascade,
  episode_no smallint not null check (episode_no > 0),
  title text not null,
  required_affinity smallint not null default 0 check (required_affinity between 0 and 100),
  default_bgm_url text,
  estimated_minutes smallint check (estimated_minutes is null or estimated_minutes >= 0),
  headphone_recommended boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (character_id, episode_no)
);

create index if not exists dimensional_gate_story_episodes_character_idx
  on public.dimensional_gate_story_episodes(character_id, sort_order, episode_no);

create table if not exists public.dimensional_gate_story_cuts (
  id bigint generated by default as identity primary key,
  episode_id bigint not null references public.dimensional_gate_story_episodes(id) on delete cascade,
  cut_order integer not null check (cut_order > 0),
  cut_type text not null default 'LINE' check (cut_type in ('TITLE','NARRATION','LINE','CHOICE','CG')),
  speaker text,
  content text,
  background_url text,
  sprite_url text,
  bgm_url text,
  sfx_url text,
  effects jsonb not null default '[]'::jsonb,
  choices jsonb,
  jump_to_order integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (episode_id, cut_order)
);

create index if not exists dimensional_gate_story_cuts_episode_idx
  on public.dimensional_gate_story_cuts(episode_id, cut_order);

create table if not exists public.dimensional_gate_story_progress (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  episode_id bigint not null references public.dimensional_gate_story_episodes(id) on delete cascade,
  opened_at timestamptz,
  completed_at timestamptz,
  last_cut_order integer,
  updated_at timestamptz not null default now(),
  unique (student_id, episode_id)
);

create table if not exists public.dimensional_gate_gallery_assets (
  id bigint generated by default as identity primary key,
  character_id bigint not null references public.characters(id) on delete cascade,
  episode_id bigint references public.dimensional_gate_story_episodes(id) on delete set null,
  asset_type text not null check (asset_type in ('STORY_CG','SPECIAL_CG')),
  title text,
  image_url text not null,
  unlock_affinity smallint check (unlock_affinity is null or unlock_affinity between 0 and 100),
  home_background_allowed boolean not null default false,
  cosmetic_item_id integer references public.cosmetic_items(id) on delete set null,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dimensional_gate_gallery_assets_character_idx
  on public.dimensional_gate_gallery_assets(character_id, sort_order, id);

create table if not exists public.dimensional_gate_gallery_unlocks (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  gallery_asset_id bigint not null references public.dimensional_gate_gallery_assets(id) on delete cascade,
  source text not null,
  unlocked_at timestamptz not null default now(),
  unique (student_id, gallery_asset_id)
);

create table if not exists public.dimensional_gate_reward_rules (
  id bigint generated by default as identity primary key,
  character_id bigint references public.characters(id) on delete cascade,
  affinity_threshold smallint not null check (affinity_threshold in (40,70,100)),
  reward_gold bigint not null default 0 check (reward_gold >= 0),
  reward_crystal bigint not null default 0 check (reward_crystal >= 0),
  reward_bv bigint not null default 0 check (reward_bv >= 0),
  gallery_asset_id bigint references public.dimensional_gate_gallery_assets(id) on delete set null,
  trust_visual_variant_no smallint check (trust_visual_variant_no is null or trust_visual_variant_no between 2 and 3),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists dimensional_gate_reward_rules_character_unique
  on public.dimensional_gate_reward_rules(character_id, affinity_threshold)
  where character_id is not null;
create unique index if not exists dimensional_gate_reward_rules_global_unique
  on public.dimensional_gate_reward_rules(affinity_threshold)
  where character_id is null;

create table if not exists public.dimensional_gate_reward_claims (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  affinity_threshold smallint not null check (affinity_threshold in (40,70,100)),
  transaction_id bigint references public.transactions(id) on delete set null,
  claimed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  unique (student_id, character_id, affinity_threshold)
);

create table if not exists public.dimensional_gate_visual_unlocks (
  id bigint generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  visual_variant_no smallint not null check (visual_variant_no between 2 and 3),
  unlock_type text not null default 'TRUST_100' check (unlock_type in ('TRUST_100')),
  unlocked_at timestamptz not null default now(),
  unique (student_id, character_id, visual_variant_no)
);

create table if not exists public.dimensional_gate_chat_messages (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  role text not null check (role in ('STUDENT','CHARACTER')),
  content text not null,
  request_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists dimensional_gate_chat_messages_recent_idx
  on public.dimensional_gate_chat_messages(student_id, character_id, created_at desc, id desc);
create unique index if not exists dimensional_gate_chat_messages_request_role_unique
  on public.dimensional_gate_chat_messages(student_id, character_id, request_id, role)
  where request_id is not null;

-- ---------------------------------------------------------------------
-- 7. RLS: no direct student data access in Wave 1; RPC is the API boundary.
-- ---------------------------------------------------------------------
alter table public.dimensional_gate_character_profiles enable row level security;
alter table public.dimensional_gate_relationships enable row level security;
alter table public.dimensional_gate_memories enable row level security;
alter table public.dimensional_gate_memory_unlocks enable row level security;
alter table public.dimensional_gate_system_progress enable row level security;
alter table public.dimensional_gate_story_episodes enable row level security;
alter table public.dimensional_gate_story_cuts enable row level security;
alter table public.dimensional_gate_story_progress enable row level security;
alter table public.dimensional_gate_gallery_assets enable row level security;
alter table public.dimensional_gate_gallery_unlocks enable row level security;
alter table public.dimensional_gate_reward_rules enable row level security;
alter table public.dimensional_gate_reward_claims enable row level security;
alter table public.dimensional_gate_visual_unlocks enable row level security;
alter table public.dimensional_gate_chat_messages enable row level security;

revoke all on table public.dimensional_gate_character_profiles from anon, authenticated;
revoke all on table public.dimensional_gate_relationships from anon, authenticated;
revoke all on table public.dimensional_gate_memories from anon, authenticated;
revoke all on table public.dimensional_gate_memory_unlocks from anon, authenticated;
revoke all on table public.dimensional_gate_system_progress from anon, authenticated;
revoke all on table public.dimensional_gate_story_episodes from anon, authenticated;
revoke all on table public.dimensional_gate_story_cuts from anon, authenticated;
revoke all on table public.dimensional_gate_story_progress from anon, authenticated;
revoke all on table public.dimensional_gate_gallery_assets from anon, authenticated;
revoke all on table public.dimensional_gate_gallery_unlocks from anon, authenticated;
revoke all on table public.dimensional_gate_reward_rules from anon, authenticated;
revoke all on table public.dimensional_gate_reward_claims from anon, authenticated;
revoke all on table public.dimensional_gate_visual_unlocks from anon, authenticated;
revoke all on table public.dimensional_gate_chat_messages from anon, authenticated;

-- ---------------------------------------------------------------------
-- 8. Relationship stage SSOT
-- ---------------------------------------------------------------------
create or replace function public.dimensional_gate_relation_stage(p_affinity integer)
returns text
language sql
immutable
as $function$
  select case
    when coalesce(p_affinity, 0) >= 100 then 'TRUST'
    when coalesce(p_affinity, 0) >= 70 then 'AFFECTION'
    when coalesce(p_affinity, 0) >= 40 then 'INTEREST'
    else 'STRANGER'
  end;
$function$;

revoke all on function public.dimensional_gate_relation_stage(integer) from public, anon;
grant execute on function public.dimensional_gate_relation_stage(integer) to authenticated, service_role;

-- ---------------------------------------------------------------------
-- 9. Student roster read RPC
-- ---------------------------------------------------------------------
create or replace function public.student_get_dimensional_gate_roster()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_student_id integer;
  v_classroom_id integer;
  v_result jsonb;
begin
  v_student_id := public.current_student_id();
  v_classroom_id := public.current_classroom_id();

  if v_student_id is null or v_classroom_id is null then
    raise exception 'Student context not found' using errcode='PDG20';
  end if;

  if not exists (
    select 1
    from public.students s
    where s.id = v_student_id
      and s.classroom_id = v_classroom_id
      and s.role::text = 'STUDENT'
      and s.transferred_at is null
  ) then
    raise exception 'Student role required' using errcode='PDG21';
  end if;

  select coalesce(jsonb_agg(row_json order by sort_order, character_id), '[]'::jsonb)
  into v_result
  from (
    select
      c.sort_order,
      c.id as character_id,
      jsonb_build_object(
        'character_id', c.id,
        'character_uid', c.character_uid,
        'name', c.name,
        'epithet', c.epithet,
        'description', c.description,
        'resource_kind', c.resource_kind,
        'resource_url', c.resource_url,
        'full_image_url', c.full_image_url,
        'card_image_url', c.card_image_url,
        'avatar_image_url', c.avatar_image_url,
        'is_owned', coalesce(sc.is_owned, false),
        'relationship_exists', (rel.id is not null),
        'affinity', case when coalesce(sc.is_owned, false) then coalesce(rel.affinity, dgp.start_affinity, 0) else 0 end,
        'relation_stage', case when coalesce(sc.is_owned, false)
          then public.dimensional_gate_relation_stage(coalesce(rel.affinity, dgp.start_affinity, 0))
          else 'LOCKED'
        end,
        'status', case when coalesce(sc.is_owned, false) then coalesce(rel.status, 'NORMAL') else 'LOCKED' end,
        'daily_chat_limit', case when coalesce(sc.is_owned, false) then coalesce(dgp.daily_chat_limit, 3) else 0 end,
        'chat_count', case
          when coalesce(sc.is_owned, false) and rel.chat_date = current_date then coalesce(rel.chat_count, 0)
          else 0
        end,
        'remaining_chat_count', case
          when not coalesce(sc.is_owned, false) then 0
          when rel.chat_date = current_date then greatest(coalesce(dgp.daily_chat_limit, 3) - coalesce(rel.chat_count, 0), 0)
          else coalesce(dgp.daily_chat_limit, 3)
        end,
        'story_scope', coalesce(dgp.story_scope, 'STANDARD'),
        'gate_enabled', coalesce(dgp.is_active, false)
      ) as row_json
    from public.characters c
    left join public.dimensional_gate_character_profiles dgp
      on dgp.character_id = c.id
     and dgp.is_active = true
    left join public.student_characters sc
      on sc.student_id = v_student_id
     and sc.character_id = c.id
     and sc.is_owned = true
    left join public.dimensional_gate_relationships rel
      on rel.student_id = v_student_id
     and rel.character_id = c.id
    where c.is_active = true
  ) q;

  return v_result;
end;
$function$;

revoke all on function public.student_get_dimensional_gate_roster() from public, anon;
grant execute on function public.student_get_dimensional_gate_roster() to authenticated, service_role;

commit;
