SET ROLE postgres;
-- ============================================================================
-- B.R.A.N.D 2.0 — General GOLD arrears auto repayment + teacher manual collection
-- 2026-10-02
--
-- Policy
-- 1) Only positive GOLD transactions trigger automatic repayment.
-- 2) Repayment is FIFO: oldest open student_asset_arrears first.
-- 3) Incoming GOLD is credited and repaid in the same DB transaction, so only the
--    remainder is visible as spendable wallet balance after commit.
-- 4) Manual collection preserves live-auction and equalization reserved GOLD.
-- 5) Every repayment has a dedicated collection row and transaction, and reversal
--    restores both wallet and arrears state.
-- ============================================================================

BEGIN;


create table if not exists public.student_asset_arrear_collections (
  id bigint generated by default as identity primary key,
  arrear_id bigint not null references public.student_asset_arrears(id),
  classroom_id integer not null references public.classrooms(id),
  student_id integer not null references public.students(id),
  amount bigint not null check (amount > 0),
  transaction_id bigint not null references public.transactions(id),
  collection_type text not null check (collection_type in ('AUTO','MANUAL')),
  source_transaction_id bigint references public.transactions(id),
  created_by uuid,
  created_at timestamptz not null default now(),
  reversed_at timestamptz,
  reversal_transaction_id bigint references public.transactions(id)
);

create index if not exists idx_asset_arrear_collections_arrear
  on public.student_asset_arrear_collections(arrear_id, created_at, id);

create index if not exists idx_asset_arrear_collections_source_tx
  on public.student_asset_arrear_collections(source_transaction_id, id)
  where source_transaction_id is not null and reversed_at is null;

create index if not exists idx_asset_arrear_collections_student
  on public.student_asset_arrear_collections(student_id, created_at desc, id desc);

alter table public.student_asset_arrear_collections enable row level security;
revoke all on public.student_asset_arrear_collections from public, anon, authenticated;

create or replace function public._collect_student_gold_asset_arrears(
  p_student_id integer,
  p_max_amount bigint,
  p_collection_type text,
  p_source_transaction_id bigint default null,
  p_created_by uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_wallet_gold bigint:=0;
  v_budget bigint:=0;
  v_total_collected bigint:=0;
  v_arrear record;
  v_outstanding bigint:=0;
  v_collect bigint:=0;
  v_new_paid bigint:=0;
  v_tx_id bigint;
  v_collection_count integer:=0;
begin
  if p_collection_type not in ('AUTO','MANUAL') then
    raise exception '올바르지 않은 미납 징수 유형입니다.' using errcode='P0640';
  end if;
  if p_max_amount is null or p_max_amount<0 then
    raise exception '미납 징수 한도는 0 이상이어야 합니다.' using errcode='P0641';
  end if;
  if p_collection_type='AUTO' and p_source_transaction_id is null then
    raise exception '자동상환에는 원본 수입 거래가 필요합니다.' using errcode='P0642';
  end if;

  select s.classroom_id
    into v_classroom_id
  from public.students s
  where s.id=p_student_id
    and s.transferred_at is null;

  if v_classroom_id is null then
    raise exception '활성 학생을 찾을 수 없습니다.' using errcode='P0632';
  end if;

  select coalesce(w.gold,0)::bigint
    into v_wallet_gold
  from public.wallets w
  where w.student_id=p_student_id
  for update;

  if v_wallet_gold is null then
    raise exception '지갑을 찾을 수 없습니다: student=%',p_student_id using errcode='P0003';
  end if;

  v_budget:=least(p_max_amount,v_wallet_gold);
  if v_budget<=0 then
    return jsonb_build_object(
      'student_id',p_student_id,
      'collection_type',p_collection_type,
      'collected_total',0,
      'collection_count',0,
      'wallet_gold_after',v_wallet_gold,
      'remaining_outstanding',coalesce((
        select sum(a.assessed_amount-a.paid_amount)
        from public.student_asset_arrears a
        where a.student_id=p_student_id
          and a.value_token='GOLD'
          and a.status in ('UNPAID','PARTIAL')
      ),0)
    );
  end if;

  for v_arrear in
    select a.*
    from public.student_asset_arrears a
    where a.student_id=p_student_id
      and a.value_token='GOLD'::public.value_token_type
      and a.status in ('UNPAID','PARTIAL')
      and a.paid_amount<a.assessed_amount
    order by a.created_at,a.id
    for update
  loop
    exit when v_budget<=0;

    v_outstanding:=greatest(v_arrear.assessed_amount-v_arrear.paid_amount,0);
    if v_outstanding<=0 then
      continue;
    end if;

    v_collect:=least(v_outstanding,v_budget);
    v_wallet_gold:=v_wallet_gold-v_collect;

    update public.wallets
    set gold=v_wallet_gold,
        updated_at=now()
    where student_id=p_student_id;

    insert into public.transactions(
      classroom_id,student_id,value_token,amount,balance_after,
      source_type,source_id,tax_amount,memo
    ) values (
      v_classroom_id,p_student_id,'GOLD'::public.value_token_type,-v_collect,v_wallet_gold,
      'TEACHER_DEDUCT'::public.transaction_source_type,v_arrear.id,0,
      case when p_collection_type='AUTO'
        then format('[미납 자동상환] %s · %s GOLD',v_arrear.reason,v_collect)
        else format('[미납 수동징수] %s · %s GOLD',v_arrear.reason,v_collect)
      end
    )
    returning id into v_tx_id;

    insert into public.student_asset_arrear_collections(
      arrear_id,classroom_id,student_id,amount,transaction_id,
      collection_type,source_transaction_id,created_by
    ) values (
      v_arrear.id,v_classroom_id,p_student_id,v_collect,v_tx_id,
      p_collection_type,p_source_transaction_id,coalesce(p_created_by,auth.uid())
    );

    v_new_paid:=v_arrear.paid_amount+v_collect;

    update public.student_asset_arrears
    set paid_amount=v_new_paid,
        status=case when v_new_paid>=assessed_amount then 'PAID' else 'PARTIAL' end,
        settled_at=case when v_new_paid>=assessed_amount then now() else null end,
        waived_at=null,
        updated_at=now()
    where id=v_arrear.id;

    v_budget:=v_budget-v_collect;
    v_total_collected:=v_total_collected+v_collect;
    v_collection_count:=v_collection_count+1;
  end loop;

  return jsonb_build_object(
    'student_id',p_student_id,
    'collection_type',p_collection_type,
    'collected_total',v_total_collected,
    'collection_count',v_collection_count,
    'wallet_gold_after',v_wallet_gold,
    'remaining_outstanding',coalesce((
      select sum(a.assessed_amount-a.paid_amount)
      from public.student_asset_arrears a
      where a.student_id=p_student_id
        and a.value_token='GOLD'
        and a.status in ('UNPAID','PARTIAL')
    ),0)
  );
end;
$function$;

revoke all on function public._collect_student_gold_asset_arrears(integer,bigint,text,bigint,uuid)
from public,anon,authenticated;
grant execute on function public._collect_student_gold_asset_arrears(integer,bigint,text,bigint,uuid)
to service_role;

create or replace function public.create_transaction(
  p_student_id integer,
  p_value_token public.value_token_type,
  p_amount bigint,
  p_source_type public.transaction_source_type,
  p_source_id bigint default null,
  p_tax_amount bigint default 0,
  p_memo text default null
)
returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_student_active boolean;
  v_current_balance bigint;
  v_new_balance bigint;
  v_reserved_gold bigint := 0;
  v_equalization_debt bigint := 0;
  v_equalization_reserve bigint := 0;
  v_is_equalization_collection boolean := false;
  v_tx_id bigint;
begin
  if p_amount=0 then
    raise exception '거래 금액은 0일 수 없습니다.' using errcode='P0000';
  end if;
  if abs(p_amount)>10000000 then
    raise exception '거래 금액이 허용 범위를 초과합니다: %',p_amount using errcode='P0005';
  end if;
  if p_tax_amount<0 then
    raise exception '세금은 음수일 수 없습니다.' using errcode='P0006';
  end if;
  if length(p_memo)>500 then
    p_memo:=left(p_memo,497)||'...';
  end if;

  select classroom_id,(transferred_at is null)
    into v_classroom_id,v_student_active
  from public.students
  where id=p_student_id;

  if v_classroom_id is null then
    raise exception '학생을 찾을 수 없습니다: %',p_student_id using errcode='P0001';
  end if;
  if not v_student_active then
    raise exception '전출된 학생은 거래할 수 없습니다: %',p_student_id using errcode='P0002';
  end if;

  execute format(
    'SELECT %I FROM public.wallets WHERE student_id = $1 FOR UPDATE',
    lower(p_value_token::text)
  ) into v_current_balance using p_student_id;

  if v_current_balance is null then
    raise exception '지갑을 찾을 수 없습니다: student=%',p_student_id using errcode='P0003';
  end if;

  v_new_balance:=v_current_balance+p_amount;
  if v_new_balance<0 then
    raise exception '잔액이 부족합니다. 현재: %, 시도: %',v_current_balance,p_amount using errcode='P0004';
  end if;

  if p_value_token='GOLD'::public.value_token_type
     and p_amount<0
     and p_source_type<>'REVERSAL'::public.transaction_source_type then
    v_is_equalization_collection :=
      p_source_type='TEACHER_DEDUCT'::public.transaction_source_type
      and p_source_id is not null
      and exists(
        select 1
        from public.equalization_contribution_payments ep
        where ep.id=p_source_id
          and ep.student_id=p_student_id
          and ep.paid_amount<ep.amount
      );

    if p_source_type<>'AUCTION_PAYMENT'::public.transaction_source_type then
      select coalesce(max(b.bid_amount),0)::bigint
        into v_reserved_gold
      from public.auction_bids b
      join public.auction_items i on i.id=b.auction_item_id
      join public.auctions a on a.id=i.auction_id
      where b.student_id=p_student_id
        and b.is_winning=true
        and b.invalidated_at is null
        and i.final_status is null
        and a.status='IN_PROGRESS'
        and a.current_item_id=i.id;

      if v_new_balance<v_reserved_gold then
        raise exception '현재 최고 입찰액 % GOLD가 예약되어 있습니다. 사용 가능한 GOLD가 부족합니다.',v_reserved_gold
          using errcode='P0733';
      end if;
    end if;

    if not v_is_equalization_collection then
      select coalesce(sum(ep.amount-ep.paid_amount),0)::bigint
        into v_equalization_debt
      from public.equalization_contribution_payments ep
      where ep.student_id=p_student_id
        and ep.paid_amount<ep.amount;

      v_equalization_reserve:=least(v_equalization_debt,v_current_balance);
      if v_new_balance<v_equalization_reserve then
        raise exception '균형발전 분담금 미납액 % GOLD가 우선 징수 대상으로 예약되어 있습니다. 미납금을 먼저 납부해야 합니다.',v_equalization_debt
          using errcode='P0E44';
      end if;
    end if;
  end if;

  execute format(
    'UPDATE public.wallets SET %I = $1, updated_at = now() WHERE student_id = $2',
    lower(p_value_token::text)
  ) using v_new_balance,p_student_id;

  insert into public.transactions(
    classroom_id,student_id,value_token,amount,balance_after,
    source_type,source_id,tax_amount,memo
  ) values (
    v_classroom_id,p_student_id,p_value_token,p_amount,v_new_balance,
    p_source_type,p_source_id,p_tax_amount,p_memo
  ) returning id into v_tx_id;

  if p_value_token='GOLD'::public.value_token_type
     and p_amount>0
     and p_source_type<>'REVERSAL'::public.transaction_source_type then
    perform public._collect_student_gold_asset_arrears(
      p_student_id,p_amount,'AUTO',v_tx_id,auth.uid()
    );
  end if;

  return v_tx_id;
end;
$function$;

revoke all on function public.create_transaction(
  integer,public.value_token_type,bigint,public.transaction_source_type,bigint,bigint,text
) from public,anon,authenticated;
grant execute on function public.create_transaction(
  integer,public.value_token_type,bigint,public.transaction_source_type,bigint,bigint,text
) to service_role;

create or replace function public._reverse_asset_arrear_collection(
  p_collection_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_collection public.student_asset_arrear_collections%rowtype;
  v_arrear public.student_asset_arrears%rowtype;
  v_settlement_tx public.transactions%rowtype;
  v_reversal_tx_id bigint;
  v_new_paid bigint;
begin
  select * into v_collection
  from public.student_asset_arrear_collections c
  where c.id=p_collection_id
  for update;

  if v_collection.id is null then
    raise exception '미납 상환 이력을 찾을 수 없습니다.' using errcode='P0643';
  end if;
  if v_collection.reversed_at is not null then
    raise exception '이미 취소된 미납 상환입니다.' using errcode='P0644';
  end if;

  select * into v_arrear
  from public.student_asset_arrears a
  where a.id=v_collection.arrear_id
  for update;

  if v_arrear.id is null then
    raise exception '연결된 미납 내역을 찾을 수 없습니다.' using errcode='P0645';
  end if;
  if v_arrear.paid_amount<v_collection.amount then
    raise exception '미납 상환 원장이 일치하지 않습니다.' using errcode='P0646';
  end if;

  select * into v_settlement_tx
  from public.transactions t
  where t.id=v_collection.transaction_id
  for update;

  if v_settlement_tx.id is null then
    raise exception '미납 상환 거래를 찾을 수 없습니다.' using errcode='P0647';
  end if;
  if v_settlement_tx.is_reversed then
    raise exception '미납 상환 거래가 이미 취소되었습니다.' using errcode='P0644';
  end if;

  v_reversal_tx_id:=public.create_transaction(
    v_collection.student_id,
    'GOLD'::public.value_token_type,
    v_collection.amount,
    'REVERSAL'::public.transaction_source_type,
    v_collection.transaction_id,
    0,
    format('[미납 상환 취소] %s · 사유: %s',v_arrear.reason,p_reason)
  );

  update public.transactions
  set is_reversed=true,
      reversed_by_transaction_id=v_reversal_tx_id,
      reversed_at=now(),
      reversal_reason=p_reason
  where id=v_collection.transaction_id;

  v_new_paid:=v_arrear.paid_amount-v_collection.amount;

  update public.student_asset_arrears
  set paid_amount=v_new_paid,
      status=case when v_new_paid<=0 then 'UNPAID' else 'PARTIAL' end,
      settled_at=null,
      waived_at=null,
      updated_at=now()
  where id=v_arrear.id;

  update public.student_asset_arrear_collections
  set reversed_at=now(),
      reversal_transaction_id=v_reversal_tx_id
  where id=v_collection.id;

  return v_reversal_tx_id;
end;
$function$;

revoke all on function public._reverse_asset_arrear_collection(bigint,text)
from public,anon,authenticated;
grant execute on function public._reverse_asset_arrear_collection(bigint,text)
to service_role;

create or replace function public._reverse_asset_arrear_auto_collections(
  p_source_transaction_id bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_collection_id bigint;
  v_count integer:=0;
  v_total bigint:=0;
  v_amount bigint;
begin
  for v_collection_id,v_amount in
    select c.id,c.amount
    from public.student_asset_arrear_collections c
    where c.source_transaction_id=p_source_transaction_id
      and c.collection_type='AUTO'
      and c.reversed_at is null
    order by c.id desc
    for update
  loop
    perform public._reverse_asset_arrear_collection(v_collection_id,p_reason);
    v_count:=v_count+1;
    v_total:=v_total+v_amount;
  end loop;

  return jsonb_build_object(
    'source_transaction_id',p_source_transaction_id,
    'reversed_collection_count',v_count,
    'reversed_amount',v_total
  );
end;
$function$;

revoke all on function public._reverse_asset_arrear_auto_collections(bigint,text)
from public,anon,authenticated;
grant execute on function public._reverse_asset_arrear_auto_collections(bigint,text)
to service_role;

create or replace function public.reverse_transaction(
  p_original_tx_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_original public.transactions%rowtype;
  v_reversal_tx_id bigint;
  v_reason text;
  v_welfare_balance bigint:=0;
  v_asset_arrear_collection_id bigint;
begin
  v_reason:=btrim(coalesce(p_reason,''));
  if char_length(v_reason)<2 or char_length(v_reason)>200 then
    raise exception '취소 사유는 2자 이상 200자 이하로 입력해주세요.' using errcode='P0624';
  end if;

  select * into v_original
  from public.transactions
  where id=p_original_tx_id
  for update;

  if v_original.id is null then
    raise exception '원본 거래를 찾을 수 없습니다.' using errcode='P0030';
  end if;
  if v_original.is_reversed then
    raise exception '이미 취소된 거래입니다.' using errcode='P0031';
  end if;
  if v_original.source_type='REVERSAL'::public.transaction_source_type then
    raise exception '취소 거래 자체는 다시 취소할 수 없습니다.' using errcode='P0623';
  end if;

  select c.id into v_asset_arrear_collection_id
  from public.student_asset_arrear_collections c
  where c.transaction_id=v_original.id
    and c.reversed_at is null
  order by c.id desc
  limit 1
  for update;

  if v_asset_arrear_collection_id is not null then
    return public._reverse_asset_arrear_collection(v_asset_arrear_collection_id,v_reason);
  end if;

  if v_original.source_type='TEACHER_GRANT'::public.transaction_source_type
     and v_original.value_token='GOLD'::public.value_token_type
     and coalesce(v_original.tax_amount,0)>0 then
    select coalesce((cs.setting_value)::text::bigint,0)
    into v_welfare_balance
    from public.classroom_settings cs
    where cs.classroom_id=v_original.classroom_id
      and cs.setting_key='welfare_balance'
    for update;

    if coalesce(v_welfare_balance,0)<v_original.tax_amount then
      raise exception '이 지급의 세금이 이미 복지기금에서 사용되어 현재 잔액으로는 거래를 취소할 수 없습니다.'
        using errcode='P0637';
    end if;
  end if;

  if v_original.value_token='GOLD'::public.value_token_type
     and v_original.amount>0 then
    perform public._reverse_asset_arrear_auto_collections(v_original.id,v_reason);
  end if;

  v_reversal_tx_id:=public.create_transaction(
    v_original.student_id,
    v_original.value_token,
    -v_original.amount,
    'REVERSAL',
    p_original_tx_id,
    0,
    format('[거래 취소] %s · 사유: %s',
      coalesce(v_original.memo,'거래 #'||v_original.id::text),v_reason)
  );

  update public.transactions
  set is_reversed=true,
      reversed_by_transaction_id=v_reversal_tx_id,
      reversed_at=now(),
      reversal_reason=v_reason
  where id=p_original_tx_id;

  if v_original.source_type='TEACHER_GRANT'::public.transaction_source_type
     and v_original.value_token='GOLD'::public.value_token_type
     and coalesce(v_original.tax_amount,0)>0 then
    update public.classroom_settings
    set setting_value=to_jsonb(v_welfare_balance-v_original.tax_amount),
        updated_at=now()
    where classroom_id=v_original.classroom_id
      and setting_key='welfare_balance';
  end if;

  update public.student_asset_arrears
  set status='WAIVED',
      waived_at=now(),
      settled_at=now(),
      updated_at=now()
  where initial_transaction_id=p_original_tx_id
    and status in ('UNPAID','PARTIAL');

  return v_reversal_tx_id;
end;
$function$;

revoke all on function public.reverse_transaction(bigint,text) from public,anon,authenticated;
grant execute on function public.reverse_transaction(bigint,text) to service_role;

create or replace function public.teacher_get_asset_arrears_state(
  p_classroom_id integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_result jsonb;
begin
  perform public.ensure_teacher_role();

  if p_classroom_id is null
     or p_classroom_id is distinct from public.current_classroom_id() then
    raise exception '담당 학급의 미납금만 조회할 수 있습니다.' using errcode='P0648';
  end if;

  with arrear_rows as (
    select
      s.id as student_id,
      s.name as student_name,
      s.brand_name,
      coalesce(w.gold,0)::bigint as current_gold,
      count(a.id)::integer as arrear_count,
      sum(a.assessed_amount-a.paid_amount)::bigint as outstanding_total,
      jsonb_agg(
        jsonb_build_object(
          'arrear_id',a.id,
          'reason',a.reason,
          'assessed_amount',a.assessed_amount,
          'paid_amount',a.paid_amount,
          'outstanding_amount',a.assessed_amount-a.paid_amount,
          'status',a.status,
          'created_at',a.created_at
        )
        order by a.created_at,a.id
      ) as details
    from public.student_asset_arrears a
    join public.students s on s.id=a.student_id
    left join public.wallets w on w.student_id=s.id
    where a.classroom_id=p_classroom_id
      and a.value_token='GOLD'::public.value_token_type
      and a.status in ('UNPAID','PARTIAL')
      and a.paid_amount<a.assessed_amount
      and s.transferred_at is null
    group by s.id,s.name,s.brand_name,w.gold
  )
  select jsonb_build_object(
    'classroom_id',p_classroom_id,
    'student_count',count(*)::integer,
    'total_outstanding',coalesce(sum(r.outstanding_total),0)::bigint,
    'students',coalesce(
      jsonb_agg(to_jsonb(r) order by r.student_name,r.student_id)
        filter(where r.student_id is not null),
      '[]'::jsonb
    )
  )
  into v_result
  from arrear_rows r;

  return coalesce(v_result,jsonb_build_object(
    'classroom_id',p_classroom_id,
    'student_count',0,
    'total_outstanding',0,
    'students','[]'::jsonb
  ));
end;
$function$;

revoke all on function public.teacher_get_asset_arrears_state(integer) from public,anon;
grant execute on function public.teacher_get_asset_arrears_state(integer) to authenticated,service_role;

create or replace function public.teacher_collect_student_asset_arrears(
  p_classroom_id integer,
  p_student_id integer
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_current_gold bigint:=0;
  v_reserved_auction bigint:=0;
  v_equalization_debt bigint:=0;
  v_equalization_reserve bigint:=0;
  v_min_balance bigint:=0;
  v_available_gold bigint:=0;
  v_result jsonb;
begin
  perform public.ensure_teacher_role();

  if p_classroom_id is null
     or p_classroom_id is distinct from public.current_classroom_id() then
    raise exception '담당 학급의 미납금만 징수할 수 있습니다.' using errcode='P0649';
  end if;

  if not exists(
    select 1
    from public.students s
    where s.id=p_student_id
      and s.classroom_id=p_classroom_id
      and s.transferred_at is null
  ) then
    raise exception '현재 학급의 활성 학생을 찾을 수 없습니다.' using errcode='P0650';
  end if;

  select coalesce(w.gold,0)::bigint
    into v_current_gold
  from public.wallets w
  where w.student_id=p_student_id
  for update;

  select coalesce(max(b.bid_amount),0)::bigint
    into v_reserved_auction
  from public.auction_bids b
  join public.auction_items i on i.id=b.auction_item_id
  join public.auctions a on a.id=i.auction_id
  where b.student_id=p_student_id
    and b.is_winning=true
    and b.invalidated_at is null
    and i.final_status is null
    and a.status='IN_PROGRESS'
    and a.current_item_id=i.id;

  select coalesce(sum(ep.amount-ep.paid_amount),0)::bigint
    into v_equalization_debt
  from public.equalization_contribution_payments ep
  where ep.student_id=p_student_id
    and ep.paid_amount<ep.amount;

  v_equalization_reserve:=least(v_equalization_debt,v_current_gold);
  v_min_balance:=greatest(v_reserved_auction,v_equalization_reserve);
  v_available_gold:=greatest(v_current_gold-v_min_balance,0);

  v_result:=public._collect_student_gold_asset_arrears(
    p_student_id,v_available_gold,'MANUAL',null,auth.uid()
  );

  return v_result || jsonb_build_object(
    'current_gold_before',v_current_gold,
    'auction_reserved_gold',v_reserved_auction,
    'equalization_reserved_gold',v_equalization_reserve,
    'available_gold_before',v_available_gold
  );
end;
$function$;

revoke all on function public.teacher_collect_student_asset_arrears(integer,integer)
from public,anon;
grant execute on function public.teacher_collect_student_asset_arrears(integer,integer)
to authenticated,service_role;


COMMIT;
