-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4.1 안정화 패치
-- 2026-08-08
-- * 돌발퀘스트: 학생 완료요청 -> 교사 승인 -> 보상
-- * 과제 공개 알림
-- * 과거 출석 조회/입력/정정 + 이후 연속출석/보상 재계산
-- * 기록실 23:59 KST 자동 스냅샷
-- * Realtime 보강
-- ============================================================================
BEGIN;

-- --------------------------------------------------------------------------
-- F4B. 돌발 퀘스트 승인 워크플로
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.emergency_quest_requests(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 quest_id bigint NOT NULL REFERENCES public.emergency_quests(id) ON DELETE CASCADE,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 student_id integer NOT NULL REFERENCES public.students(id),
 status varchar(12) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED')),
 note text,
 requested_at timestamptz NOT NULL DEFAULT now(),
 reviewed_at timestamptz,
 reviewed_by uuid,
 UNIQUE(quest_id,student_id)
);
CREATE INDEX IF NOT EXISTS idx_emergency_quest_requests_pending ON public.emergency_quest_requests(classroom_id,status,requested_at);
ALTER TABLE public.emergency_quest_requests ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='emergency_quest_requests' AND policyname='emergency_quest_requests_select') THEN
  CREATE POLICY emergency_quest_requests_select ON public.emergency_quest_requests FOR SELECT TO authenticated
   USING(student_id=public.current_student_id() OR public.is_teacher_or_admin());
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.request_emergency_quest_completion(p_student_id integer,p_quest_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE q public.emergency_quests%ROWTYPE; v_class integer; v_id bigint; v_status text;
BEGIN
 PERFORM public.ensure_self_or_teacher(p_student_id);
 SELECT classroom_id INTO v_class FROM public.students WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4B] active student not found' USING ERRCODE='P4B25'; END IF;
 SELECT * INTO q FROM public.emergency_quests WHERE id=p_quest_id;
 IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
 IF q.classroom_id<>v_class THEN RAISE EXCEPTION '[F4B] quest belongs to another classroom' USING ERRCODE='P4B26'; END IF;
 IF q.status<>'ACTIVE' OR now()<q.starts_at OR now()>=q.expires_at THEN RAISE EXCEPTION '[F4B] quest is not requestable' USING ERRCODE='P4B27'; END IF;
 IF EXISTS(SELECT 1 FROM public.emergency_quest_completions WHERE quest_id=p_quest_id AND student_id=p_student_id) THEN
  RAISE EXCEPTION '[F4B] quest already completed' USING ERRCODE='P4B28';
 END IF;
 SELECT status,id INTO v_status,v_id FROM public.emergency_quest_requests WHERE quest_id=p_quest_id AND student_id=p_student_id FOR UPDATE;
 IF v_id IS NULL THEN
  INSERT INTO public.emergency_quest_requests(quest_id,classroom_id,student_id) VALUES(p_quest_id,v_class,p_student_id) RETURNING id INTO v_id;
 ELSIF v_status='PENDING' THEN
  RETURN v_id;
 ELSIF v_status='APPROVED' THEN
  RAISE EXCEPTION '[F4B] quest already approved' USING ERRCODE='P4B28';
 ELSE
  UPDATE public.emergency_quest_requests SET status='PENDING',note=NULL,requested_at=now(),reviewed_at=NULL,reviewed_by=NULL WHERE id=v_id;
 END IF;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public._grant_emergency_quest_after_approval(p_student_id integer,p_quest_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE q public.emergency_quests%ROWTYPE; v_class integer; v_completion bigint; v_gold bigint; v_bv bigint;
BEGIN
 -- 브라우저에 공개하지 않는 내부 함수. 요청 시각의 유효성은 review RPC가 검증한다.
 SELECT classroom_id INTO v_class FROM public.students WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4B] active student not found' USING ERRCODE='P4B25'; END IF;
 SELECT * INTO q FROM public.emergency_quests WHERE id=p_quest_id FOR UPDATE;
 IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
 IF q.classroom_id<>v_class THEN RAISE EXCEPTION '[F4B] quest belongs to another classroom' USING ERRCODE='P4B26'; END IF;
 INSERT INTO public.emergency_quest_completions(quest_id,classroom_id,student_id) VALUES(q.id,v_class,p_student_id) RETURNING id INTO v_completion;
 IF q.reward_gold>0 THEN v_gold:=public.create_transaction(p_student_id,'GOLD',q.reward_gold,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트] %s',q.title)); END IF;
 IF q.reward_bv>0 THEN v_bv:=public.create_transaction(p_student_id,'BV',q.reward_bv,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트 명예] %s',q.title)); END IF;
 UPDATE public.emergency_quest_completions SET gold_transaction_id=v_gold,bv_transaction_id=v_bv WHERE id=v_completion;
 PERFORM public.send_mail(p_student_id,'SYSTEM',NULL,NULL,'⚡ 돌발 퀘스트 완료',format('"%s" 완료 요청이 승인되어 보상이 지급되었습니다.',q.title),'REWARD','DAILY_QUEST',v_completion);
 PERFORM public.push_activity_feed(v_class,'OTHER',p_student_id,jsonb_build_object('message','돌발 퀘스트 완료 승인','quest_title',q.title),'PUBLIC');
 RETURN v_completion;
EXCEPTION WHEN unique_violation THEN
 RAISE EXCEPTION '[F4B] quest already completed' USING ERRCODE='P4B28';
END $$;
REVOKE ALL ON FUNCTION public._grant_emergency_quest_after_approval(integer,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public._grant_emergency_quest_after_approval(integer,bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.teacher_review_emergency_quest_request(p_request_id bigint,p_approve boolean,p_note text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE r public.emergency_quest_requests%ROWTYPE; q public.emergency_quests%ROWTYPE; v_completion bigint;
BEGIN
 PERFORM public.ensure_teacher_role();
 SELECT * INTO r FROM public.emergency_quest_requests WHERE id=p_request_id FOR UPDATE;
 IF r.id IS NULL THEN RAISE EXCEPTION '[F4B] quest request not found' USING ERRCODE='P4B29'; END IF;
 IF NOT public.is_classroom_member(r.classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
 IF r.status<>'PENDING' THEN RAISE EXCEPTION '[F4B] quest request already reviewed' USING ERRCODE='P4B29'; END IF;
 SELECT * INTO q FROM public.emergency_quests WHERE id=r.quest_id FOR UPDATE;
 IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
 -- 교사가 나중에 승인해도, 학생이 퀘스트 유효시간 안에 요청했다면 승인 가능하다.
 IF r.requested_at<q.starts_at OR r.requested_at>=q.expires_at THEN RAISE EXCEPTION '[F4B] completion request was outside quest window' USING ERRCODE='P4B27'; END IF;
 IF p_approve THEN
  v_completion:=public._grant_emergency_quest_after_approval(r.student_id,r.quest_id);
  UPDATE public.emergency_quest_requests SET status='APPROVED',note=nullif(btrim(coalesce(p_note,'')),''),reviewed_at=now(),reviewed_by=auth.uid() WHERE id=r.id;
 ELSE
  UPDATE public.emergency_quest_requests SET status='REJECTED',note=nullif(btrim(coalesce(p_note,'')),''),reviewed_at=now(),reviewed_by=auth.uid() WHERE id=r.id;
  v_completion:=0;
 END IF;
 RETURN v_completion;
END $$;

-- 학생은 더 이상 즉시 완료 RPC를 직접 실행할 수 없다.
REVOKE ALL ON FUNCTION public.complete_emergency_quest(integer,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.complete_emergency_quest(integer,bigint) TO service_role;
REVOKE ALL ON FUNCTION public.request_emergency_quest_completion(integer,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.request_emergency_quest_completion(integer,bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_review_emergency_quest_request(bigint,boolean,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_review_emergency_quest_request(bigint,boolean,text) TO authenticated,service_role;
REVOKE ALL ON TABLE public.emergency_quest_requests FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.emergency_quest_requests FROM authenticated;
GRANT SELECT ON TABLE public.emergency_quest_requests TO authenticated;
GRANT ALL ON TABLE public.emergency_quest_requests TO service_role;

-- --------------------------------------------------------------------------
-- F4C. 과제 공개 시 중요 알림 생성
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_create_assignment(
 p_classroom_id integer,p_title text,p_description text,p_subject text,p_due_at timestamptz,
 p_max_score integer,p_base_reward_gold integer,p_full_score_reward_bv integer,p_publish_now boolean
) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id integer; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION '[F4C] assignment title invalid' USING ERRCODE='P4C30'; END IF;
 IF char_length(coalesce(p_description,''))>5000 OR char_length(coalesce(p_subject,''))>50 THEN RAISE EXCEPTION '[F4C] assignment text too long' USING ERRCODE='P4C31'; END IF;
 IF p_due_at<=now() THEN RAISE EXCEPTION '[F4C] assignment due date must be future' USING ERRCODE='P4C32'; END IF;
 IF p_max_score NOT BETWEEN 1 AND 1000 OR p_base_reward_gold NOT BETWEEN 0 AND 10000 OR p_full_score_reward_bv NOT BETWEEN 0 AND 10000 THEN RAISE EXCEPTION '[F4C] assignment reward/score invalid' USING ERRCODE='P4C33'; END IF;
 INSERT INTO public.assignments(classroom_id,title,description,subject,published_at,due_at,max_score,base_reward_gold,full_score_reward_bv,auto_reward_on_submit,status,created_by)
 VALUES(p_classroom_id,btrim(p_title),nullif(btrim(coalesce(p_description,'')),''),nullif(btrim(coalesce(p_subject,'')),''),CASE WHEN p_publish_now THEN now() ELSE NULL END,p_due_at,p_max_score,p_base_reward_gold,p_full_score_reward_bv,true,CASE WHEN p_publish_now THEN 'PUBLISHED'::public.assignment_status ELSE 'DRAFT'::public.assignment_status END,auth.uid()) RETURNING id INTO v_id;
 IF p_publish_now THEN
  PERFORM public.broadcast_global_alert(p_classroom_id,'GENERAL',format('📝 새 과제가 공개되었습니다: %s',btrim(p_title)),'📝',NULL,'ASSIGNMENT',v_id,168);
 END IF;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_set_assignment_status(p_assignment_id integer,p_status public.assignment_status)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_class integer; v_old public.assignment_status; v_title text; BEGIN
 PERFORM public.ensure_teacher_role();
 SELECT classroom_id,status,title INTO v_class,v_old,v_title FROM public.assignments WHERE id=p_assignment_id FOR UPDATE;
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4C] assignment not found' USING ERRCODE='P4C34'; END IF;
 IF NOT public.is_classroom_member(v_class) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF p_status='PUBLISHED'::public.assignment_status AND EXISTS(SELECT 1 FROM public.assignments WHERE id=p_assignment_id AND due_at<=now()) THEN RAISE EXCEPTION '[F4C] cannot publish an assignment whose due date has passed' USING ERRCODE='P4C35'; END IF;
 UPDATE public.assignments SET status=p_status,published_at=CASE WHEN p_status='PUBLISHED' AND published_at IS NULL THEN now() ELSE published_at END,updated_at=now() WHERE id=p_assignment_id;
 IF p_status='PUBLISHED'::public.assignment_status AND v_old<>'PUBLISHED'::public.assignment_status THEN
  PERFORM public.broadcast_global_alert(v_class,'GENERAL',format('📝 새 과제가 공개되었습니다: %s',v_title),'📝',NULL,'ASSIGNMENT',p_assignment_id,168);
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- F4C. 과거 출석 안전 정정: 대상 날짜 이후 출석/마일스톤을 역분개 후 순서대로 재생
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public._teacher_rebuild_attendance_from_date(
 p_student_id integer,p_from_date date,p_override_status public.attendance_status,p_reason text
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE a record; m record; v_target bigint; v_today date:=timezone('Asia/Seoul',now())::date;
BEGIN
 IF p_from_date>v_today THEN RAISE EXCEPTION '[F4C] future attendance not allowed' USING ERRCODE='P4C40'; END IF;
 CREATE TEMP TABLE IF NOT EXISTS pg_temp.f41_attendance_replay(attendance_date date,status public.attendance_status) ON COMMIT DROP;
 TRUNCATE pg_temp.f41_attendance_replay;
 INSERT INTO pg_temp.f41_attendance_replay(attendance_date,status)
 SELECT attendance_date,status FROM public.attendances WHERE student_id=p_student_id AND attendance_date>p_from_date ORDER BY attendance_date;
 FOR a IN SELECT * FROM public.attendances WHERE student_id=p_student_id AND attendance_date>=p_from_date FOR UPDATE LOOP
  IF a.transaction_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=a.transaction_id AND NOT is_reversed) THEN PERFORM public.reverse_transaction(a.transaction_id,'출석 과거기록 정정: '||p_reason); END IF;
 END LOOP;
 FOR m IN SELECT * FROM public.attendance_milestones WHERE student_id=p_student_id AND achieved_on>=p_from_date FOR UPDATE LOOP
  IF m.transaction_id_gold IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_gold AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_gold,'출석 과거기록 정정: '||p_reason); END IF;
  IF m.transaction_id_bv IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_bv AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_bv,'출석 과거기록 정정: '||p_reason); END IF;
  IF m.transaction_id_crystal IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_crystal AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_crystal,'출석 과거기록 정정: '||p_reason); END IF;
 END LOOP;
 DELETE FROM public.attendance_milestones WHERE student_id=p_student_id AND achieved_on>=p_from_date;
 DELETE FROM public.attendances WHERE student_id=p_student_id AND attendance_date>=p_from_date;
 v_target:=public.record_attendance(p_student_id,p_from_date,p_override_status);
 FOR a IN SELECT * FROM pg_temp.f41_attendance_replay ORDER BY attendance_date LOOP
  PERFORM public.record_attendance(p_student_id,a.attendance_date,a.status);
 END LOOP;
 RETURN v_target;
END $$;
REVOKE ALL ON FUNCTION public._teacher_rebuild_attendance_from_date(integer,date,public.attendance_status,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public._teacher_rebuild_attendance_from_date(integer,date,public.attendance_status,text) TO service_role;

CREATE OR REPLACE FUNCTION public.teacher_correct_attendance(p_attendance_id bigint,p_new_status public.attendance_status,p_reason text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE a public.attendances%ROWTYPE; v_reason text; BEGIN
 PERFORM public.ensure_teacher_role(); v_reason:=btrim(coalesce(p_reason,''));
 IF char_length(v_reason)<2 OR char_length(v_reason)>200 THEN RAISE EXCEPTION '[F4C] correction reason must be 2-200 chars' USING ERRCODE='P4C44'; END IF;
 SELECT * INTO a FROM public.attendances WHERE id=p_attendance_id FOR UPDATE;
 IF a.id IS NULL THEN RAISE EXCEPTION '[F4C] attendance not found' USING ERRCODE='P4C45'; END IF;
 IF NOT public.is_classroom_member(a.classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF a.status=p_new_status THEN RETURN a.id; END IF;
 RETURN public._teacher_rebuild_attendance_from_date(a.student_id,a.attendance_date,p_new_status,v_reason);
END $$;

CREATE OR REPLACE FUNCTION public.teacher_record_attendance_bulk(p_classroom_id integer,p_attendance_date date,p_entries jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE e jsonb; v_student integer; v_status public.attendance_status; v_id bigint; v_recorded jsonb:='[]'::jsonb; v_skipped jsonb:='[]'::jsonb; v_today date:=timezone('Asia/Seoul',now())::date;
BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF p_attendance_date>v_today THEN RAISE EXCEPTION '[F4C] future attendance not allowed' USING ERRCODE='P4C40'; END IF;
 IF jsonb_typeof(p_entries)<>'array' OR jsonb_array_length(p_entries)<1 OR jsonb_array_length(p_entries)>100 THEN RAISE EXCEPTION '[F4C] attendance entries must contain 1-100 rows' USING ERRCODE='P4C41'; END IF;
 FOR e IN SELECT * FROM jsonb_array_elements(p_entries) LOOP
  v_student:=(e->>'student_id')::integer; v_status:=(e->>'status')::public.attendance_status;
  IF NOT EXISTS(SELECT 1 FROM public.students WHERE id=v_student AND classroom_id=p_classroom_id AND transferred_at IS NULL AND role='STUDENT') THEN RAISE EXCEPTION '[F4C] invalid attendance student %',v_student USING ERRCODE='P4C43'; END IF;
  IF EXISTS(SELECT 1 FROM public.attendances WHERE student_id=v_student AND attendance_date=p_attendance_date) THEN
   v_skipped:=v_skipped||jsonb_build_array(jsonb_build_object('student_id',v_student,'reason','already_recorded'));
  ELSE
   v_id:=public._teacher_rebuild_attendance_from_date(v_student,p_attendance_date,v_status,'과거/당일 출석 입력');
   v_recorded:=v_recorded||jsonb_build_array(jsonb_build_object('student_id',v_student,'attendance_id',v_id,'status',v_status));
  END IF;
 END LOOP;
 RETURN jsonb_build_object('recorded',v_recorded,'skipped',v_skipped);
END $$;

REVOKE ALL ON FUNCTION public.teacher_correct_attendance(bigint,public.attendance_status,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_correct_attendance(bigint,public.attendance_status,text) TO authenticated,service_role;

-- --------------------------------------------------------------------------
-- F4D. 23:59 KST 자동 기록 스냅샷
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.refresh_all_classroom_records_kst()
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE c record; v_date date:=timezone('Asia/Seoul',now())::date; v_count integer:=0; BEGIN
 FOR c IN SELECT DISTINCT classroom_id FROM public.students WHERE role='STUDENT' AND transferred_at IS NULL LOOP
  PERFORM public.calculate_daily_statistics(c.classroom_id,v_date);
  PERFORM public.calculate_rankings(c.classroom_id,v_date);
  v_count:=v_count+1;
 END LOOP;
 RETURN v_count;
END $$;
REVOKE ALL ON FUNCTION public.refresh_all_classroom_records_kst() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_all_classroom_records_kst() TO service_role;

DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
  IF EXISTS(SELECT 1 FROM cron.job WHERE jobname='brand_feature4_daily_records_2359_kst') THEN
   PERFORM cron.unschedule('brand_feature4_daily_records_2359_kst');
  END IF;
  -- pg_cron 기본 UTC 기준: 14:59 UTC = 23:59 KST
  PERFORM cron.schedule('brand_feature4_daily_records_2359_kst','59 14 * * *','SELECT public.refresh_all_classroom_records_kst();');
 ELSE
  RAISE NOTICE '[F4.1] pg_cron not enabled; daily records schedule skipped';
 END IF;
EXCEPTION WHEN OTHERS THEN RAISE NOTICE '[F4.1] records cron scheduling skipped: %',SQLERRM; END $$;

-- Realtime 보강
DO $$ DECLARE t text; BEGIN
 IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
  FOREACH t IN ARRAY ARRAY['emergency_quest_requests','assignments'] LOOP
   IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN
    EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
   END IF;
  END LOOP;
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- Feature 4.1 진단: 기존 F4 진단 결과에 안정화 패치 상태를 병합
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_feature4_1_health_check()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE
 v_base jsonb;
 v_cron boolean:=false;
BEGIN
 PERFORM public.ensure_teacher_role();
 v_base:=public.teacher_feature4_health_check();
 IF EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
  BEGIN
   SELECT EXISTS(SELECT 1 FROM cron.job WHERE jobname='brand_feature4_daily_records_2359_kst') INTO v_cron;
  EXCEPTION WHEN OTHERS THEN v_cron:=false; END;
 END IF;
 RETURN v_base || jsonb_build_object('F4.1',jsonb_build_object(
  'quest_request_table',to_regclass('public.emergency_quest_requests') IS NOT NULL,
  'quest_request_rpc',to_regprocedure('public.request_emergency_quest_completion(integer,bigint)') IS NOT NULL,
  'quest_review_rpc',to_regprocedure('public.teacher_review_emergency_quest_request(bigint,boolean,text)') IS NOT NULL,
  'instant_complete_closed_to_students',NOT has_function_privilege('authenticated','public.complete_emergency_quest(integer,bigint)','EXECUTE'),
  'historical_attendance_edit',to_regprocedure('public.teacher_correct_attendance(bigint,attendance_status,text)') IS NOT NULL,
  'assignment_realtime',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='assignments'),
  'quest_request_realtime',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergency_quest_requests'),
  'records_cron_2359_kst',v_cron
 ));
END $$;
REVOKE ALL ON FUNCTION public.teacher_feature4_1_health_check() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_feature4_1_health_check() TO authenticated,service_role;

COMMIT;
-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4.1.1 UI / Realtime / 운영 안정화 Hotfix
-- 2026-08-08
--
-- 목적
-- 1) Feature 4.1 완료요청 테이블을 다시 보장하고 PostgREST schema cache 갱신
-- 2) 완료요청/과제 Realtime publication 보강
-- 3) 교사 BV + GOLD 동시 지급을 단일 DB 트랜잭션으로 제공
-- ============================================================================
BEGIN;

-- --------------------------------------------------------------------------
-- F4B. 완료요청 테이블 / ACL 재보장
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.emergency_quest_requests(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 quest_id bigint NOT NULL REFERENCES public.emergency_quests(id) ON DELETE CASCADE,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 student_id integer NOT NULL REFERENCES public.students(id),
 status varchar(12) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED')),
 note text,
 requested_at timestamptz NOT NULL DEFAULT now(),
 reviewed_at timestamptz,
 reviewed_by uuid,
 UNIQUE(quest_id,student_id)
);
CREATE INDEX IF NOT EXISTS idx_emergency_quest_requests_pending
 ON public.emergency_quest_requests(classroom_id,status,requested_at);
ALTER TABLE public.emergency_quest_requests ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
 IF NOT EXISTS(
   SELECT 1 FROM pg_policies
   WHERE schemaname='public'
     AND tablename='emergency_quest_requests'
     AND policyname='emergency_quest_requests_select'
 ) THEN
  CREATE POLICY emergency_quest_requests_select
   ON public.emergency_quest_requests
   FOR SELECT TO authenticated
   USING(student_id=public.current_student_id() OR public.is_teacher_or_admin());
 END IF;
END $$;
REVOKE ALL ON TABLE public.emergency_quest_requests FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER
 ON TABLE public.emergency_quest_requests FROM authenticated;
GRANT SELECT ON TABLE public.emergency_quest_requests TO authenticated;
GRANT ALL ON TABLE public.emergency_quest_requests TO service_role;

-- 완료요청 RPC가 없는 상태라면 4.1 migration이 적용되지 않은 것이므로 조용히 잘못 동작하지 않게 명확히 실패시킨다.
DO $$
BEGIN
 IF to_regprocedure('public.request_emergency_quest_completion(integer,bigint)') IS NULL
    OR to_regprocedure('public.teacher_review_emergency_quest_request(bigint,boolean,text)') IS NULL THEN
  RAISE EXCEPTION '[F4.1.1] Feature 4.1 DB 함수가 없습니다. 20260808_01_feature4_1_stabilization.sql을 먼저 적용한 뒤 이 migration을 다시 실행하세요.';
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- Feature 1 보강. BV + GOLD 동시 지급
-- 반드시 하나의 SECURITY DEFINER 함수/트랜잭션 안에서 처리한다.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_grant_student_assets_combined(
  p_student_ids integer[],
  p_bv_amount bigint,
  p_gold_amount bigint,
  p_reason text
)
RETURNS TABLE(
  student_id integer,
  bv_transaction_id bigint,
  gold_transaction_id bigint,
  new_bv bigint,
  new_gold bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_teacher_classroom_id integer;
  v_requested_count integer;
  v_unique_count integer;
  v_valid_count integer;
  v_student_id integer;
  v_bv_tx bigint;
  v_gold_tx bigint;
  v_new_bv bigint;
  v_new_gold bigint;
  v_reason text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.' USING ERRCODE='P0610';
  END IF;
  PERFORM public.ensure_teacher_role();

  v_requested_count := cardinality(p_student_ids);
  IF p_student_ids IS NULL OR v_requested_count IS NULL OR v_requested_count < 1 THEN
    RAISE EXCEPTION '대상 학생을 한 명 이상 선택해주세요.' USING ERRCODE='P0611';
  END IF;
  IF v_requested_count > 100 THEN
    RAISE EXCEPTION '한 번에 처리할 수 있는 학생은 최대 100명입니다.' USING ERRCODE='P0612';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(p_student_ids) AS x(id) WHERE x.id IS NULL) THEN
    RAISE EXCEPTION '학생 목록에 잘못된 값이 포함되어 있습니다.' USING ERRCODE='P0613';
  END IF;
  SELECT count(DISTINCT x.id) INTO v_unique_count FROM unnest(p_student_ids) AS x(id);
  IF v_unique_count <> v_requested_count THEN
    RAISE EXCEPTION '같은 학생이 중복 선택되어 있습니다.' USING ERRCODE='P0613';
  END IF;

  IF p_bv_amount IS NULL OR p_gold_amount IS NULL
     OR p_bv_amount < 0 OR p_gold_amount < 0
     OR p_bv_amount > 10000000 OR p_gold_amount > 10000000
     OR (p_bv_amount = 0 AND p_gold_amount = 0) THEN
    RAISE EXCEPTION 'BV/골드는 각각 0~10,000,000 정수이며 둘 중 하나 이상은 1 이상이어야 합니다.' USING ERRCODE='P0614';
  END IF;

  v_reason := btrim(coalesce(p_reason,''));
  IF char_length(v_reason) < 2 OR char_length(v_reason) > 200 THEN
    RAISE EXCEPTION '사유는 2자 이상 200자 이하로 입력해주세요.' USING ERRCODE='P0615';
  END IF;

  SELECT s.classroom_id
    INTO v_teacher_classroom_id
    FROM public.students AS s
   WHERE s.user_id = auth.uid()
     AND s.transferred_at IS NULL
     AND s.role IN ('TEACHER','ADMIN')
   ORDER BY CASE WHEN s.role='TEACHER' THEN 0 ELSE 1 END, s.id
   LIMIT 1;

  IF v_teacher_classroom_id IS NULL THEN
    SELECT c.id INTO v_teacher_classroom_id
      FROM public.classrooms AS c
     WHERE c.teacher_user_id=auth.uid() AND c.is_active=true
     ORDER BY c.id LIMIT 1;
  END IF;
  IF v_teacher_classroom_id IS NULL THEN
    RAISE EXCEPTION '담당 학급을 확인할 수 없습니다.' USING ERRCODE='P0616';
  END IF;

  SELECT count(*) INTO v_valid_count
    FROM public.students AS s
   WHERE s.id = ANY(p_student_ids)
     AND s.classroom_id = v_teacher_classroom_id
     AND s.transferred_at IS NULL
     AND s.role IN ('STUDENT','STUDENT_LEADER','GUARD');
  IF v_valid_count <> v_requested_count THEN
    RAISE EXCEPTION '선택한 학생 중 담당 학급의 활성 학생이 아닌 대상이 있습니다.' USING ERRCODE='P0617';
  END IF;

  FOR v_student_id IN SELECT x.id FROM unnest(p_student_ids) AS x(id) ORDER BY x.id LOOP
    v_bv_tx := NULL;
    v_gold_tx := NULL;

    IF p_bv_amount > 0 THEN
      v_bv_tx := public.create_transaction(
        v_student_id,
        'BV'::public.value_token_type,
        p_bv_amount,
        'TEACHER_GRANT'::public.transaction_source_type,
        NULL,
        0,
        '[교사 BV+골드 동시 지급/BV] ' || v_reason
      );
    END IF;

    IF p_gold_amount > 0 THEN
      v_gold_tx := public.create_transaction(
        v_student_id,
        'GOLD'::public.value_token_type,
        p_gold_amount,
        'TEACHER_GRANT'::public.transaction_source_type,
        NULL,
        0,
        '[교사 BV+골드 동시 지급/GOLD] ' || v_reason
      );
    END IF;

    SELECT w.bv,w.gold INTO v_new_bv,v_new_gold
      FROM public.wallets AS w WHERE w.student_id=v_student_id;

    student_id := v_student_id;
    bv_transaction_id := v_bv_tx;
    gold_transaction_id := v_gold_tx;
    new_bv := v_new_bv;
    new_gold := v_new_gold;
    RETURN NEXT;
  END LOOP;
END;
$$;

COMMENT ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text)
IS '교사 전용 BV+GOLD 동시 지급. 두 자산 지급을 하나의 PostgreSQL 트랜잭션에서 원자적으로 처리한다.';
REVOKE ALL ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text) TO authenticated,service_role;

-- --------------------------------------------------------------------------
-- Realtime publication 보강
-- --------------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
 IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
  FOREACH t IN ARRAY ARRAY['mail_messages','global_alerts','global_alert_reads','emergencies','emergency_quests','emergency_quest_completions','emergency_quest_requests','assignments'] LOOP
   IF to_regclass(format('public.%I',t)) IS NOT NULL
      AND NOT EXISTS(
        SELECT 1 FROM pg_publication_tables
         WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t
      ) THEN
    EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
   END IF;
  END LOOP;
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- Feature 4.1.1 진단
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_feature4_1_1_health_check()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
DECLARE v_base jsonb;
BEGIN
  PERFORM public.ensure_teacher_role();
  v_base := public.teacher_feature4_1_health_check();
  RETURN v_base || jsonb_build_object('F4.1.1', jsonb_build_object(
    'quest_request_table', to_regclass('public.emergency_quest_requests') IS NOT NULL,
    'combined_asset_grant_rpc', to_regprocedure('public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text)') IS NOT NULL,
    'mail_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='mail_messages'),
    'alerts_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='global_alerts'),
    'emergency_quests_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergency_quests'),
    'quest_requests_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergency_quest_requests'),
    'auction_create_rpc', to_regprocedure('public.teacher_create_live_auction(integer,integer,integer,date,integer,integer)') IS NOT NULL,
    'auction_start_rpc', to_regprocedure('public.teacher_start_live_auction(integer)') IS NOT NULL
  ));
END $$;
REVOKE ALL ON FUNCTION public.teacher_feature4_1_1_health_check() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_feature4_1_1_health_check() TO authenticated,service_role;

-- PostgREST가 방금 생성/교체한 테이블·RPC를 즉시 인식하도록 요청.
NOTIFY pgrst, 'reload schema';

COMMIT;
