-- =====================================================================
-- B.R.A.N.D 2.0 — Dimensional Gate Wave 7
-- Liminel archivist + teacher operations
-- =====================================================================

begin;

create table if not exists public.dimensional_gate_teacher_audit_events (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete cascade,
  teacher_user_id uuid not null,
  student_id integer not null references public.students(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  action text not null check (action in ('SET_AFFINITY','UNLOCK','LOCK','CLEAR_WARNINGS','RESET_DAILY')),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists dimensional_gate_teacher_audit_events_classroom_idx
  on public.dimensional_gate_teacher_audit_events(classroom_id, created_at desc);
create index if not exists dimensional_gate_teacher_audit_events_student_idx
  on public.dimensional_gate_teacher_audit_events(student_id, character_id, created_at desc);

alter table public.dimensional_gate_teacher_audit_events enable row level security;
revoke all on table public.dimensional_gate_teacher_audit_events from public, anon, authenticated;

create policy dimensional_gate_teacher_audit_select
  on public.dimensional_gate_teacher_audit_events
  for select to authenticated
  using (public.is_teacher_or_admin() and classroom_id=public.current_classroom_id());

-- ---------------------------------------------------------------------
-- Student: Liminel record. No AI call and no client-side localStorage SSOT.
-- ---------------------------------------------------------------------
create or replace function public.student_get_dimensional_gate_liminel_record()
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_student_id integer:=public.current_student_id();
  v_classroom_id integer:=public.current_classroom_id();
  v_intro_seen_at timestamptz;
  v_relationship_count integer:=0;
  v_memory_count integer:=0;
  v_story_count integer:=0;
  v_gallery_count integer:=0;
  v_trust_count integer:=0;
  v_trust_records jsonb:='[]'::jsonb;
begin
  if v_student_id is null or v_classroom_id is null then
    raise exception 'Student context not found' using errcode='PDG20';
  end if;
  if not exists(
    select 1 from public.students s
    where s.id=v_student_id and s.classroom_id=v_classroom_id
      and s.role::text='STUDENT' and s.transferred_at is null
  ) then
    raise exception 'Active student required' using errcode='PDG61';
  end if;

  select sp.intro_seen_at into v_intro_seen_at
  from public.dimensional_gate_system_progress sp
  where sp.student_id=v_student_id;

  select count(*)::integer into v_relationship_count
  from public.dimensional_gate_relationships r
  where r.student_id=v_student_id;

  select count(*)::integer into v_memory_count
  from public.dimensional_gate_memory_unlocks u
  where u.student_id=v_student_id;

  select count(*)::integer into v_story_count
  from public.dimensional_gate_story_progress p
  join public.dimensional_gate_story_episodes e on e.id=p.episode_id
  where p.student_id=v_student_id and p.completed_at is not null and e.is_active=true;

  select count(*)::integer into v_gallery_count
  from public.dimensional_gate_gallery_unlocks u
  where u.student_id=v_student_id;

  select count(*)::integer into v_trust_count
  from public.dimensional_gate_memory_unlocks u
  where u.student_id=v_student_id and u.memory_no=3;

  select coalesce(jsonb_agg(item order by unlocked_at desc),'[]'::jsonb)
  into v_trust_records
  from (
    select
      u.unlocked_at,
      jsonb_build_object(
        'character_id',c.id,
        'character_uid',c.character_uid,
        'name',c.name,
        'epithet',c.epithet,
        'unlocked_at',u.unlocked_at
      ) item
    from public.dimensional_gate_memory_unlocks u
    join public.characters c on c.id=u.character_id
    where u.student_id=v_student_id and u.memory_no=3
    order by u.unlocked_at desc
    limit 20
  ) q;

  return jsonb_build_object(
    'intro_seen',v_intro_seen_at is not null,
    'intro_seen_at',v_intro_seen_at,
    'relationship_count',v_relationship_count,
    'memory_count',v_memory_count,
    'completed_story_count',v_story_count,
    'gallery_count',v_gallery_count,
    'trust_count',v_trust_count,
    'trust_records',v_trust_records
  );
end;
$function$;

revoke all on function public.student_get_dimensional_gate_liminel_record() from public, anon;
grant execute on function public.student_get_dimensional_gate_liminel_record() to authenticated, service_role;

create or replace function public.student_mark_dimensional_gate_intro_seen()
returns timestamptz
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_student_id integer:=public.current_student_id();
  v_seen timestamptz;
begin
  if v_student_id is null then raise exception 'Student context not found' using errcode='PDG20'; end if;
  insert into public.dimensional_gate_system_progress(student_id,intro_seen_at,last_liminel_view_at,created_at,updated_at)
  values(v_student_id,now(),now(),now(),now())
  on conflict (student_id) do update
    set intro_seen_at=coalesce(public.dimensional_gate_system_progress.intro_seen_at,excluded.intro_seen_at),
        last_liminel_view_at=now(),
        updated_at=now()
  returning intro_seen_at into v_seen;
  return v_seen;
end;
$function$;

revoke all on function public.student_mark_dimensional_gate_intro_seen() from public, anon;
grant execute on function public.student_mark_dimensional_gate_intro_seen() to authenticated, service_role;

-- ---------------------------------------------------------------------
-- Teacher board: owned + gate-enabled characters only.
-- ---------------------------------------------------------------------
create or replace function public.teacher_get_dimensional_gate_admin_board(p_classroom_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_students jsonb;
  v_rows jsonb;
  v_settings jsonb;
begin
  if not public.is_teacher_or_admin() then raise exception 'Teacher/admin only' using errcode='42501'; end if;
  if p_classroom_id is null or public.current_classroom_id() is null or p_classroom_id<>public.current_classroom_id() then
    raise exception 'Classroom scope mismatch' using errcode='42501';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'brand_name',s.brand_name) order by s.name),'[]'::jsonb)
    into v_students
  from public.students s
  where s.classroom_id=p_classroom_id and s.role::text='STUDENT' and s.transferred_at is null;

  select coalesce(to_jsonb(ds),'{}'::jsonb) into v_settings
  from public.dimensional_gate_settings ds
  where ds.classroom_id=p_classroom_id;
  v_settings:=coalesce(v_settings,jsonb_build_object(
    'classroom_id',p_classroom_id,'normal_gain',3,'mild_penalty',10,'severe_penalty',30,
    'lock_warning_count',3,'max_student_message_chars',600,'recent_history_limit',10,
    'activity_lookback_days',45,'activity_event_limit',5
  ));

  select coalesce(jsonb_agg(item order by student_name, character_name),'[]'::jsonb)
    into v_rows
  from (
    select
      s.name student_name,
      c.name character_name,
      jsonb_build_object(
        'student_id',s.id,
        'student_name',s.name,
        'brand_name',s.brand_name,
        'character_id',c.id,
        'character_uid',c.character_uid,
        'character_name',c.name,
        'affinity',coalesce(r.affinity,p.start_affinity),
        'relation_stage',public.dimensional_gate_relation_stage(coalesce(r.affinity,p.start_affinity)),
        'status',coalesce(r.status,'NORMAL'),
        'warning_count',coalesce(r.warning_count,0),
        'daily_chat_limit',p.daily_chat_limit,
        'chat_count',case when r.chat_date=current_date then coalesce(r.chat_count,0) else 0 end,
        'remaining_chat_count',greatest(p.daily_chat_limit-(case when r.chat_date=current_date then coalesce(r.chat_count,0) else 0 end),0),
        'last_interacted_at',r.last_interacted_at
      ) item
    from public.students s
    join public.student_characters sc on sc.student_id=s.id and sc.is_owned=true
    join public.characters c on c.id=sc.character_id and c.is_active=true
    join public.dimensional_gate_character_profiles p on p.character_id=c.id and p.is_active=true
    left join public.dimensional_gate_relationships r on r.student_id=s.id and r.character_id=c.id
    where s.classroom_id=p_classroom_id and s.role::text='STUDENT' and s.transferred_at is null
  ) q;

  return jsonb_build_object('settings',v_settings,'students',v_students,'relationships',v_rows);
end;
$function$;

revoke all on function public.teacher_get_dimensional_gate_admin_board(integer) from public, anon;
grant execute on function public.teacher_get_dimensional_gate_admin_board(integer) to authenticated, service_role;

create or replace function public.teacher_manage_dimensional_gate_relationship(
  p_student_id integer,
  p_character_id bigint,
  p_action text,
  p_value integer default null,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_action text:=upper(btrim(coalesce(p_action,'')));
  v_profile public.dimensional_gate_character_profiles%rowtype;
  v_rel public.dimensional_gate_relationships%rowtype;
  v_before jsonb;
  v_after jsonb;
begin
  if not public.is_teacher_or_admin() then raise exception 'Teacher/admin only' using errcode='42501'; end if;
  select s.classroom_id into v_classroom_id from public.students s
  where s.id=p_student_id and s.role::text='STUDENT' and s.transferred_at is null;
  if v_classroom_id is null or public.current_classroom_id() is null or v_classroom_id<>public.current_classroom_id() then
    raise exception 'Student classroom mismatch' using errcode='42501';
  end if;
  if v_action not in ('SET_AFFINITY','UNLOCK','LOCK','CLEAR_WARNINGS','RESET_DAILY') then
    raise exception 'Unsupported action' using errcode='PDG80';
  end if;

  select * into v_profile from public.dimensional_gate_character_profiles p
  where p.character_id=p_character_id and p.is_active=true;
  if not found then raise exception 'Dimensional Gate profile not found' using errcode='PDG21'; end if;
  if not exists(select 1 from public.student_characters sc where sc.student_id=p_student_id and sc.character_id=p_character_id and sc.is_owned=true) then
    raise exception 'Character not owned' using errcode='PDG22';
  end if;

  insert into public.dimensional_gate_relationships(
    classroom_id,student_id,character_id,affinity,warning_count,status,chat_count,created_at,updated_at
  ) values(v_classroom_id,p_student_id,p_character_id,v_profile.start_affinity,0,'NORMAL',0,now(),now())
  on conflict(student_id,character_id) do nothing;

  select * into v_rel from public.dimensional_gate_relationships r
  where r.student_id=p_student_id and r.character_id=p_character_id for update;
  v_before:=jsonb_build_object('affinity',v_rel.affinity,'status',v_rel.status,'warning_count',v_rel.warning_count,'chat_date',v_rel.chat_date,'chat_count',v_rel.chat_count);

  if v_action='SET_AFFINITY' then
    if p_value is null or p_value<0 or p_value>100 then raise exception 'Affinity must be 0..100' using errcode='PDG81'; end if;
    update public.dimensional_gate_relationships set affinity=p_value,updated_at=now() where id=v_rel.id;
    perform public.dimensional_gate_sync_milestone_unlocks(p_student_id,p_character_id,p_value);
  elsif v_action='UNLOCK' then
    update public.dimensional_gate_relationships set status='NORMAL',warning_count=0,updated_at=now() where id=v_rel.id;
  elsif v_action='LOCK' then
    update public.dimensional_gate_relationships set status='LOCKED',updated_at=now() where id=v_rel.id;
  elsif v_action='CLEAR_WARNINGS' then
    update public.dimensional_gate_relationships set warning_count=0,updated_at=now() where id=v_rel.id;
  elsif v_action='RESET_DAILY' then
    update public.dimensional_gate_relationships set chat_date=current_date,chat_count=0,updated_at=now() where id=v_rel.id;
  end if;

  select * into v_rel from public.dimensional_gate_relationships r where r.id=v_rel.id;
  v_after:=jsonb_build_object('affinity',v_rel.affinity,'status',v_rel.status,'warning_count',v_rel.warning_count,'chat_date',v_rel.chat_date,'chat_count',v_rel.chat_count);

  insert into public.dimensional_gate_teacher_audit_events(
    classroom_id,teacher_user_id,student_id,character_id,action,before_state,after_state,reason,created_at
  ) values(v_classroom_id,auth.uid(),p_student_id,p_character_id,v_action,v_before,v_after,nullif(btrim(p_reason),''),now());

  return jsonb_build_object(
    'student_id',p_student_id,'character_id',p_character_id,
    'affinity',v_rel.affinity,'relation_stage',public.dimensional_gate_relation_stage(v_rel.affinity),
    'status',v_rel.status,'warning_count',v_rel.warning_count,
    'chat_count',case when v_rel.chat_date=current_date then v_rel.chat_count else 0 end,
    'remaining_chat_count',greatest(v_profile.daily_chat_limit-(case when v_rel.chat_date=current_date then v_rel.chat_count else 0 end),0)
  );
end;
$function$;

revoke all on function public.teacher_manage_dimensional_gate_relationship(integer,bigint,text,integer,text) from public, anon;
grant execute on function public.teacher_manage_dimensional_gate_relationship(integer,bigint,text,integer,text) to authenticated, service_role;

commit;
