-- ============================================================================
-- B.R.A.N.D 2.0 — Records Room hidden seal / legacy successor registration V1
-- 2026-09-11
--
-- Student flow:
--   hidden wax seal discovery -> seal confirmation -> choose one preserved path
--   -> register one sentence -> 12 successors unseal the legacy.
--
-- Security:
--   no direct table access for authenticated users; SECURITY DEFINER RPC only.
--   all writes resolve student/classroom from auth context.
-- ============================================================================

create table if not exists public.records_legacy_events (
  id bigint generated by default as identity primary key,
  owner_teacher_user_id uuid not null,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  school_year integer not null check (school_year between 2000 and 2100),
  status text not null default 'OPEN'
    check (status in ('OPEN', 'UNSEALED', 'LOCKED', 'INHERITED')),
  minimum_successors integer not null default 12 check (minimum_successors between 1 and 100),
  unsealed_at timestamptz,
  locked_at timestamptz,
  locked_successor_count integer,
  inherited_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_legacy_event_one_per_teacher_year
    unique (owner_teacher_user_id, school_year)
);

create table if not exists public.records_legacy_successors (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.records_legacy_events(id) on delete cascade,
  owner_teacher_user_id uuid not null,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  school_year integer not null check (school_year between 2000 and 2100),
  student_id integer not null references public.students(id) on delete restrict,
  student_name_snapshot text not null,
  brand_name_snapshot text,
  seal_discovered_at timestamptz,
  seal_confirmed_at timestamptz,
  legacy_path_code text check (
    legacy_path_code is null or legacy_path_code in (
      'GRANDMASTER_LINEAGE',
      'FIRST_50000_GOLD',
      'HIGHEST_BV',
      'HIGHEST_ASSETS',
      'MOST_MVP_NOMINATIONS',
      'HIGHEST_MONTHLY_BV_GAIN'
    )
  ),
  legacy_statement text check (
    legacy_statement is null or char_length(legacy_statement) between 1 and 120
  ),
  registered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_legacy_successor_one_per_student_year
    unique (owner_teacher_user_id, school_year, student_id),
  constraint records_legacy_successor_registration_complete check (
    registered_at is null
    or (
      seal_discovered_at is not null
      and seal_confirmed_at is not null
      and legacy_path_code is not null
      and legacy_statement is not null
    )
  )
);

create index if not exists records_legacy_successors_event_registered_idx
  on public.records_legacy_successors (event_id, registered_at desc nulls last);

create index if not exists records_legacy_successors_owner_year_idx
  on public.records_legacy_successors (owner_teacher_user_id, school_year, registered_at desc nulls last);

alter table public.records_legacy_events enable row level security;
alter table public.records_legacy_successors enable row level security;

revoke all on table public.records_legacy_events from public, anon, authenticated;
revoke all on table public.records_legacy_successors from public, anon, authenticated;
revoke all on sequence public.records_legacy_events_id_seq from public, anon, authenticated;
revoke all on sequence public.records_legacy_successors_id_seq from public, anon, authenticated;

grant all on table public.records_legacy_events to service_role;
grant all on table public.records_legacy_successors to service_role;
grant all on sequence public.records_legacy_events_id_seq to service_role;
grant all on sequence public.records_legacy_successors_id_seq to service_role;

-- ----------------------------------------------------------------------------
-- Student: read current hidden-event state.
-- Does not create rows. Before first discovery the event is represented as OPEN/12.
-- ----------------------------------------------------------------------------
create or replace function public.student_get_records_legacy_successor_state()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_can_participate boolean := false;
  v_event public.records_legacy_events%rowtype;
  v_successor public.records_legacy_successors%rowtype;
  v_registered_count integer := 0;
begin
  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_LEGACY] authenticated classroom context is required.'
      using errcode = 'P0950';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null then
    raise exception '[RECORDS_LEGACY] classroom lineage could not be resolved.'
      using errcode = 'P0951';
  end if;

  v_can_participate := v_student_id is not null
    and public.is_official_participant(v_student_id);

  select e.* into v_event
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year
  limit 1;

  if v_student_id is not null then
    select s.* into v_successor
    from public.records_legacy_successors s
    where s.owner_teacher_user_id = v_owner_teacher_user_id
      and s.school_year = v_school_year
      and s.student_id = v_student_id
    limit 1;
  end if;

  select count(*)::integer into v_registered_count
  from public.records_legacy_successors s
  where s.owner_teacher_user_id = v_owner_teacher_user_id
    and s.school_year = v_school_year
    and s.registered_at is not null;

  return jsonb_build_object(
    'can_participate', v_can_participate,
    'event_status', coalesce(v_event.status, 'OPEN'),
    'minimum_successors', coalesce(v_event.minimum_successors, 12),
    'registered_count', v_registered_count,
    'seal_discovered_at', v_successor.seal_discovered_at,
    'seal_confirmed_at', v_successor.seal_confirmed_at,
    'legacy_path_code', v_successor.legacy_path_code,
    'legacy_statement', v_successor.legacy_statement,
    'registered_at', v_successor.registered_at,
    'unsealed_at', v_event.unsealed_at,
    'locked_at', v_event.locked_at,
    'inherited_at', v_event.inherited_at
  );
end;
$function$;

-- ----------------------------------------------------------------------------
-- Student: discover the wax seal. Creates the current-year event lazily.
-- ----------------------------------------------------------------------------
create or replace function public.student_discover_records_legacy_seal()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_student_name text;
  v_brand_name text;
  v_event_id bigint;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS_LEGACY] authenticated student context is required.'
      using errcode = 'P0952';
  end if;

  if not public.is_official_participant(v_student_id) then
    raise exception '[RECORDS_LEGACY] only official participants may discover the seal.'
      using errcode = 'P0953';
  end if;

  select c.teacher_user_id, c.school_year, s.name, s.brand_name
    into v_owner_teacher_user_id, v_school_year, v_student_name, v_brand_name
  from public.classrooms c
  join public.students s
    on s.id = v_student_id
   and s.classroom_id = c.id
   and s.transferred_at is null
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null or v_student_name is null then
    raise exception '[RECORDS_LEGACY] student lineage could not be resolved.'
      using errcode = 'P0954';
  end if;

  insert into public.records_legacy_events (
    owner_teacher_user_id, classroom_id, school_year
  ) values (
    v_owner_teacher_user_id, v_classroom_id, v_school_year
  )
  on conflict (owner_teacher_user_id, school_year)
  do update set classroom_id = excluded.classroom_id, updated_at = now()
  returning id into v_event_id;

  insert into public.records_legacy_successors (
    event_id,
    owner_teacher_user_id,
    classroom_id,
    school_year,
    student_id,
    student_name_snapshot,
    brand_name_snapshot,
    seal_discovered_at
  ) values (
    v_event_id,
    v_owner_teacher_user_id,
    v_classroom_id,
    v_school_year,
    v_student_id,
    v_student_name,
    v_brand_name,
    now()
  )
  on conflict (owner_teacher_user_id, school_year, student_id)
  do update set
    event_id = excluded.event_id,
    classroom_id = excluded.classroom_id,
    student_name_snapshot = excluded.student_name_snapshot,
    brand_name_snapshot = excluded.brand_name_snapshot,
    seal_discovered_at = coalesce(public.records_legacy_successors.seal_discovered_at, excluded.seal_discovered_at),
    updated_at = now();

  return public.student_get_records_legacy_successor_state();
end;
$function$;

-- ----------------------------------------------------------------------------
-- Student: confirm the discovered seal, unlocking the quest UI for this student.
-- ----------------------------------------------------------------------------
create or replace function public.student_confirm_records_legacy_seal()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_updated bigint;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS_LEGACY] authenticated student context is required.'
      using errcode = 'P0955';
  end if;

  if not public.is_official_participant(v_student_id) then
    raise exception '[RECORDS_LEGACY] only official participants may confirm the seal.'
      using errcode = 'P0956';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  update public.records_legacy_successors s
  set seal_confirmed_at = coalesce(s.seal_confirmed_at, now()),
      updated_at = now()
  where s.owner_teacher_user_id = v_owner_teacher_user_id
    and s.school_year = v_school_year
    and s.student_id = v_student_id
    and s.seal_discovered_at is not null
  returning s.id into v_updated;

  if v_updated is null then
    raise exception '[RECORDS_LEGACY] discover the seal before confirming it.'
      using errcode = 'P0957';
  end if;

  return public.student_get_records_legacy_successor_state();
end;
$function$;

-- ----------------------------------------------------------------------------
-- Student: register one preserved record path and one sentence.
-- The event row is FOR UPDATE locked so 11 -> 12 can unseal exactly once.
-- ----------------------------------------------------------------------------
create or replace function public.student_register_records_legacy_successor(
  p_path_code text,
  p_statement text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_student_name text;
  v_brand_name text;
  v_event public.records_legacy_events%rowtype;
  v_successor public.records_legacy_successors%rowtype;
  v_statement text;
  v_registered_count integer := 0;
  v_just_unsealed boolean := false;
  v_result jsonb;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS_LEGACY] authenticated student context is required.'
      using errcode = 'P0958';
  end if;

  if not public.is_official_participant(v_student_id) then
    raise exception '[RECORDS_LEGACY] only official participants may register as successors.'
      using errcode = 'P0959';
  end if;

  if p_path_code is null or p_path_code not in (
    'GRANDMASTER_LINEAGE',
    'FIRST_50000_GOLD',
    'HIGHEST_BV',
    'HIGHEST_ASSETS',
    'MOST_MVP_NOMINATIONS',
    'HIGHEST_MONTHLY_BV_GAIN'
  ) then
    raise exception '[RECORDS_LEGACY] invalid legacy path.'
      using errcode = 'P0960';
  end if;

  v_statement := regexp_replace(btrim(coalesce(p_statement, '')), '[[:space:]]+', ' ', 'g');
  if char_length(v_statement) < 1 or char_length(v_statement) > 120 then
    raise exception '[RECORDS_LEGACY] statement must be between 1 and 120 characters.'
      using errcode = 'P0961';
  end if;

  select c.teacher_user_id, c.school_year, s.name, s.brand_name
    into v_owner_teacher_user_id, v_school_year, v_student_name, v_brand_name
  from public.classrooms c
  join public.students s
    on s.id = v_student_id
   and s.classroom_id = c.id
   and s.transferred_at is null
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null or v_student_name is null then
    raise exception '[RECORDS_LEGACY] student lineage could not be resolved.'
      using errcode = 'P0962';
  end if;

  insert into public.records_legacy_events (
    owner_teacher_user_id, classroom_id, school_year
  ) values (
    v_owner_teacher_user_id, v_classroom_id, v_school_year
  )
  on conflict (owner_teacher_user_id, school_year)
  do update set classroom_id = excluded.classroom_id, updated_at = now();

  select e.* into v_event
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year
  for update;

  if v_event.status in ('LOCKED', 'INHERITED') then
    raise exception '[RECORDS_LEGACY] successor registration is closed.'
      using errcode = 'P0963';
  end if;

  select s.* into v_successor
  from public.records_legacy_successors s
  where s.owner_teacher_user_id = v_owner_teacher_user_id
    and s.school_year = v_school_year
    and s.student_id = v_student_id
  for update;

  if v_successor.id is null or v_successor.seal_discovered_at is null or v_successor.seal_confirmed_at is null then
    raise exception '[RECORDS_LEGACY] confirm the hidden seal before registering.'
      using errcode = 'P0964';
  end if;

  if v_successor.registered_at is not null then
    raise exception '[RECORDS_LEGACY] successor path has already been registered.'
      using errcode = 'P0965';
  end if;

  update public.records_legacy_successors s
  set legacy_path_code = p_path_code,
      legacy_statement = v_statement,
      student_name_snapshot = v_student_name,
      brand_name_snapshot = v_brand_name,
      registered_at = now(),
      updated_at = now()
  where s.id = v_successor.id;

  select count(*)::integer into v_registered_count
  from public.records_legacy_successors s
  where s.event_id = v_event.id
    and s.registered_at is not null;

  if v_event.status = 'OPEN'
     and v_event.unsealed_at is null
     and v_registered_count >= v_event.minimum_successors then
    update public.records_legacy_events e
    set status = 'UNSEALED',
        unsealed_at = now(),
        updated_at = now()
    where e.id = v_event.id;
    v_just_unsealed := true;
  end if;

  v_result := public.student_get_records_legacy_successor_state();
  return v_result || jsonb_build_object('just_unsealed', v_just_unsealed);
end;
$function$;

-- ----------------------------------------------------------------------------
-- Teacher board. Creates the current-year event lazily so the admin panel has a
-- stable row even before a student discovers the seal.
-- ----------------------------------------------------------------------------
create or replace function public.teacher_get_records_legacy_successors()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_event public.records_legacy_events%rowtype;
  v_discovered_count integer := 0;
  v_confirmed_count integer := 0;
  v_registered_count integer := 0;
  v_rows jsonb := '[]'::jsonb;
  v_path_counts jsonb := '{}'::jsonb;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_LEGACY] authenticated teacher context is required.'
      using errcode = 'P0966';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null then
    raise exception '[RECORDS_LEGACY] teacher lineage could not be resolved.'
      using errcode = 'P0967';
  end if;

  insert into public.records_legacy_events (
    owner_teacher_user_id, classroom_id, school_year
  ) values (
    v_owner_teacher_user_id, v_classroom_id, v_school_year
  )
  on conflict (owner_teacher_user_id, school_year)
  do update set classroom_id = excluded.classroom_id, updated_at = now();

  select e.* into v_event
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year;

  select
    count(*) filter (where s.seal_discovered_at is not null)::integer,
    count(*) filter (where s.seal_confirmed_at is not null)::integer,
    count(*) filter (where s.registered_at is not null)::integer
  into v_discovered_count, v_confirmed_count, v_registered_count
  from public.records_legacy_successors s
  where s.event_id = v_event.id;

  select coalesce(
    jsonb_object_agg(x.legacy_path_code, x.cnt),
    '{}'::jsonb
  ) into v_path_counts
  from (
    select s.legacy_path_code, count(*)::integer as cnt
    from public.records_legacy_successors s
    where s.event_id = v_event.id
      and s.registered_at is not null
      and s.legacy_path_code is not null
    group by s.legacy_path_code
  ) x;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'student_id', x.student_id,
        'student_name', x.student_name_snapshot,
        'brand_name', x.brand_name_snapshot,
        'seal_discovered_at', x.seal_discovered_at,
        'seal_confirmed_at', x.seal_confirmed_at,
        'legacy_path_code', x.legacy_path_code,
        'legacy_statement', x.legacy_statement,
        'registered_at', x.registered_at
      )
      order by x.registered_at desc nulls last, x.seal_discovered_at desc, x.student_name_snapshot asc
    ),
    '[]'::jsonb
  ) into v_rows
  from public.records_legacy_successors x
  where x.event_id = v_event.id;

  return jsonb_build_object(
    'event_status', v_event.status,
    'minimum_successors', v_event.minimum_successors,
    'discovered_count', v_discovered_count,
    'confirmed_count', v_confirmed_count,
    'registered_count', v_registered_count,
    'unsealed_at', v_event.unsealed_at,
    'locked_at', v_event.locked_at,
    'locked_successor_count', v_event.locked_successor_count,
    'inherited_at', v_event.inherited_at,
    'path_counts', v_path_counts,
    'rows', v_rows
  );
end;
$function$;

-- ----------------------------------------------------------------------------
-- Teacher: reset one student's formal registration while preserving discovery /
-- confirmation. If the event was already unsealed, it never reseals.
-- ----------------------------------------------------------------------------
create or replace function public.teacher_reset_records_legacy_successor(
  p_student_id integer
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_event_status text;
  v_updated bigint;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_LEGACY] authenticated teacher context is required.'
      using errcode = 'P0974';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  select e.status into v_event_status
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year;

  if v_event_status in ('LOCKED', 'INHERITED') then
    raise exception '[RECORDS_LEGACY] unlock the final roster before resetting a registration.'
      using errcode = 'P0968';
  end if;

  update public.records_legacy_successors s
  set legacy_path_code = null,
      legacy_statement = null,
      registered_at = null,
      updated_at = now()
  where s.owner_teacher_user_id = v_owner_teacher_user_id
    and s.school_year = v_school_year
    and s.student_id = p_student_id
    and s.registered_at is not null
  returning s.id into v_updated;

  if v_updated is null then
    raise exception '[RECORDS_LEGACY] registered successor not found.'
      using errcode = 'P0969';
  end if;

  return public.teacher_get_records_legacy_successors();
end;
$function$;

-- ----------------------------------------------------------------------------
-- Teacher: lock the final successor roster for the inheritance ceremony.
-- ----------------------------------------------------------------------------
create or replace function public.teacher_lock_records_legacy_successors()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_event public.records_legacy_events%rowtype;
  v_count integer := 0;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_LEGACY] authenticated teacher context is required.'
      using errcode = 'P0975';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  select e.* into v_event
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year
  for update;

  if v_event.id is null then
    raise exception '[RECORDS_LEGACY] event has not started.' using errcode = 'P0970';
  end if;

  if v_event.status not in ('OPEN', 'UNSEALED') then
    raise exception '[RECORDS_LEGACY] only an open successor roster can be locked.' using errcode = 'P0971';
  end if;

  select count(*)::integer into v_count
  from public.records_legacy_successors s
  where s.event_id = v_event.id and s.registered_at is not null;

  if v_count < v_event.minimum_successors then
    raise exception '[RECORDS_LEGACY] minimum successor count has not been reached.' using errcode = 'P0972';
  end if;

  update public.records_legacy_events e
  set status = 'LOCKED',
      locked_at = now(),
      locked_successor_count = v_count,
      updated_at = now()
  where e.id = v_event.id;

  return public.teacher_get_records_legacy_successors();
end;
$function$;

-- ----------------------------------------------------------------------------
-- Teacher: unlock a roster that was locked by mistake. The event stays
-- UNSEALED once it has ever reached 12.
-- ----------------------------------------------------------------------------
create or replace function public.teacher_unlock_records_legacy_successors()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_event public.records_legacy_events%rowtype;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_LEGACY] authenticated teacher context is required.'
      using errcode = 'P0976';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  select e.* into v_event
  from public.records_legacy_events e
  where e.owner_teacher_user_id = v_owner_teacher_user_id
    and e.school_year = v_school_year
  for update;

  if v_event.id is null or v_event.status <> 'LOCKED' then
    raise exception '[RECORDS_LEGACY] only a locked event can be unlocked.' using errcode = 'P0973';
  end if;

  update public.records_legacy_events e
  set status = case when e.unsealed_at is not null then 'UNSEALED' else 'OPEN' end,
      locked_at = null,
      locked_successor_count = null,
      updated_at = now()
  where e.id = v_event.id;

  return public.teacher_get_records_legacy_successors();
end;
$function$;

revoke all on function public.student_get_records_legacy_successor_state() from public, anon;
revoke all on function public.student_discover_records_legacy_seal() from public, anon;
revoke all on function public.student_confirm_records_legacy_seal() from public, anon;
revoke all on function public.student_register_records_legacy_successor(text, text) from public, anon;
revoke all on function public.teacher_get_records_legacy_successors() from public, anon;
revoke all on function public.teacher_reset_records_legacy_successor(integer) from public, anon;
revoke all on function public.teacher_lock_records_legacy_successors() from public, anon;
revoke all on function public.teacher_unlock_records_legacy_successors() from public, anon;

grant execute on function public.student_get_records_legacy_successor_state() to authenticated;
grant execute on function public.student_discover_records_legacy_seal() to authenticated;
grant execute on function public.student_confirm_records_legacy_seal() to authenticated;
grant execute on function public.student_register_records_legacy_successor(text, text) to authenticated;
grant execute on function public.teacher_get_records_legacy_successors() to authenticated;
grant execute on function public.teacher_reset_records_legacy_successor(integer) to authenticated;
grant execute on function public.teacher_lock_records_legacy_successors() to authenticated;
grant execute on function public.teacher_unlock_records_legacy_successors() to authenticated;

comment on table public.records_legacy_events is
  'Hidden Hall-of-Glory legacy inheritance event state, scoped by teacher lineage and school year.';
comment on table public.records_legacy_successors is
  'Student discovery/confirmation/registration state for the Hall-of-Glory hidden legacy successor quest.';
