import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader, EmptyState, LoadingSpinner, useRpcCall } from '@/components/shared/components';
import { supabase } from '@/lib/supabase/client';
import { useClassroomId, useStudentId } from '@/stores/auth_store';
import { feature4Rpc } from '@/lib/rpc/feature4_rpc';
import { formatRelativeTime } from '@/lib/utils/format';
import { feature4QueryError } from '@/lib/feature4_debug';
import { Feature4ErrorPanel } from '@/features/feature4/Feature4ErrorPanel';

export default function AssignmentsPage(){
 const classroomId=useClassroomId(),studentId=useStudentId(),qc=useQueryClient(),{call,isLoading}=useRpcCall(); const [text,setText]=useState<Record<number,string>>({}); const [links,setLinks]=useState<Record<number,string>>({});
 const q=useQuery({queryKey:['f4c-student-assignments',classroomId,studentId],enabled:!!classroomId&&!!studentId,queryFn:async()=>{
  const [{data:a,error:e1},{data:s,error:e2}]=await Promise.all([
   supabase.from('assignments').select('id,title,description,subject,due_at,max_score,base_reward_gold,full_score_reward_bv,status').eq('classroom_id',classroomId!).in('status',['PUBLISHED','CLOSED']).order('due_at',{ascending:true}),
   supabase.from('assignment_submissions').select('id,assignment_id,status,is_late,submitted_at,grading:assignment_gradings(score,feedback,is_revoked)').eq('student_id',studentId!).order('submitted_at',{ascending:true})
  ]);if(e1)throw feature4QueryError('F4C','student-assignment-list',e1);if(e2)throw feature4QueryError('F4C','student-submission-list',e2);const sm=new Map((s??[]).map((x:any)=>[x.assignment_id,x]));return (a??[]).map((x:any)=>({...x,submission:sm.get(x.id)}));
 }});
 return <><PageHeader title="과제" emoji="📝"/><div className="px-4 pt-4 pb-28 max-w-3xl mx-auto">{q.isLoading?<div className="py-10 flex justify-center"><LoadingSpinner size="lg"/></div>:q.isError?<Feature4ErrorPanel domain="F4C" error={q.error} onRetry={()=>void q.refetch()}/>:!q.data?.length?<EmptyState emoji="📚" title="현재 공개된 과제가 없어요"/>:<div className="space-y-3">{q.data.map((a:any)=>{const submitted=!!a.submission&&a.submission.status!=='RETURNED';const expired=new Date(a.due_at).getTime()<Date.now();return <div key={a.id} className="glass-card p-4"><div className="flex justify-between gap-2"><div><div className="text-2xs text-gold font-black">{a.subject||'학급 과제'} · 마감 {formatRelativeTime(a.due_at)}</div><h2 className="font-display text-lg mt-1">{a.title}</h2></div><span className="text-xs font-bold text-text-secondary">{submitted?'✅ 제출됨':a.submission?.status==='RETURNED'?'↩️ 재제출 필요':a.status==='CLOSED'?'🔒 종료':expired?'⏰ 지각 제출 가능':'진행 중'}</span></div>{a.description&&<p className="text-sm text-text-secondary mt-2 whitespace-pre-wrap">{a.description}</p>}<div className="text-2xs text-text-muted mt-2">제출 보상 {a.base_reward_gold} GOLD · 만점 보상 {a.full_score_reward_bv} BV · {a.max_score}점</div>{!submitted&&a.status==='PUBLISHED'&&<div className="mt-3"><textarea value={text[a.id]||''} onChange={e=>setText(v=>({...v,[a.id]:e.target.value}))} placeholder="제출 내용을 입력하세요" className="w-full min-h-24 bg-bg-deep border border-line rounded-card-md p-3 text-sm"/><textarea value={links[a.id]||''} onChange={e=>setLinks(v=>({...v,[a.id]:e.target.value}))} placeholder="첨부 링크 (선택, 한 줄에 하나 · 최대 5개)" className="w-full min-h-16 bg-bg-deep border border-line rounded-card-md p-3 text-xs mt-2"/><button disabled={isLoading} onClick={()=>call(()=>feature4Rpc.submitAssignment(supabase,{p_student_id:studentId!,p_assignment_id:a.id,p_content_text:text[a.id]||undefined,p_attachment_urls:(links[a.id]||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,5)}),{successTitle:'과제를 제출했어요',onSuccess:()=>{setText(v=>({...v,[a.id]:''}));setLinks(v=>({...v,[a.id]:''}));qc.invalidateQueries({queryKey:['f4c-student-assignments']});}})} className="btn-primary w-full mt-2">제출하기</button></div>}{a.submission&&<div className="mt-3 text-xs bg-bg-deep rounded-card-md p-3"><div>상태: {a.submission.status}{a.submission.is_late?' · 지각 제출':''} · {formatRelativeTime(a.submission.submitted_at)}</div>{a.submission.grading?.find((g:any)=>!g.is_revoked)&&(()=>{const g=a.submission.grading.find((x:any)=>!x.is_revoked);return <div className="mt-2 pt-2 border-t border-line"><div className="font-black text-success">채점: {g.score} / {a.max_score}</div>{g.feedback&&<div className="text-text-secondary mt-1 whitespace-pre-wrap">피드백: {g.feedback}</div>}</div>})()}</div>}</div>})}</div>}</div></>;
}
