import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader, LoadingPage, EmptyState, Modal } from '@/components/shared/components';
import { supabase } from '@/lib/supabase/client';
import { guild3StudentRpc, guild3RpcError, type Guild3StudentBoardItem } from '@/lib/rpc/guild3_rpc';
import { useToastStore } from '@/stores/ui_store';

const fmt=(value?:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'-';
const statusLabel:Record<string,string>={DRAFT:'예고',ACTIVE:'진행 중',CLOSED:'채점 중',FINALIZED:'확정',CANCELLED:'취소',VOIDED:'무효'};

export default function GuildMissionsPage(){
  const qc=useQueryClient(); const show=useToastStore(s=>s.show); const [missionListOpen,setMissionListOpen]=useState(false);
  const boardQ=useQuery({queryKey:['guild3-student-board'],queryFn:async()=>{const r=await guild3StudentRpc.board(supabase); if(!r.success) throw new Error(guild3RpcError(r)); return r.data;}});
  const scoreQ=useQuery({queryKey:['guild3-student-score-summary'],queryFn:async()=>{const r=await guild3StudentRpc.scoreSummary(supabase); if(!r.success) throw new Error(guild3RpcError(r)); return r.data;}});
  const submitM=useMutation({mutationFn:async(input:{p_mission_id:number;p_content:string;p_reference_url?:string|null})=>{const r=await guild3StudentRpc.submit(supabase,input);if(!r.success)throw new Error(guild3RpcError(r));return r.data;},onSuccess:()=>{show({title:'미션 제출 완료',variant:'success'});void qc.invalidateQueries({queryKey:['guild3-student-board']});},onError:e=>show({title:'제출 실패',description:String((e as Error).message),variant:'error'})});
  const activityM=useMutation({mutationFn:async(input:{p_mission_id:number;p_content:string})=>{const r=await guild3StudentRpc.activity(supabase,input);if(!r.success)throw new Error(guild3RpcError(r));return r.data;},onSuccess:()=>{show({title:'활동 기록 저장 완료',variant:'success'});void qc.invalidateQueries({queryKey:['guild3-student-board']});},onError:e=>show({title:'저장 실패',description:String((e as Error).message),variant:'error'})});
  const scores=scoreQ.data??[];
  const missions=boardQ.data??[];
  const missionIndex=useMemo(()=>missions,[missions]);
  const jumpToMission=(missionId:number)=>{setMissionListOpen(false);window.setTimeout(()=>document.getElementById(`mission-${missionId}`)?.scrollIntoView({behavior:'smooth',block:'start'}),80);};
  if(boardQ.isLoading)return <><PageHeader title="길드 미션" emoji="🗺️"/><LoadingPage/></>;
  return <div className="pb-24"><PageHeader title="길드 미션" emoji="🗺️"/><div className="p-4 space-y-4 max-w-3xl mx-auto">
    <section className="glass-card p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-text-muted">개인 기여도 · Mission</p><h2 className="font-display text-lg text-brand-gradient mt-1">월간 미션 점수</h2></div><span className="text-2xl">🎯</span></div>
      {scores.length===0?<p className="text-sm text-text-secondary mt-3">아직 집계할 공식 미션이 없습니다.</p>:<div className="mt-3 grid gap-2">{scores.map(s=><div key={s.year_month} className="flex items-center justify-between rounded-card-md border border-line bg-bg-deep p-3"><span className="font-bold text-sm">{s.year_month}</span><span className={s.status==='READY'?'text-bv font-black':'text-warning font-black'}>{s.status==='READY'?`${Number(s.points).toFixed(1)} / ${s.max_points}`:'집계 중'}</span></div>)}</div>}
    </section>
    {missions.length>0&&<div className="flex justify-end"><button type="button" className="btn-secondary" onClick={()=>setMissionListOpen(true)}>☰ 미션 목록</button></div>}
    {missions.length===0?<EmptyState emoji="🗺️" title="표시할 미션이 없어요" description="새 미션이 공개되면 여기에 나타납니다."/>:missions.map(m=><StudentMissionCard key={m.mission_id} mission={m} submitting={submitM.isPending} recording={activityM.isPending} onSubmit={(content,url)=>submitM.mutate({p_mission_id:m.mission_id,p_content:content,p_reference_url:url||null})} onActivity={content=>activityM.mutate({p_mission_id:m.mission_id,p_content:content})}/>) }
    {missionListOpen&&<Modal isOpen onClose={()=>setMissionListOpen(false)} title="미션 목록" emoji="🗺️" size="lg"><div className="space-y-2 max-h-[65vh] overflow-y-auto">{missionIndex.map(m=><button key={m.mission_id} type="button" onClick={()=>jumpToMission(m.mission_id)} className="w-full rounded-card-md border border-line bg-bg-deep p-3 text-left hover:border-bv/50 transition"><div className="flex items-center justify-between gap-3"><span className="font-black text-sm truncate">{m.title}</span><span className="text-2xs font-black text-text-muted shrink-0">{statusLabel[m.lifecycle_state]??m.lifecycle_state}</span></div><div className="text-2xs text-text-muted mt-1">미션 #{m.mission_id}{m.due_at?` · ${fmt(m.due_at)}`:''}</div></button>)}</div></Modal>}
  </div></div>;
}

function StudentMissionCard({mission,submitting,recording,onSubmit,onActivity}:{mission:Guild3StudentBoardItem;submitting:boolean;recording:boolean;onSubmit:(content:string,url:string)=>void;onActivity:(content:string)=>void}){
  const [content,setContent]=useState(mission.current_submission??''); const [url,setUrl]=useState(''); const [activity,setActivity]=useState(mission.my_activity_record??'');
  const now=Date.now(); const canSubmit=mission.lifecycle_state==='ACTIVE' && (!mission.due_at||now<new Date(mission.due_at).getTime()) && mission.submission_scope!=='NONE';
  const canActivity=['ACTIVE','CLOSED'].includes(mission.lifecycle_state)&&(!mission.activity_record_due_at||now<new Date(mission.activity_record_due_at).getTime());
  const requirement=mission.submission_requirement==='REQUIRED'?'필수':mission.submission_requirement==='OPTIONAL'?'선택':'제출 없음';
  const scope=mission.submission_scope==='GUILD'?'길드 공동':mission.submission_scope==='INDIVIDUAL'?'개인':'없음';
  if(mission.lifecycle_state==='CANCELLED')return <section id={`mission-${mission.mission_id}`} className="glass-card relative overflow-hidden px-4 py-5 border-warning/30 scroll-mt-4"><div className="opacity-50"><span className="text-2xs px-2 py-1 rounded-full bg-warning/10 text-warning font-black">취소</span><h3 className="font-display text-lg mt-2">{mission.title}</h3></div><MissionStatusOverlay label="취소"/></section>;
  if(mission.teaser_only)return <section id={`mission-${mission.mission_id}`} className="glass-card p-4 border-warning/30"><div className="flex justify-between gap-3"><div><span className="text-2xs px-2 py-1 rounded-full bg-warning/10 text-warning font-black">미션 예고</span><h3 className="font-display text-lg mt-2">{mission.title}</h3></div><span className="text-3xl opacity-70">🔭</span></div><p className="text-sm text-text-secondary mt-3">아직 상세 내용은 공개되지 않았습니다.</p></section>;
  const terminalOverlay=mission.lifecycle_state==='FINALIZED'?'종료':mission.lifecycle_state==='VOIDED'?'무효':null;
  return <section id={`mission-${mission.mission_id}`} className="glass-card relative overflow-hidden p-4 space-y-4 scroll-mt-4"><div className="flex items-start justify-between gap-3"><div><span className="text-2xs px-2 py-1 rounded-full bg-bv/10 text-bv font-black">{statusLabel[mission.lifecycle_state]??mission.lifecycle_state}</span><h3 className="font-display text-xl text-text-primary mt-2">{mission.title}</h3></div><span className="text-3xl">⚔️</span></div>
    {mission.description&&<p className="text-sm text-text-secondary whitespace-pre-wrap">{mission.description}</p>}
    {mission.student_success_criteria&&<div className="rounded-card-md bg-bg-deep border border-line p-3"><p className="text-xs font-black text-gold">성공 조건</p><p className="text-sm mt-1 whitespace-pre-wrap">{mission.student_success_criteria}</p></div>}
    <div className="grid grid-cols-2 gap-2 text-xs"><Info label="미션 마감" value={fmt(mission.due_at)}/><Info label="활동기록 마감" value={fmt(mission.activity_record_due_at)}/><Info label="제출 방식" value={`${scope} · ${requirement}`}/><Info label="현재 제출" value={mission.current_submission_revision?`${mission.current_submission_revision}차 제출`:'없음'}/></div>
    {mission.special_rule_note&&<div className="rounded-card-md border border-warning/30 bg-warning/10 p-3"><p className="text-xs font-black text-warning">우리 길드 특별 안내</p><p className="text-sm mt-1 whitespace-pre-wrap">{mission.special_rule_note}</p></div>}
    {(mission.guild_result||mission.my_grade)&&<div className="grid grid-cols-2 gap-2"><Info label="공식 길드 결과" value={mission.guild_result==='CLEARED'?'CLEARED ✅':mission.guild_result==='FAILED'?'FAILED':'-'}/><Info label="내 활동 등급" value={mission.my_grade??'-'}/></div>}
    {mission.submission_scope!=='NONE'&&<div className="border-t border-line pt-4"><h4 className="font-black text-sm">{scope} 결과 제출</h4>{mission.current_submission&&<div className="mt-2 rounded-card-md bg-bg-deep p-3 text-sm whitespace-pre-wrap"><span className="text-2xs text-text-muted block mb-1">현재 저장본</span>{mission.current_submission}</div>}<textarea className="input-field w-full min-h-28 mt-2" value={content} onChange={e=>setContent(e.target.value)} disabled={!canSubmit} placeholder={canSubmit?'결과물 또는 설명을 입력하세요.':'현재는 제출할 수 없습니다.'}/><input className="input-field w-full mt-2" value={url} onChange={e=>setUrl(e.target.value)} disabled={!canSubmit} placeholder="참고 링크 (선택)"/><button className="btn-primary w-full mt-2" disabled={!canSubmit||!content.trim()||submitting} onClick={()=>onSubmit(content,url)}>{submitting?'제출 중...':mission.current_submission_revision?'수정 제출':'제출'}</button></div>}
    <div className="border-t border-line pt-4"><h4 className="font-black text-sm">내 활동 기록</h4><p className="text-sm mt-2"><b>이번 미션에서 내가 실제로 한 일을 구체적으로 적어주세요.</b><br/><span className="text-xs text-text-secondary">(길드 개인 기여도 점수에 일부 반영됩니다.)</span></p><p className="text-xs text-text-muted mt-1">예: 태풍 피해 사례 4개를 조사하고, 그중 3개를 발표자료 2~3쪽에 정리했다.</p><textarea className="input-field w-full min-h-28 mt-2" value={activity} onChange={e=>setActivity(e.target.value)} disabled={!canActivity} maxLength={500}/><div className="flex justify-between text-2xs text-text-muted mt-1"><span>{mission.my_activity_record_revision?`${mission.my_activity_record_revision}차 기록 저장됨`:canActivity?'20~500자':'기록 마감'}</span><span>{activity.length}/500</span></div><button className="btn-secondary w-full mt-2" disabled={!canActivity||activity.trim().length<20||recording} onClick={()=>onActivity(activity)}>{recording?'저장 중...':mission.my_activity_record_revision?'활동 기록 수정':'활동 기록 저장'}</button></div>
    {terminalOverlay&&<MissionStatusOverlay label={terminalOverlay}/>}
  </section>;
}
function MissionStatusOverlay({label}:{label:string}){return <div className="pointer-events-none absolute inset-0 z-20 flex items-center justify-center bg-warning/50"><span className="rounded-card-md border border-warning/70 bg-bg-deep/85 px-7 py-3 font-display text-3xl font-black text-warning shadow-lg">{label}</span></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-card-md border border-line bg-bg-deep p-3"><div className="text-2xs font-black text-text-muted">{label}</div><div className="text-sm font-bold mt-1 break-keep">{value}</div></div>}
