#!/usr/bin/env python3
"""B.R.A.N.D 2.0 webfont builder.

Input: the user's original TTF/OTF directory or ZIP.
Output per logical font family:
  <slug>/<weight>.woff2     - full runtime WOFF2 (no glyph subsetting)
  <slug>/preview.woff2      - small market-preview subset
  <slug>/font.css           - @font-face declarations for runtime faces
  build_manifest.json       - validation and size summary

Safety/stability choices:
- Exact SHA-256 match is preferred, PostScript name is fallback only.
- The build fails on missing/duplicate configured faces.
- Restricted/no-subsetting OpenType embedding flags block unsafe operations.
- Runtime fonts are full-glyph WOFF2 to avoid student-name/free-text subset misses.
- Only the market preview font is subsetted.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    from fontTools.ttLib import TTFont
    import fontTools.ttLib.woff2 as woff2_module
    from fontTools import subset
except Exception as exc:  # pragma: no cover
    raise SystemExit("fonttools가 필요합니다: py -m pip install fonttools brotli") from exc

HERE = Path(__file__).resolve().parent
CONFIG_PATH = HERE / "font_sources.json"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def postscript_name(path: Path) -> str:
    font = TTFont(str(path), lazy=True)
    try:
        if "name" not in font:
            return ""
        for record in font["name"].names:
            if record.nameID == 6:
                try:
                    value = record.toUnicode().strip()
                except Exception:
                    continue
                if value:
                    return value
        return ""
    finally:
        font.close()


def fs_type(path: Path) -> int:
    font = TTFont(str(path), lazy=True)
    try:
        return int(getattr(font["OS/2"], "fsType", 0)) if "OS/2" in font else 0
    finally:
        font.close()


def validate_embedding_flags(path: Path, *, for_subset: bool) -> None:
    value = fs_type(path)
    if value & 0x0002:
        raise RuntimeError(f"Restricted License Embedding(fsType bit 1): {path.name}")
    if value & 0x0200:
        raise RuntimeError(f"Bitmap-only embedding flag: {path.name}")
    if for_subset and (value & 0x0100):
        raise RuntimeError(f"No-subsetting flag: {path.name}")


def write_full_woff2(source: Path, target: Path) -> None:
    validate_embedding_flags(source, for_subset=False)
    target.parent.mkdir(parents=True, exist_ok=True)
    font = TTFont(str(source))
    try:
        font.flavor = "woff2"
        font.save(str(target))
    finally:
        font.close()


def write_preview_woff2(source: Path, target: Path, text: str) -> None:
    validate_embedding_flags(source, for_subset=True)
    target.parent.mkdir(parents=True, exist_ok=True)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 4, 5, 6]
    options.name_legacy = True
    options.name_languages = ["*"]
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recalc_bounds = True
    options.recalc_timestamp = False
    options.canonical_order = True

    font = subset.load_font(str(source), options)
    try:
        sub = subset.Subsetter(options=options)
        sub.populate(text=text)
        sub.subset(font)
        subset.save_font(font, str(target), options)
    finally:
        font.close()


def validate_woff2(path: Path) -> dict[str, Any]:
    font = TTFont(str(path), lazy=True)
    try:
        if font.flavor != "woff2":
            raise RuntimeError(f"WOFF2 flavor validation failed: {path}")
        cmap = set()
        if "cmap" in font:
            for table in font["cmap"].tables:
                if table.isUnicode():
                    cmap.update(table.cmap.keys())
        if not cmap:
            raise RuntimeError(f"Unicode cmap missing: {path}")
        return {"unicodeChars": len(cmap), "bytes": path.stat().st_size, "sha256": sha256(path)}
    finally:
        font.close()


def css_for_family(css_family: str, weights: list[int]) -> str:
    lines = ["/* Generated by B.R.A.N.D webfont builder. Do not hand-edit. */"]
    for weight in sorted(weights):
        lines.extend([
            "@font-face {",
            f"  font-family: '{css_family}';",
            f"  src: url('./{weight}.woff2') format('woff2');",
            f"  font-weight: {weight};",
            "  font-style: normal;",
            "  font-display: swap;",
            "}",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def collect_font_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*") if p.is_file() and p.suffix.lower() in {".ttf", ".otf"})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", help="TTF/OTF directory or ZIP")
    parser.add_argument("--out", default="webfonts_output", help="output directory")
    parser.add_argument("--allow-postscript-fallback", action="store_true", help="allow matching changed files by PostScript name when SHA differs")
    parser.add_argument("--only", default="", help="comma-separated slugs for partial validation/rebuild; default builds all 27")
    parser.add_argument("--brotli-quality", type=int, default=8, choices=range(0, 12), metavar="0..11", help="WOFF2 Brotli quality; 8 is the validated stable default for the 45-face Korean font set; 10/11 are slower")
    args = parser.parse_args()

    # fontTools' internal Brotli exposure differs by version.
    # Older/some versions expose `fontTools.ttLib.woff2.brotli`; others do not.
    # The quality override is an optimization only, never a correctness requirement.
    # If the internal Brotli module is available, honor --brotli-quality.
    # Otherwise let fontTools use its own supported/default WOFF2 compressor.
    _woff2_brotli = getattr(woff2_module, "brotli", None)
    if _woff2_brotli is not None and hasattr(_woff2_brotli, "compress"):
        _original_brotli_compress = _woff2_brotli.compress

        def _brand_brotli_compress(data, *compress_args, **compress_kwargs):
            compress_kwargs["quality"] = args.brotli_quality
            return _original_brotli_compress(data, *compress_args, **compress_kwargs)

        _woff2_brotli.compress = _brand_brotli_compress
    else:
        print(
            f"[INFO] fontTools가 내부 brotli 객체를 노출하지 않아 "
            f"--brotli-quality={args.brotli_quality} 강제 설정을 건너뜁니다. "
            "WOFF2 생성은 fontTools 기본 압축 설정으로 계속합니다."
        )

    config = json.loads(CONFIG_PATH.read_text("utf-8"))
    selected_slugs = {x.strip() for x in args.only.split(",") if x.strip()}
    selected_families = [
        family for family in config["families"]
        if not selected_slugs or family["slug"] in selected_slugs
    ]
    if selected_slugs:
        known = {family["slug"] for family in config["families"]}
        unknown = selected_slugs - known
        if unknown:
            raise SystemExit(f"알 수 없는 slug: {', '.join(sorted(unknown))}")
        if not selected_families:
            raise SystemExit("선택된 family가 없습니다.")
    active_slugs = {family["slug"] for family in selected_families}
    selected_sources = [spec for spec in config["sources"] if spec["slug"] in active_slugs]
    source_arg = Path(args.source).expanduser().resolve()
    out_dir = Path(args.out).expanduser().resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    temp_ctx: tempfile.TemporaryDirectory[str] | None = None
    if source_arg.is_file() and source_arg.suffix.lower() == ".zip":
        temp_ctx = tempfile.TemporaryDirectory(prefix="brand-fonts-")
        scan_root = Path(temp_ctx.name)
        with zipfile.ZipFile(source_arg) as zf:
            zf.extractall(scan_root)
    elif source_arg.is_dir():
        scan_root = source_arg
    else:
        raise SystemExit(f"입력 경로를 찾을 수 없습니다: {source_arg}")

    try:
        discovered = collect_font_files(scan_root)
        if not discovered:
            raise RuntimeError("TTF/OTF 파일이 없습니다.")

        by_hash: dict[str, list[Path]] = {}
        by_ps: dict[str, list[Path]] = {}
        for path in discovered:
            by_hash.setdefault(sha256(path), []).append(path)
            by_ps.setdefault(postscript_name(path), []).append(path)

        resolved: dict[tuple[str, int], Path] = {}
        source_checks: list[dict[str, Any]] = []
        for spec in selected_sources:
            candidates = by_hash.get(spec["sha256"], [])
            match_mode = "sha256"
            if len(candidates) != 1:
                if not args.allow_postscript_fallback:
                    raise RuntimeError(
                        f"원본 일치 실패: {spec['itemUid']} weight={spec['weight']} "
                        f"(SHA exact match {len(candidates)}개). 원본이 바뀌었다면 먼저 재감사하세요."
                    )
                candidates = by_ps.get(spec["postscriptName"], [])
                match_mode = "postscript-fallback"
            if len(candidates) != 1:
                raise RuntimeError(
                    f"폰트 식별 실패: PS={spec['postscriptName']} candidates={len(candidates)}"
                )
            path = candidates[0]
            key = (spec["slug"], int(spec["weight"]))
            if key in resolved:
                raise RuntimeError(f"중복 logical face: {key}")
            resolved[key] = path
            source_checks.append({
                "itemUid": spec["itemUid"], "slug": spec["slug"], "weight": int(spec["weight"]),
                "source": path.name, "matchMode": match_mode, "sourceSha256": sha256(path),
            })

        expected = len(selected_sources)
        if len(resolved) != expected:
            raise RuntimeError(f"logical face count mismatch: {len(resolved)} != {expected}")

        manifest: dict[str, Any] = {
            "version": 1,
            "sourceFaceCount": len(resolved),
            "discoveredFontFileCount": len(discovered),
            "previewText": config["previewText"],
            "brotliQuality": args.brotli_quality,
            "partialBuild": bool(selected_slugs),
            "selectedSlugs": sorted(active_slugs),
            "families": [],
            "sourceChecks": source_checks,
        }

        for family in selected_families:
            slug = family["slug"]
            family_dir = out_dir / slug
            family_dir.mkdir(parents=True, exist_ok=True)
            face_results = []
            for weight in family["availableWeights"]:
                source = resolved[(slug, int(weight))]
                target = family_dir / f"{int(weight)}.woff2"
                print(f"[runtime] {slug} {weight} <- {source.name}", flush=True)
                write_full_woff2(source, target)
                meta = validate_woff2(target)
                face_results.append({"weight": int(weight), "file": target.name, **meta})

            default_weight = int(family["defaultWeight"])
            preview_source = resolved[(slug, default_weight)]
            preview_target = family_dir / "preview.woff2"
            print(f"[preview] {slug} <- {preview_source.name}", flush=True)
            write_preview_woff2(preview_source, preview_target, config["previewText"])
            preview_meta = validate_woff2(preview_target)

            (family_dir / "font.css").write_text(
                css_for_family(family["cssFamily"], [int(x) for x in family["availableWeights"]]),
                "utf-8",
            )
            manifest["families"].append({
                "itemUid": family["itemUid"], "slug": slug,
                "cssFamily": family["cssFamily"], "previewFamily": family["previewFamily"],
                "defaultWeight": default_weight, "faces": face_results,
                "preview": {"file": "preview.woff2", **preview_meta},
            })

        manifest["runtimeWoff2Bytes"] = sum(face["bytes"] for fam in manifest["families"] for face in fam["faces"])
        manifest["previewWoff2Bytes"] = sum(fam["preview"]["bytes"] for fam in manifest["families"])
        (out_dir / "build_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), "utf-8")
        print(f"\nOK: {len(manifest['families'])} families / {len(resolved)} runtime faces", flush=True)
        print(f"Runtime WOFF2 total: {manifest['runtimeWoff2Bytes']/1024/1024:.2f} MiB", flush=True)
        print(f"Preview WOFF2 total: {manifest['previewWoff2Bytes']/1024/1024:.2f} MiB", flush=True)
        return 0
    finally:
        if temp_ctx is not None:
            temp_ctx.cleanup()


if __name__ == "__main__":
    raise SystemExit(main())
