-- B.R.A.N.D 2.0 Records / Hall of Glory cross-season archive
-- Designed 2026-09-05 after Production READ-ONLY preflight.
-- IMPORTANT: Production application must follow the project protocol:
-- READ-ONLY PREFLIGHT -> guard -> ROLLBACK REHEARSAL -> ONE-TIME APPLY -> STRICT POSTCHECK -> Runtime/Auth E2E.

create table if not exists public.records_historical_entries (
  id bigint generated by default as identity primary key,
  record_key text not null unique,
  hall_key text not null,
  record_type text not null,
  title text not null,
  subtitle text,
  description text,
  subject_kind text not null default 'STUDENT',
  subject_display_name text not null,
  subject_brand_name text,
  subject_student_id integer references public.students(id) on delete set null,
  subject_guild_id integer references public.guilds(id) on delete set null,
  school_year integer,
  season_label text,
  period_label text,
  occurred_on date,
  rank_position integer,
  value_primary numeric,
  value_secondary numeric,
  denominator numeric,
  unit text,
  comparison_value numeric,
  source_kind text not null default 'CURATED',
  source_ref text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'ACTIVE',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_historical_entries_hall_key_check check (
    hall_key in (
      'PIONEERS',
      'THRONE',
      'REPEATED_CROWNS',
      'ASCENT',
      'GOLDEN_CHRONICLE',
      'GUILD_HEGEMONY',
      'ARCADE_RULERS',
      'CONSTELLATION',
      'SOVEREIGN_PROOF'
    )
  ),
  constraint records_historical_entries_subject_kind_check check (
    subject_kind in ('STUDENT','GUILD','SYSTEM','EMPTY_THRONE')
  ),
  constraint records_historical_entries_source_kind_check check (
    source_kind in ('CURATED','PRODUCTION_SNAPSHOT','PRODUCTION_DERIVED')
  ),
  constraint records_historical_entries_status_check check (
    status in ('ACTIVE','ARCHIVED')
  ),
  constraint records_historical_entries_rank_check check (
    rank_position is null or rank_position > 0
  )
);

comment on table public.records_historical_entries is
  'Cross-season Hall of Glory archive. Historical display-name snapshots are authoritative; current student/guild FK links are optional.';
comment on column public.records_historical_entries.record_key is
  'Stable semantic identity for idempotent historical seed/update operations.';
comment on column public.records_historical_entries.subject_display_name is
  'Historical snapshot name. Never reconstruct past people by joining current students.';
comment on column public.records_historical_entries.comparison_value is
  'Optional normalized value used only for cross-era comparison while value_primary preserves the displayed/original metric.';

create index if not exists records_historical_entries_hall_idx
  on public.records_historical_entries (hall_key, status, sort_order, id);
create index if not exists records_historical_entries_year_idx
  on public.records_historical_entries (school_year, occurred_on, id);
create index if not exists records_historical_entries_type_idx
  on public.records_historical_entries (record_type, status, comparison_value desc nulls last, value_primary desc nulls last);

alter table public.records_historical_entries enable row level security;
revoke all on table public.records_historical_entries from public;
revoke all on table public.records_historical_entries from anon;
revoke all on table public.records_historical_entries from authenticated;

create table if not exists public.records_monthly_mvp_archive (
  id bigint generated by default as identity primary key,
  period_key text not null unique,
  school_year integer not null,
  month_no integer not null,
  period_label text not null,
  winner_display_name text not null,
  winner_student_id integer references public.students(id) on delete set null,
  finalists jsonb not null default '[]'::jsonb,
  source_kind text not null default 'CURATED',
  source_ref text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_monthly_mvp_month_check check (month_no between 1 and 12),
  constraint records_monthly_mvp_source_kind_check check (
    source_kind in ('CURATED','PRODUCTION_SNAPSHOT','PRODUCTION_DERIVED')
  ),
  constraint records_monthly_mvp_status_check check (
    status in ('ACTIVE','ARCHIVED')
  ),
  constraint records_monthly_mvp_finalists_array_check check (jsonb_typeof(finalists) = 'array')
);

comment on table public.records_monthly_mvp_archive is
  'Cross-season official Monthly MVP archive. finalists stores official final-round candidates including the winner.';

create index if not exists records_monthly_mvp_archive_period_idx
  on public.records_monthly_mvp_archive (school_year, month_no, id);

alter table public.records_monthly_mvp_archive enable row level security;
revoke all on table public.records_monthly_mvp_archive from public;
revoke all on table public.records_monthly_mvp_archive from anon;
revoke all on table public.records_monthly_mvp_archive from authenticated;

create or replace function public.student_get_records_hall_of_glory()
returns jsonb
language plpgsql
stable
security definer
set search_path = 'public', 'pg_temp'
as $$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_entries jsonb;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS] authenticated classroom member context is required.' using errcode='P0930';
  end if;

  select coalesce(jsonb_agg(to_jsonb(q) order by q.hall_key, q.sort_order, q.rank_position nulls last, q.id), '[]'::jsonb)
  into v_entries
  from (
    select
      h.id,
      h.record_key,
      h.hall_key,
      h.record_type,
      h.title,
      h.subtitle,
      h.description,
      h.subject_kind,
      h.subject_display_name,
      h.subject_brand_name,
      h.school_year,
      h.season_label,
      h.period_label,
      h.occurred_on,
      h.rank_position,
      h.value_primary,
      h.value_secondary,
      h.denominator,
      h.unit,
      h.comparison_value,
      h.source_kind,
      h.metadata,
      h.sort_order
    from public.records_historical_entries h
    where h.status='ACTIVE'
  ) q;

  return jsonb_build_object(
    'entries', v_entries,
    'gap_eras', jsonb_build_array(
      jsonb_build_object(
        'start_year', 2024,
        'end_year', 2025,
        'title', '공백의 2년',
        'subtitle', '기록이 침묵한 시대'
      )
    )
  );
end;
$$;

revoke all on function public.student_get_records_hall_of_glory() from public;
revoke all on function public.student_get_records_hall_of_glory() from anon;
grant execute on function public.student_get_records_hall_of_glory() to authenticated;

create or replace function public.student_get_records_monthly_mvp_archive()
returns jsonb
language plpgsql
stable
security definer
set search_path = 'public', 'pg_temp'
as $$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_rows jsonb;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS] authenticated classroom member context is required.' using errcode='P0930';
  end if;

  select coalesce(jsonb_agg(to_jsonb(q) order by q.school_year, q.month_no, q.id), '[]'::jsonb)
  into v_rows
  from (
    select
      m.id,
      m.period_key,
      m.school_year,
      m.month_no,
      m.period_label,
      m.winner_display_name,
      m.finalists,
      m.source_kind,
      m.metadata
    from public.records_monthly_mvp_archive m
    where m.status='ACTIVE'
  ) q;

  return jsonb_build_object(
    'rows', v_rows,
    'gap_eras', jsonb_build_array(
      jsonb_build_object(
        'start_year', 2024,
        'end_year', 2025,
        'title', '공백의 2년',
        'subtitle', '기록이 침묵한 시대'
      )
    )
  );
end;
$$;

revoke all on function public.student_get_records_monthly_mvp_archive() from public;
revoke all on function public.student_get_records_monthly_mvp_archive() from anon;
grant execute on function public.student_get_records_monthly_mvp_archive() to authenticated;

-- -----------------------------------------------------------------------------
-- Curated authoritative historical seed
-- Priority: user-confirmed values > source files > Production FINALIZED > old calculations.
-- 2023 BV comparison values are already x1.1 and rounded to the nearest hundred where applicable.
-- -----------------------------------------------------------------------------

insert into public.records_historical_entries (
  record_key,hall_key,record_type,title,subtitle,subject_kind,subject_display_name,
  school_year,season_label,period_label,occurred_on,rank_position,value_primary,value_secondary,denominator,unit,comparison_value,source_kind,metadata,sort_order
) values
  ('PIONEER_MASTER_2023_KIMSEUNGHYUN','PIONEERS','FIRST_TIER_MASTER','최초의 마스터','B.R.A.N.D 역사상 처음으로 마스터의 문을 연 기록','STUDENT','김승현',2023,null,'2023',null,1,75000,null,null,'BV',75000,'CURATED','{"tier":"마스터","threshold_bv":75000}'::jsonb,10),
  ('PIONEER_CELESTIAL_MASTER_2023_KIMSEUNGHYUN','PIONEERS','FIRST_TIER_CELESTIAL_MASTER','최초의 천상의 마스터',null,'STUDENT','김승현',2023,null,'2023',null,1,85000,null,null,'BV',85000,'CURATED','{"tier":"천상의 마스터","threshold_bv":85000}'::jsonb,20),
  ('PIONEER_GRANDMASTER_2023_KIMSEUNGHYUN','PIONEERS','FIRST_TIER_GRANDMASTER','최초의 그랜드마스터',null,'STUDENT','김승현',2023,null,'2023',null,1,100000,null,null,'BV',100000,'CURATED','{"tier":"그랜드마스터","threshold_bv":100000}'::jsonb,30),
  ('PIONEER_FIRST_GOLD_50000_2023_CHOIMINJAE','PIONEERS','FIRST_GOLD_50000','최초 GOLD 50,000 도달',null,'STUDENT','최민재',2023,null,'2023',null,1,50000,null,null,'GOLD',50000,'CURATED','{}'::jsonb,40),
  ('PIONEER_FIRST_GOLD_100000_EMPTY','PIONEERS','FIRST_GOLD_100000','최초 GOLD 100,000 도달','아직 주인이 없는 자리','EMPTY_THRONE','아직 주인이 없는 자리',null,null,null,null,null,100000,null,null,'GOLD',100000,'CURATED','{"unclaimed":true}'::jsonb,50),
  ('PIONEER_FIRST_MONTHLY_MVP_2023_03_KIMSEUNGHYUN','PIONEERS','FIRST_MONTHLY_MVP','최초 월간 MVP','2023년 3월','STUDENT','김승현',2023,null,'2023년 3월','2023-03-31',1,1,null,null,'회',1,'CURATED','{}'::jsonb,60),
  ('PIONEER_FIRST_UNIQUE_2026_KIMSEOYOUNG','PIONEERS','FIRST_UNIQUE_ACHIEVEMENT','최초 유일 업적 달성','랭크 브레이커','STUDENT','김서영',2026,null,'2026',null,1,1,null,null,'개',1,'CURATED','{"display_achievement_name":"랭크 브레이커","production_variants":["랭크 브레이커C","랭크 브레이커B","랭크 브레이커A","랭크 브레이커S"]}'::jsonb,70),
  ('PIONEER_FIRST_TRANSCENDENT_2026_PARKSEOEUN','PIONEERS','FIRST_TRANSCENDENT_ACHIEVEMENT','최초 초월 업적 달성','마스터피스','STUDENT','박서은',2026,null,'2026','2026-04-17',1,1,null,null,'개',1,'CURATED','{"achievement_name":"마스터피스"}'::jsonb,80),
  ('PIONEER_FIRST_ACHIEVEMENT_90_EMPTY','PIONEERS','FIRST_ACHIEVEMENT_90_PERCENT','최초 업적 90% 달성','아직 주인이 없는 자리','EMPTY_THRONE','아직 주인이 없는 자리',null,null,null,null,null,90,null,100,'%',90,'CURATED','{"unclaimed":true}'::jsonb,90),
  ('PIONEER_FIRST_ACHIEVEMENT_100_EMPTY','PIONEERS','FIRST_ACHIEVEMENT_100','최초 업적 100개 달성','아직 주인이 없는 자리','EMPTY_THRONE','아직 주인이 없는 자리',null,null,null,null,null,100,null,null,'개',100,'CURATED','{"unclaimed":true}'::jsonb,100),

  ('GRANDMASTER_ROLL_2023_KIMSEUNGHYUN','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','김승현',2023,null,'2023',null,1,115300,104803,null,'BV',115300,'CURATED','{"raw_bv":104803,"display_bv":115300,"adjustment":"x1.1_then_round_100"}'::jsonb,120),
  ('GRANDMASTER_ROLL_2023_CHOIMINJAE','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','최민재',2023,null,'2023',null,2,106900,97188,null,'BV',106900,'CURATED','{"raw_bv":97188,"display_bv":106900,"adjustment":"x1.1_then_round_100"}'::jsonb,121),
  ('GRANDMASTER_ROLL_2023_LEEJUNHYUK','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','이준혁',2023,null,'2023',null,3,104300,94784,null,'BV',104300,'CURATED','{"raw_bv":94784,"display_bv":104300,"adjustment":"x1.1_then_round_100"}'::jsonb,122),
  ('GRANDMASTER_ROLL_2023_GONGYESEONG','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','공예성',2023,null,'2023',null,4,102200,92930,null,'BV',102200,'CURATED','{"raw_bv":92930,"display_bv":102200,"adjustment":"x1.1_then_round_100"}'::jsonb,123),
  ('GRANDMASTER_ROLL_2023_MINSEOHONG','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','민서홍',2023,null,'2023',null,5,101900,92600,null,'BV',101900,'CURATED','{"raw_bv":92600,"display_bv":101900,"adjustment":"x1.1_then_round_100"}'::jsonb,124),
  ('GRANDMASTER_ROLL_2023_LEEHYEJUN','PIONEERS','GRANDMASTER_ROLL','역대 그랜드마스터 명예록',null,'STUDENT','이혜준',2023,null,'2023',null,6,101200,91990,null,'BV',101200,'CURATED','{"raw_bv":91990,"display_bv":101200,"adjustment":"x1.1_then_round_100"}'::jsonb,125),

  ('THRONE_BV_2023_1_KIMSEUNGHYUN','THRONE','ALL_TIME_BV','역대 최고 BV',null,'STUDENT','김승현',2023,null,'2023',null,1,115300,104803,null,'BV',115300,'CURATED','{"raw_bv":104803,"display_bv":115300,"adjustment":"x1.1_then_round_100"}'::jsonb,10),
  ('THRONE_GOLD_2023_1_CHOIMINJAE','THRONE','ALL_TIME_GOLD_BALANCE','역대 최고 보유 GOLD','2023년 11월','STUDENT','최민재',2023,null,'2023년 11월','2023-11-30',1,81715,null,null,'GOLD',81715,'CURATED','{}'::jsonb,20),
  ('THRONE_GOLD_2023_2_KIMSEUNGHYUN','THRONE','ALL_TIME_GOLD_BALANCE','역대 최고 보유 GOLD','2023년 11월','STUDENT','김승현',2023,null,'2023년 11월','2023-11-30',2,65015,null,null,'GOLD',65015,'CURATED','{}'::jsonb,21),
  ('THRONE_GOLD_2023_3_KIMCHAEUN','THRONE','ALL_TIME_GOLD_BALANCE','역대 최고 보유 GOLD','2023년 11월','STUDENT','김채은',2023,null,'2023년 11월','2023-11-30',3,53632,null,null,'GOLD',53632,'CURATED','{}'::jsonb,22),
  ('THRONE_GOLD_2023_4_MINSEOHONG','THRONE','ALL_TIME_GOLD_BALANCE','역대 최고 보유 GOLD','2023년 11월','STUDENT','민서홍',2023,null,'2023년 11월','2023-11-30',4,53014,null,null,'GOLD',53014,'CURATED','{}'::jsonb,23),
  ('THRONE_GOLD_2023_5_LEEHYEJUN','THRONE','ALL_TIME_GOLD_BALANCE','역대 최고 보유 GOLD','2023년 12월','STUDENT','이혜준',2023,null,'2023년 12월','2023-12-31',5,51210,null,null,'GOLD',51210,'CURATED','{}'::jsonb,24),

  ('CROWN_MVP_FIRST_2_2023_KIMSEUNGHYUN','REPEATED_CROWNS','FIRST_MVP_2','최초 월간 MVP 2회 수상','2023년 8월에 두 번째 왕관을 획득','STUDENT','김승현',2023,null,'2023년 8월','2023-08-31',1,2,null,null,'회',2,'CURATED','{}'::jsonb,10),
  ('CROWN_MVP_FIRST_3_EMPTY','REPEATED_CROWNS','FIRST_MVP_3','최초 월간 MVP 3회 수상','아직 주인이 없는 자리','EMPTY_THRONE','아직 주인이 없는 자리',null,null,null,null,null,3,null,null,'회',3,'CURATED','{"unclaimed":true}'::jsonb,20),
  ('CROWN_MVP_FINALIST_2023_KIMSEUNGHYUN','REPEATED_CROWNS','MOST_MVP_FINALS','역대 최다 월간 MVP 후보 선정','2023년 공식 본선 7회 진출','STUDENT','김승현',2023,null,'2023',null,1,7,null,null,'회',7,'CURATED','{}'::jsonb,30),

  ('ASCENT_MONTH_BV_2023_1_KIMSEUNGHYUN','ASCENT','MONTHLY_BV_GAIN','한 달 최대 BV 상승량','2023년 5월','STUDENT','김승현',2023,null,'2023년 5월','2023-05-31',1,17700,null,null,'BV',17700,'CURATED','{}'::jsonb,10),
  ('ASCENT_MONTH_BV_2023_2_CHOIMINJAE','ASCENT','MONTHLY_BV_GAIN','한 달 최대 BV 상승량','2023년 11월','STUDENT','최민재',2023,null,'2023년 11월','2023-11-30',2,17200,null,null,'BV',17200,'CURATED','{}'::jsonb,11),
  ('ASCENT_MONTH_BV_2023_3_KIMCHAEUN','ASCENT','MONTHLY_BV_GAIN','한 달 최대 BV 상승량','2023년 11월','STUDENT','김채은',2023,null,'2023년 11월','2023-11-30',3,15600,null,null,'BV',15600,'CURATED','{}'::jsonb,12),
  ('ASCENT_MONTH_BV_2023_4_MINSEOHONG','ASCENT','MONTHLY_BV_GAIN','한 달 최대 BV 상승량','2023년 12월','STUDENT','민서홍',2023,null,'2023년 12월','2023-12-31',4,15500,null,null,'BV',15500,'CURATED','{}'::jsonb,13),
  ('ASCENT_MONTH_BV_2023_5_KIMSEUNGHYUN','ASCENT','MONTHLY_BV_GAIN','한 달 최대 BV 상승량','2023년 11월','STUDENT','김승현',2023,null,'2023년 11월','2023-11-30',5,14540,null,null,'BV',14540,'CURATED','{}'::jsonb,14),

  ('GOLD_DONATION_2023_1_LEESEOLYEON','GOLDEN_CHRONICLE','LIFETIME_DONATION','역대 최고 누적 기부','2023 내부 TOP3 · 향후 2026과 통합 비교','STUDENT','이설연',2023,null,'2023',null,1,27000,null,null,'GOLD',27000,'CURATED','{"scope":"2023_internal_top3"}'::jsonb,10),
  ('GOLD_DONATION_2023_2_MINSEOHONG','GOLDEN_CHRONICLE','LIFETIME_DONATION','역대 최고 누적 기부','2023 내부 TOP3 · 향후 2026과 통합 비교','STUDENT','민서홍',2023,null,'2023',null,2,22000,null,null,'GOLD',22000,'CURATED','{"scope":"2023_internal_top3"}'::jsonb,11),
  ('GOLD_DONATION_2023_3_PARKSOYUL','GOLDEN_CHRONICLE','LIFETIME_DONATION','역대 최고 누적 기부','2023 내부 TOP3 · 향후 2026과 통합 비교','STUDENT','박소율',2023,null,'2023',null,3,20000,null,null,'GOLD',20000,'CURATED','{"scope":"2023_internal_top3"}'::jsonb,12),
  ('GOLD_STOCK_DIVIDEND_2023_KIMSEUNGHYUN','GOLDEN_CHRONICLE','STOCK_DIVIDEND_2023','2023 주식시대 최고의 배당 수익','배당수익 컬럼만 누적','STUDENT','김승현',2023,null,'2023',null,1,24749,null,null,'GOLD',24749,'CURATED','{"definition":"배당수익 컬럼만 합산"}'::jsonb,20),

  ('GUILD_SEASON1_CHAMPION_RUBY','GUILD_HEGEMONY','SEASON_CHAMPION','시즌 최종 우승 길드','2026 시즌1','GUILD','Ruby',2026,'2026 시즌1','시즌1',null,1,26826,null,30000,'GS',26826,'CURATED','{"runner_up":"빛나는 은하수","runner_up_gs":26814,"margin_gs":12,"margin_percent":0.0447}'::jsonb,10),
  ('GUILD_MONTH_GS_2026_05_RUBY','GUILD_HEGEMONY','BEST_MONTHLY_GS_RATE','역대 최고 단일 월 GS','2026년 5월','GUILD','Ruby',2026,'2026 시즌1','2026-05','2026-05-31',1,9750,null,10000,'GS',97.50,'CURATED','{"rate_percent":97.50}'::jsonb,20),
  ('GUILD_MONTH_GS_2026_05_GALAXY','GUILD_HEGEMONY','BEST_MONTHLY_GS_RATE','역대 최고 단일 월 GS','2026년 5월','GUILD','빛나는 은하수',2026,'2026 시즌1','2026-05','2026-05-31',2,9734,null,10000,'GS',97.34,'CURATED','{"rate_percent":97.34}'::jsonb,21),
  ('GUILD_MONTH_GS_2026_05_DARKROSE','GUILD_HEGEMONY','BEST_MONTHLY_GS_RATE','역대 최고 단일 월 GS','2026년 5월','GUILD','암흑장미',2026,'2026 시즌1','2026-05','2026-05-31',3,9473,null,10000,'GS',94.73,'CURATED','{"rate_percent":94.73}'::jsonb,22),
  ('GUILD_MONTH_GS_2026_07_RUBY','GUILD_HEGEMONY','BEST_MONTHLY_GS_RATE','역대 최고 단일 월 GS','2026년 7월','GUILD','Ruby',2026,'2026 시즌1','2026-07','2026-07-31',4,9025,null,10000,'GS',90.25,'CURATED','{"rate_percent":90.25}'::jsonb,23),
  ('GUILD_MONTH_GS_2026_07_GALAXY','GUILD_HEGEMONY','BEST_MONTHLY_GS_RATE','역대 최고 단일 월 GS','2026년 7월','GUILD','빛나는 은하수',2026,'2026 시즌1','2026-07','2026-07-31',5,8980,null,10000,'GS',89.80,'CURATED','{"rate_percent":89.80}'::jsonb,24),
  ('GUILD_MONTH_CONTRIB_2026_05_JEONGMINJUN','GUILD_HEGEMONY','BEST_MONTHLY_CONTRIBUTION_RATE','역대 최고 월간 기여도 달성률','2026년 5월 · 에메랄드','STUDENT','정민준',2026,'2026 시즌1','2026-05','2026-05-31',1,750,null,900,'점',83.33,'CURATED','{"guild":"에메랄드","rate_percent":83.33}'::jsonb,30),
  ('GUILD_SEASON_CONTRIB_2026_S1_HANSEOHYEON','GUILD_HEGEMONY','SEASON_CONTRIBUTION_CHAMPION','시즌 개인 기여도 1위','2026 시즌1','STUDENT','한서현',2026,'2026 시즌1','시즌1',null,1,1860,null,2300,'점',80.87,'CURATED','{"rate_percent":80.87,"normalization":"none"}'::jsonb,40),
  ('GUILD_CLOSEST_WIN_2026_S1_RUBY','GUILD_HEGEMONY','CLOSEST_SEASON_WIN','가장 근소한 시즌 우승','Ruby vs 빛나는 은하수 · 12 GS 차','GUILD','Ruby',2026,'2026 시즌1','시즌1',null,1,12,26826,null,'GS',0.0447,'CURATED','{"runner_up":"빛나는 은하수","runner_up_gs":26814,"margin_percent":0.0447}'::jsonb,50),

  ('SOVEREIGN_EMPEROR_2026_S1_HANSEOHYEON','SOVEREIGN_PROOF','SEASON_EMPEROR','시즌의 황제','2026 시즌1','STUDENT','한서현',2026,'2026 시즌1','시즌1',null,1,1,null,null,'달성',1,'CURATED','{}'::jsonb,10),
  ('SOVEREIGN_EMPEROR_2026_S1_KIMSEOYOUNG','SOVEREIGN_PROOF','SEASON_EMPEROR','시즌의 황제','2026 시즌1','STUDENT','김서영',2026,'2026 시즌1','시즌1',null,1,1,null,null,'달성',1,'CURATED','{}'::jsonb,11)
on conflict (record_key) do update set
  hall_key=excluded.hall_key,
  record_type=excluded.record_type,
  title=excluded.title,
  subtitle=excluded.subtitle,
  subject_kind=excluded.subject_kind,
  subject_display_name=excluded.subject_display_name,
  school_year=excluded.school_year,
  season_label=excluded.season_label,
  period_label=excluded.period_label,
  occurred_on=excluded.occurred_on,
  rank_position=excluded.rank_position,
  value_primary=excluded.value_primary,
  value_secondary=excluded.value_secondary,
  denominator=excluded.denominator,
  unit=excluded.unit,
  comparison_value=excluded.comparison_value,
  source_kind=excluded.source_kind,
  metadata=excluded.metadata,
  sort_order=excluded.sort_order,
  updated_at=now();

insert into public.records_monthly_mvp_archive (
  period_key,school_year,month_no,period_label,winner_display_name,winner_student_id,finalists,source_kind,metadata
) values
  ('2023-03',2023,3,'2023년 3월','김승현',null,'["김승현","공예성","최나연","이가온"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-04',2023,4,'2023년 4월','최나연',null,'["최나연","김승현","이혜준","이가온"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-05',2023,5,'2023년 5월','최민재',null,'["최민재","김승현","이준혁","이선후"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-06',2023,6,'2023년 6월','공예성',null,'["공예성","민서홍","최민재","풍아정"]'::jsonb,'CURATED','{"authority_note":"사용자 직접 정정값"}'::jsonb),
  ('2023-07',2023,7,'2023년 7월','김채은',null,'["김채은","김승현","이선후","최민재"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-08',2023,8,'2023년 8월','김승현',null,'["김승현","김채은","이설연","풍아정"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-09',2023,9,'2023년 9월','이가온',null,'["이가온","공예성","김승현","이준혁"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-10',2023,10,'2023년 10월','민서홍',null,'["민서홍","이준혁","김승현","임희석"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-11',2023,11,'2023년 11월','이준혁',null,'["이준혁","민서홍","최민재","이예지"]'::jsonb,'CURATED','{}'::jsonb),
  ('2023-12',2023,12,'2023년 12월','공예성',null,'["공예성","민서홍","최나연","한재아"]'::jsonb,'CURATED','{}'::jsonb),
  ('2026-03',2026,3,'2026년 3월','김서영',3,'["김서영","류은우","한서현"]'::jsonb,'CURATED','{"finalist_count":3}'::jsonb),
  ('2026-04',2026,4,'2026년 4월','류은우',7,'["김서영","류은우","김윤우","부희주"]'::jsonb,'CURATED','{}'::jsonb),
  ('2026-05',2026,5,'2026년 5월','한서현',23,'["김서영","정민준","이태우","한서현"]'::jsonb,'CURATED','{}'::jsonb),
  ('2026-06',2026,6,'2026년 6월','류은우',7,'["류은우","지담","한서현","김서영"]'::jsonb,'CURATED','{}'::jsonb),
  ('2026-07',2026,7,'2026년 7월','김서영',3,'["김서영","지담","한서현","정우림"]'::jsonb,'CURATED','{}'::jsonb)
on conflict (period_key) do update set
  school_year=excluded.school_year,
  month_no=excluded.month_no,
  period_label=excluded.period_label,
  winner_display_name=excluded.winner_display_name,
  winner_student_id=excluded.winner_student_id,
  finalists=excluded.finalists,
  source_kind=excluded.source_kind,
  metadata=excluded.metadata,
  updated_at=now();
