-- B.R.A.N.D 2.0 Records Guestbook V1
-- PRODUCTION STATUS: ALREADY APPLIED ON 2026-09-07.
-- DO NOT RUN THIS FILE AGAIN ON PRODUCTION.
-- This repository copy exists only to keep source control aligned with the applied schema.

create table public.records_guestbook_entries (
  id bigint generated by default as identity primary key,
  owner_teacher_user_id uuid not null,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  school_year integer not null check (school_year between 2000 and 2100),
  student_id integer not null references public.students(id) on delete restrict,
  student_name_snapshot text not null,
  brand_name_snapshot text,
  message text not null check (char_length(message) between 1 and 80),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint records_guestbook_one_per_student_year
    unique (owner_teacher_user_id, school_year, student_id)
);

create index records_guestbook_owner_year_created_idx
  on public.records_guestbook_entries (owner_teacher_user_id, school_year desc, created_at desc);

alter table public.records_guestbook_entries enable row level security;

revoke all on table public.records_guestbook_entries from public, anon, authenticated;
revoke all on sequence public.records_guestbook_entries_id_seq from public, anon, authenticated;

create or replace function public.student_get_records_guestbook(
  p_limit integer default 200,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 200);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_total integer := 0;
  v_rows jsonb := '[]'::jsonb;
  v_my_entry jsonb := null;
  v_can_write boolean := false;
begin
  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_GUESTBOOK] authenticated classroom context is required.'
      using errcode = 'P0940';
  end if;

  select c.teacher_user_id, c.school_year
    into v_owner_teacher_user_id, v_school_year
  from public.classrooms c
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null then
    raise exception '[RECORDS_GUESTBOOK] classroom lineage could not be resolved.'
      using errcode = 'P0941';
  end if;

  v_can_write := v_student_id is not null
                 and public.is_official_participant(v_student_id);

  select count(*)::integer
    into v_total
  from public.records_guestbook_entries e
  where e.owner_teacher_user_id = v_owner_teacher_user_id;

  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'id', x.id,
               'school_year', x.school_year,
               'student_name', x.student_name_snapshot,
               'brand_name', x.brand_name_snapshot,
               'message', x.message,
               'created_at', x.created_at,
               'updated_at', x.updated_at,
               'is_mine', (v_student_id is not null and x.student_id = v_student_id)
             )
             order by x.school_year desc, x.created_at desc, x.id desc
           ),
           '[]'::jsonb
         )
    into v_rows
  from (
    select e.*
    from public.records_guestbook_entries e
    where e.owner_teacher_user_id = v_owner_teacher_user_id
    order by e.school_year desc, e.created_at desc, e.id desc
    limit v_limit offset v_offset
  ) x;

  if v_student_id is not null then
    select jsonb_build_object(
             'id', e.id,
             'school_year', e.school_year,
             'student_name', e.student_name_snapshot,
             'brand_name', e.brand_name_snapshot,
             'message', e.message,
             'created_at', e.created_at,
             'updated_at', e.updated_at,
             'is_mine', true
           )
      into v_my_entry
    from public.records_guestbook_entries e
    where e.owner_teacher_user_id = v_owner_teacher_user_id
      and e.school_year = v_school_year
      and e.student_id = v_student_id
    limit 1;
  end if;

  return jsonb_build_object(
    'current_school_year', v_school_year,
    'can_write', v_can_write,
    'total_count', v_total,
    'limit', v_limit,
    'offset', v_offset,
    'my_entry', v_my_entry,
    'rows', v_rows
  );
end;
$function$;

create or replace function public.student_upsert_records_guestbook(
  p_message text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_student_id integer := public.current_student_id();
  v_owner_teacher_user_id uuid;
  v_school_year integer;
  v_student_name text;
  v_brand_name text;
  v_message text;
  v_entry public.records_guestbook_entries%rowtype;
begin
  if auth.uid() is null or v_classroom_id is null or v_student_id is null then
    raise exception '[RECORDS_GUESTBOOK] authenticated student context is required.'
      using errcode = 'P0942';
  end if;

  if not public.is_official_participant(v_student_id) then
    raise exception '[RECORDS_GUESTBOOK] only official participants may leave a guestbook entry.'
      using errcode = 'P0943';
  end if;

  select c.teacher_user_id, c.school_year, s.name, s.brand_name
    into v_owner_teacher_user_id, v_school_year, v_student_name, v_brand_name
  from public.classrooms c
  join public.students s
    on s.id = v_student_id
   and s.classroom_id = c.id
   and s.transferred_at is null
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null or v_school_year is null or v_student_name is null then
    raise exception '[RECORDS_GUESTBOOK] student lineage could not be resolved.'
      using errcode = 'P0944';
  end if;

  v_message := regexp_replace(btrim(coalesce(p_message, '')), '[[:space:]]+', ' ', 'g');

  if char_length(v_message) < 1 or char_length(v_message) > 80 then
    raise exception '[RECORDS_GUESTBOOK] message must be between 1 and 80 characters.'
      using errcode = 'P0945';
  end if;

  insert into public.records_guestbook_entries (
    owner_teacher_user_id,
    classroom_id,
    school_year,
    student_id,
    student_name_snapshot,
    brand_name_snapshot,
    message
  )
  values (
    v_owner_teacher_user_id,
    v_classroom_id,
    v_school_year,
    v_student_id,
    v_student_name,
    v_brand_name,
    v_message
  )
  on conflict (owner_teacher_user_id, school_year, student_id)
  do update set
    classroom_id = excluded.classroom_id,
    student_name_snapshot = excluded.student_name_snapshot,
    brand_name_snapshot = excluded.brand_name_snapshot,
    message = excluded.message,
    updated_at = now()
  returning * into v_entry;

  return jsonb_build_object(
    'id', v_entry.id,
    'school_year', v_entry.school_year,
    'student_name', v_entry.student_name_snapshot,
    'brand_name', v_entry.brand_name_snapshot,
    'message', v_entry.message,
    'created_at', v_entry.created_at,
    'updated_at', v_entry.updated_at,
    'is_mine', true
  );
end;
$function$;

create or replace function public.teacher_get_records_guestbook(
  p_limit integer default 200,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 200);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_total integer := 0;
  v_rows jsonb := '[]'::jsonb;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_GUESTBOOK] authenticated teacher context is required.'
      using errcode = 'P0946';
  end if;

  select c.teacher_user_id
    into v_owner_teacher_user_id
  from public.classrooms c
  where c.id = v_classroom_id;

  if v_owner_teacher_user_id is null then
    raise exception '[RECORDS_GUESTBOOK] teacher lineage could not be resolved.'
      using errcode = 'P0947';
  end if;

  select count(*)::integer
    into v_total
  from public.records_guestbook_entries e
  where e.owner_teacher_user_id = v_owner_teacher_user_id;

  select coalesce(
           jsonb_agg(
             jsonb_build_object(
               'id', x.id,
               'classroom_id', x.classroom_id,
               'school_year', x.school_year,
               'student_id', x.student_id,
               'student_name', x.student_name_snapshot,
               'brand_name', x.brand_name_snapshot,
               'message', x.message,
               'created_at', x.created_at,
               'updated_at', x.updated_at
             )
             order by x.school_year desc, x.created_at desc, x.id desc
           ),
           '[]'::jsonb
         )
    into v_rows
  from (
    select e.*
    from public.records_guestbook_entries e
    where e.owner_teacher_user_id = v_owner_teacher_user_id
    order by e.school_year desc, e.created_at desc, e.id desc
    limit v_limit offset v_offset
  ) x;

  return jsonb_build_object(
    'total_count', v_total,
    'limit', v_limit,
    'offset', v_offset,
    'rows', v_rows
  );
end;
$function$;

create or replace function public.teacher_delete_records_guestbook(
  p_entry_id bigint
)
returns boolean
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_classroom_id integer := public.current_classroom_id();
  v_owner_teacher_user_id uuid;
  v_deleted_id bigint;
begin
  perform public.ensure_teacher_role();

  if auth.uid() is null or v_classroom_id is null then
    raise exception '[RECORDS_GUESTBOOK] authenticated teacher context is required.'
      using errcode = 'P0948';
  end if;

  select c.teacher_user_id
    into v_owner_teacher_user_id
  from public.classrooms c
  where c.id = v_classroom_id;

  delete from public.records_guestbook_entries e
  where e.id = p_entry_id
    and e.owner_teacher_user_id = v_owner_teacher_user_id
  returning e.id into v_deleted_id;

  if v_deleted_id is null then
    raise exception '[RECORDS_GUESTBOOK] guestbook entry not found in this teacher lineage.'
      using errcode = 'P0949';
  end if;

  return true;
end;
$function$;

revoke all on function public.student_get_records_guestbook(integer, integer) from public, anon;
revoke all on function public.student_upsert_records_guestbook(text) from public, anon;
revoke all on function public.teacher_get_records_guestbook(integer, integer) from public, anon;
revoke all on function public.teacher_delete_records_guestbook(bigint) from public, anon;

grant execute on function public.student_get_records_guestbook(integer, integer) to authenticated;
grant execute on function public.student_upsert_records_guestbook(text) to authenticated;
grant execute on function public.teacher_get_records_guestbook(integer, integer) to authenticated;
grant execute on function public.teacher_delete_records_guestbook(bigint) to authenticated;

comment on table public.records_guestbook_entries is
  'Cross-year B.R.A.N.D records-room guestbook, scoped by teacher lineage. One entry per official student per school year.';
