-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4D: 기록실 · 랭킹 · 분석 · 진단
-- Fault domain: F4D / SQLSTATE P4Dxx
-- ============================================================================
BEGIN;
DO $$ BEGIN
 RAISE NOTICE '[F4D] preflight: records + analytics';
 IF to_regclass('public.rankings') IS NULL OR to_regclass('public.daily_statistics') IS NULL THEN RAISE EXCEPTION '[F4D] ranking/stat tables missing' USING ERRCODE='P4D01'; END IF;
 IF to_regprocedure('public.calculate_daily_statistics(integer,date)') IS NULL OR to_regprocedure('public.calculate_rankings(integer,date)') IS NULL THEN RAISE EXCEPTION '[F4D] calculation functions missing' USING ERRCODE='P4D02'; END IF;
 IF to_regprocedure('public.ensure_teacher_role()') IS NULL OR to_regprocedure('public.is_classroom_member(integer)') IS NULL OR to_regprocedure('public.current_classroom_id()') IS NULL THEN RAISE EXCEPTION '[F4D] identity helpers missing' USING ERRCODE='P4D03'; END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.hall_of_fame_entries(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 category varchar(40) NOT NULL,
 period_label varchar(60),
 title varchar(160) NOT NULL,
 subtitle text,
 student_id integer REFERENCES public.students(id),
 guild_id integer REFERENCES public.guilds(id),
 rank_position integer,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 status varchar(12) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','ARCHIVED')),
 created_by uuid,
 created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(rank_position IS NULL OR rank_position>0)
);
CREATE INDEX IF NOT EXISTS idx_hof_classroom_recent ON public.hall_of_fame_entries(classroom_id,status,created_at DESC);
ALTER TABLE public.hall_of_fame_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='hall_of_fame_entries' AND policyname='hall_of_fame_select_class') THEN
 CREATE POLICY hall_of_fame_select_class ON public.hall_of_fame_entries FOR SELECT TO authenticated USING(public.is_classroom_member(classroom_id)); END IF; END $$;

CREATE OR REPLACE FUNCTION public.teacher_refresh_classroom_records(p_classroom_id integer,p_stat_date date DEFAULT CURRENT_DATE)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_stat integer; v_rank integer; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 IF p_stat_date>(timezone('Asia/Seoul',now()))::date THEN RAISE EXCEPTION '[F4D] future statistics date not allowed' USING ERRCODE='P4D11'; END IF;
 v_stat:=public.calculate_daily_statistics(p_classroom_id,p_stat_date);
 v_rank:=public.calculate_rankings(p_classroom_id,p_stat_date);
 RETURN jsonb_build_object('statistics_id',v_stat,'ranking_rows_last_statement',v_rank,'stat_date',p_stat_date);
END $$;

CREATE OR REPLACE FUNCTION public.teacher_add_hall_of_fame_entry(
 p_classroom_id integer,p_category text,p_period_label text,p_title text,p_subtitle text DEFAULT NULL,p_student_id integer DEFAULT NULL,p_rank_position integer DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id bigint; BEGIN
 PERFORM public.ensure_teacher_role(); IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 IF char_length(btrim(coalesce(p_category,''))) NOT BETWEEN 1 AND 40 OR char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 160 THEN RAISE EXCEPTION '[F4D] record category/title invalid' USING ERRCODE='P4D20'; END IF;
 IF p_student_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.students WHERE id=p_student_id AND classroom_id=p_classroom_id) THEN RAISE EXCEPTION '[F4D] record student mismatch' USING ERRCODE='P4D21'; END IF;
 INSERT INTO public.hall_of_fame_entries(classroom_id,category,period_label,title,subtitle,student_id,rank_position,created_by)
 VALUES(p_classroom_id,btrim(p_category),nullif(btrim(coalesce(p_period_label,'')),''),btrim(p_title),nullif(btrim(coalesce(p_subtitle,'')),''),p_student_id,p_rank_position,auth.uid()) RETURNING id INTO v_id;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_archive_hall_of_fame_entry(p_entry_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_class integer; BEGIN
 PERFORM public.ensure_teacher_role(); SELECT classroom_id INTO v_class FROM public.hall_of_fame_entries WHERE id=p_entry_id FOR UPDATE;
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4D] record entry not found' USING ERRCODE='P4D22'; END IF;
 IF NOT public.is_classroom_member(v_class) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 UPDATE public.hall_of_fame_entries SET status='ARCHIVED' WHERE id=p_entry_id;
END $$;

-- Feature4 전체 설치 상태를 한 번에 진단. 오류 위치를 A/B/C/D로 분리해 반환.
CREATE OR REPLACE FUNCTION public.teacher_feature4_health_check()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE v_class integer; BEGIN
 PERFORM public.ensure_teacher_role(); v_class:=public.current_classroom_id();
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4D] current classroom unavailable' USING ERRCODE='P4D30'; END IF;
 RETURN jsonb_build_object(
  'classroom_id',v_class,'checked_at',now(),
  'F4A',jsonb_build_object(
    'global_alert_reads',to_regclass('public.global_alert_reads') IS NOT NULL,
    'teacher_send_mail',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_send_mail'),
    'mark_global_alert_read',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='mark_global_alert_read'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type)'),'EXECUTE'),
    'mail_helper_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)'),'EXECUTE'),
    'mail_count',(SELECT count(*) FROM public.mail_messages WHERE classroom_id=v_class),
    'alert_count',(SELECT count(*) FROM public.global_alerts WHERE classroom_id=v_class)),
  'F4B',jsonb_build_object(
    'emergency_quests',to_regclass('public.emergency_quests') IS NOT NULL,
    'complete_quest',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='complete_emergency_quest'),
    'expiry_processor',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='process_expired_emergencies'),
    'expiry_classroom_rpc',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='finalize_expired_emergencies_for_classroom'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.finalize_expired_emergencies_for_classroom(integer)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.finalize_expired_emergencies_for_classroom(integer)'),'EXECUTE'),
    'processor_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.process_expired_emergencies()'),'EXECUTE'),
    'active_emergencies',(SELECT count(*) FROM public.emergencies WHERE classroom_id=v_class AND status='ACTIVE'),
    'active_guards',(SELECT count(*) FROM public.guard_terms WHERE classroom_id=v_class AND is_active)),
  'F4C',jsonb_build_object(
    'attendance_bulk',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_record_attendance_bulk'),
    'assignment_create',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_create_assignment'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.submit_assignment(integer,integer,text,jsonb)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.submit_assignment(integer,integer,text,jsonb)'),'EXECUTE'),
    'today_attendance',(SELECT count(*) FROM public.attendances WHERE classroom_id=v_class AND attendance_date=(timezone('Asia/Seoul',now()))::date),
    'assignments',(SELECT count(*) FROM public.assignments WHERE classroom_id=v_class)),
  'F4D',jsonb_build_object(
    'hall_of_fame',to_regclass('public.hall_of_fame_entries') IS NOT NULL,
    'refresh_records',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_refresh_classroom_records'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.teacher_refresh_classroom_records(integer,date)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.teacher_refresh_classroom_records(integer,date)'),'EXECUTE'),
    'calculators_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.calculate_daily_statistics(integer,date)'),'EXECUTE') AND NOT has_function_privilege('authenticated',to_regprocedure('public.calculate_rankings(integer,date)'),'EXECUTE'),
    'statistics_rows',(SELECT count(*) FROM public.daily_statistics WHERE classroom_id=v_class),
    'ranking_rows',(SELECT count(*) FROM public.rankings WHERE classroom_id=v_class),
    'hall_rows',(SELECT count(*) FROM public.hall_of_fame_entries WHERE classroom_id=v_class)),
  'realtime',jsonb_build_object(
    'mail_messages',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='mail_messages'),
    'emergencies',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergencies'),
    'attendances',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='attendances'),
    'rankings',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='rankings'))
 );
END $$;

-- 집계 함수는 직접 브라우저 호출을 막고 교사 wrapper/cron에서만 사용한다.
REVOKE ALL ON FUNCTION public.calculate_daily_statistics(integer,date) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_daily_statistics(integer,date) TO service_role;
REVOKE ALL ON FUNCTION public.calculate_rankings(integer,date) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_rankings(integer,date) TO service_role;

-- ACL: 교사용 외부 RPC의 정확한 시그니처만 authenticated에 공개
REVOKE ALL ON FUNCTION public.teacher_refresh_classroom_records(integer,date) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_refresh_classroom_records(integer,date) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_add_hall_of_fame_entry(integer,text,text,text,text,integer,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_add_hall_of_fame_entry(integer,text,text,text,text,integer,integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_archive_hall_of_fame_entry(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_archive_hall_of_fame_entry(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_feature4_health_check() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_feature4_health_check() TO authenticated,service_role;
REVOKE ALL ON TABLE public.hall_of_fame_entries FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.hall_of_fame_entries FROM authenticated;
GRANT SELECT ON TABLE public.hall_of_fame_entries TO authenticated;
GRANT ALL ON TABLE public.hall_of_fame_entries TO service_role;
DO $$ DECLARE t text; BEGIN IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
 FOREACH t IN ARRAY ARRAY['daily_statistics','rankings','hall_of_fame_entries'] LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t); END IF;
 END LOOP; END IF; END $$;
DO $$ BEGIN RAISE NOTICE '[F4D] installed successfully'; END $$;
COMMIT;

-- 최종 눈으로 확인할 수 있는 단일 결과표
SELECT 'F4A' module,to_regclass('public.global_alert_reads') IS NOT NULL installed
UNION ALL SELECT 'F4B',to_regclass('public.emergency_quests') IS NOT NULL
UNION ALL SELECT 'F4C',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_record_attendance_bulk')
UNION ALL SELECT 'F4D',to_regclass('public.hall_of_fame_entries') IS NOT NULL
ORDER BY module;
