-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4 Bundle
-- F4A 소통 / F4B 학급운영 / F4C 출석·과제 / F4D 기록·분석
--
-- IMPORTANT
-- * 각 모듈은 독립 BEGIN/COMMIT 단위입니다.
-- * 오류 메시지의 [F4A]/[F4B]/[F4C]/[F4D]를 그대로 보고하면 고장 영역을 즉시 분리할 수 있습니다.
-- * 앞 모듈이 COMMIT된 뒤 뒤 모듈이 실패하면 앞 모듈은 유지됩니다. 실패 모듈만 수정/재적용합니다.
-- * 기존 전체 스키마를 재실행하지 마세요.
-- ============================================================================


-- ========================== F4A START ==========================
-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4A: 소통 (우편 · 전역 알림 · 활동 피드)
-- Fault domain: F4A / SQLSTATE P4Axx
-- ============================================================================
BEGIN;

DO $$
BEGIN
  RAISE NOTICE '[F4A] preflight: communications';
  IF to_regclass('public.mail_messages') IS NULL OR to_regclass('public.global_alerts') IS NULL
     OR to_regclass('public.activity_feed_items') IS NULL THEN
    RAISE EXCEPTION '[F4A] required communication tables missing' USING ERRCODE = 'P4A01';
  END IF;
  IF to_regprocedure('public.ensure_teacher_role()') IS NULL
     OR to_regprocedure('public.current_student_id()') IS NULL
     OR to_regprocedure('public.current_classroom_id()') IS NULL
     OR to_regprocedure('public.is_classroom_member(integer)') IS NULL
     OR to_regprocedure('public.is_teacher_or_admin()') IS NULL THEN
    RAISE EXCEPTION '[F4A] required identity helpers missing' USING ERRCODE = 'P4A02';
  END IF;
  IF to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)') IS NULL
     OR to_regprocedure('public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer)') IS NULL
     OR to_regprocedure('public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility)') IS NULL THEN
    RAISE EXCEPTION '[F4A] communication helpers have an unexpected signature' USING ERRCODE = 'P4A03';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.global_alert_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL REFERENCES public.global_alerts(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(alert_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_global_alert_reads_student ON public.global_alert_reads(student_id, read_at DESC);
ALTER TABLE public.global_alert_reads ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='global_alert_reads' AND policyname='global_alert_reads_select_own') THEN
    CREATE POLICY global_alert_reads_select_own ON public.global_alert_reads FOR SELECT TO authenticated
      USING (student_id = public.current_student_id() OR public.is_teacher_or_admin());
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.mark_mail_read(p_message_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  UPDATE public.mail_messages SET is_read=true, read_at=coalesce(read_at, now())
   WHERE id=p_message_id AND recipient_id=v_student_id;
  IF NOT FOUND THEN RAISE EXCEPTION '[F4A] mail not found or not yours' USING ERRCODE='P4A11'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.mark_global_alert_read(p_alert_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer; v_classroom_id integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  SELECT classroom_id INTO v_classroom_id FROM public.global_alerts WHERE id=p_alert_id;
  IF v_classroom_id IS NULL THEN RAISE EXCEPTION '[F4A] alert not found' USING ERRCODE='P4A12'; END IF;
  IF NOT public.is_classroom_member(v_classroom_id) THEN RAISE EXCEPTION '[F4A] alert belongs to another classroom' USING ERRCODE='P4A13'; END IF;
  INSERT INTO public.global_alert_reads(alert_id,student_id) VALUES(p_alert_id,v_student_id)
    ON CONFLICT(alert_id,student_id) DO UPDATE SET read_at=excluded.read_at;
END $$;

CREATE OR REPLACE FUNCTION public.mark_all_global_alerts_read(p_classroom_id integer)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer; v_count integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] classroom access denied' USING ERRCODE='P4A13'; END IF;
  INSERT INTO public.global_alert_reads(alert_id,student_id)
  SELECT a.id,v_student_id FROM public.global_alerts a
   WHERE a.classroom_id=p_classroom_id AND a.status='ACTIVE'
     AND (a.expires_at IS NULL OR a.expires_at>now())
  ON CONFLICT(alert_id,student_id) DO NOTHING;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_send_mail(
  p_classroom_id integer, p_recipient_ids integer[], p_title text, p_body text,
  p_message_type public.mail_message_type DEFAULT 'TEACHER_MESSAGE'::public.mail_message_type
) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_id integer; v_count integer:=0; v_title text; v_body text;
BEGIN
  PERFORM public.ensure_teacher_role();
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] teacher classroom denied' USING ERRCODE='P4A20'; END IF;
  IF p_recipient_ids IS NULL OR cardinality(p_recipient_ids)=0 OR cardinality(p_recipient_ids)>100 THEN
    RAISE EXCEPTION '[F4A] select 1-100 recipients' USING ERRCODE='P4A21';
  END IF;
  IF cardinality(p_recipient_ids) <> (SELECT count(DISTINCT x) FROM unnest(p_recipient_ids) AS x) THEN
    RAISE EXCEPTION '[F4A] duplicate recipients are not allowed' USING ERRCODE='P4A27';
  END IF;
  v_title:=btrim(coalesce(p_title,'')); v_body:=btrim(coalesce(p_body,''));
  IF char_length(v_title)<1 OR char_length(v_title)>200 THEN RAISE EXCEPTION '[F4A] title must be 1-200 chars' USING ERRCODE='P4A22'; END IF;
  IF char_length(v_body)<1 OR char_length(v_body)>5000 THEN RAISE EXCEPTION '[F4A] body must be 1-5000 chars' USING ERRCODE='P4A23'; END IF;
  FOREACH v_id IN ARRAY p_recipient_ids LOOP
    IF NOT EXISTS(SELECT 1 FROM public.students WHERE id=v_id AND classroom_id=p_classroom_id AND transferred_at IS NULL AND role='STUDENT') THEN
      RAISE EXCEPTION '[F4A] invalid recipient student_id=%',v_id USING ERRCODE='P4A24';
    END IF;
    INSERT INTO public.mail_messages(message_uid,classroom_id,recipient_id,sender_type,sender_user_id,title,body,message_type)
    VALUES('F4MAIL_'||extract(epoch from clock_timestamp())::bigint||'_'||v_id||'_'||substr(md5(random()::text),1,5),
      p_classroom_id,v_id,'TEACHER',auth.uid(),v_title,v_body,p_message_type);
    v_count:=v_count+1;
  END LOOP;
  RETURN v_count;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_broadcast_alert(
  p_classroom_id integer, p_message text, p_emoji varchar DEFAULT '📢', p_expires_in_hours integer DEFAULT 48
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_id bigint; v_message text;
BEGIN
  PERFORM public.ensure_teacher_role();
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] teacher classroom denied' USING ERRCODE='P4A20'; END IF;
  v_message:=btrim(coalesce(p_message,''));
  IF char_length(v_message)<1 OR char_length(v_message)>1000 THEN RAISE EXCEPTION '[F4A] alert must be 1-1000 chars' USING ERRCODE='P4A25'; END IF;
  IF p_expires_in_hours<1 OR p_expires_in_hours>168 THEN RAISE EXCEPTION '[F4A] expiry must be 1-168 hours' USING ERRCODE='P4A26'; END IF;
  INSERT INTO public.global_alerts(alert_uid,classroom_id,category,message,emoji,status,expires_at)
  VALUES('F4ALERT_'||extract(epoch from clock_timestamp())::bigint||'_'||substr(md5(random()::text),1,5),
    p_classroom_id,'GENERAL',v_message,left(coalesce(p_emoji,'📢'),10),'ACTIVE',now()+make_interval(hours=>p_expires_in_hours))
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;

-- 기존 내부 통신 헬퍼는 상위 SECURITY DEFINER 함수에서만 사용한다.
REVOKE ALL ON FUNCTION public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint) TO service_role;
REVOKE ALL ON FUNCTION public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer) TO service_role;
REVOKE ALL ON FUNCTION public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility) TO service_role;

-- ACL: Feature4A 외부 RPC만 authenticated에 공개 (정확한 시그니처만 허용)
REVOKE ALL ON FUNCTION public.mark_mail_read(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_mail_read(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.mark_global_alert_read(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_global_alert_read(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.mark_all_global_alerts_read(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_all_global_alerts_read(integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_broadcast_alert(integer,text,character varying,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_broadcast_alert(integer,text,character varying,integer) TO authenticated,service_role;
REVOKE ALL ON TABLE public.global_alert_reads FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.global_alert_reads FROM authenticated;
GRANT SELECT ON TABLE public.global_alert_reads TO authenticated;
GRANT ALL ON TABLE public.global_alert_reads TO service_role;

DO $$ DECLARE t text; BEGIN
  IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['mail_messages','global_alerts','activity_feed_items','global_alert_reads'] LOOP
      IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
      END IF;
    END LOOP;
  END IF;
END $$;

DO $$ BEGIN RAISE NOTICE '[F4A] installed successfully'; END $$;
COMMIT;

-- =========================== F4A END ===========================

-- ========================== F4B START ==========================
-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4B: 학급 운영 (비상사태 · 경비대 · 돌발 퀘스트)
-- Fault domain: F4B / SQLSTATE P4Bxx
-- ============================================================================
BEGIN;
DO $$ BEGIN
  RAISE NOTICE '[F4B] preflight: operations';
  IF to_regclass('public.emergencies') IS NULL OR to_regclass('public.guard_terms') IS NULL THEN
    RAISE EXCEPTION '[F4B] required operations tables missing' USING ERRCODE='P4B01'; END IF;
  IF to_regprocedure('public.create_transaction(integer,public.value_token_type,bigint,public.transaction_source_type,bigint,bigint,text)') IS NULL
     OR to_regprocedure('public.ensure_teacher_role()') IS NULL
     OR to_regprocedure('public.ensure_self_or_teacher(integer)') IS NULL
     OR to_regprocedure('public.is_classroom_member(integer)') IS NULL
     OR to_regprocedure('public.current_student_id()') IS NULL THEN
    RAISE EXCEPTION '[F4B] Feature1/2 transaction or identity core missing' USING ERRCODE='P4B02'; END IF;
  IF to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)') IS NULL
     OR to_regprocedure('public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer)') IS NULL
     OR to_regprocedure('public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility)') IS NULL THEN
    RAISE EXCEPTION '[F4B] Feature4A communication helpers missing or mismatched' USING ERRCODE='P4B03'; END IF;
END $$;

-- 기존 비상사태 RPC를 교사 검증 포함 버전으로 하드닝
CREATE OR REPLACE FUNCTION public.activate_emergency(
 p_classroom_id integer,p_emergency_type public.emergency_type,p_reason text,
 p_scheduled_end_at timestamptz DEFAULT NULL,p_auto_termination jsonb DEFAULT NULL,p_teacher_user_id uuid DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id integer; BEGIN
  PERFORM public.ensure_teacher_role();
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
  IF EXISTS(SELECT 1 FROM public.emergencies WHERE classroom_id=p_classroom_id AND emergency_type=p_emergency_type AND status='ACTIVE') THEN
    RAISE EXCEPTION '[F4B] same emergency type already active' USING ERRCODE='P4B11'; END IF;
  IF char_length(coalesce(p_reason,''))>5000 THEN RAISE EXCEPTION '[F4B] emergency reason too long' USING ERRCODE='P4B15'; END IF;
  IF p_scheduled_end_at IS NOT NULL AND p_scheduled_end_at<=now() THEN RAISE EXCEPTION '[F4B] scheduled end must be future' USING ERRCODE='P4B12'; END IF;
  INSERT INTO public.emergencies(classroom_id,emergency_type,reason,scheduled_end_at,auto_termination_condition,started_by)
  VALUES(p_classroom_id,p_emergency_type,nullif(btrim(coalesce(p_reason,'')),''),p_scheduled_end_at,p_auto_termination,auth.uid()) RETURNING id INTO v_id;
  PERFORM public.broadcast_global_alert(p_classroom_id,'EMERGENCY',format('⚠️ 비상사태 발동: %s',p_emergency_type),'⚠️',NULL,'EMERGENCY',v_id,72);
  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.terminate_emergency(p_emergency_id integer,p_is_auto boolean DEFAULT false,p_teacher_user_id uuid DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v public.emergencies%ROWTYPE; BEGIN
  -- 외부 RPC는 p_is_auto 값과 무관하게 반드시 교사만 호출할 수 있다.
  -- 자동 종료는 아래 service_role 전용 process_expired_emergencies()가 담당한다.
  PERFORM public.ensure_teacher_role();
  SELECT * INTO v FROM public.emergencies WHERE id=p_emergency_id FOR UPDATE;
  IF v.id IS NULL OR v.status<>'ACTIVE' THEN RAISE EXCEPTION '[F4B] emergency not active' USING ERRCODE='P4B13'; END IF;
  IF NOT public.is_classroom_member(v.classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
  -- p_is_auto는 구버전 호출 호환용으로만 유지한다. 외부 교사 종료는 항상 MANUAL_TERMINATED.
  UPDATE public.emergencies SET status='MANUAL_TERMINATED'::public.emergency_status,
    actual_end_at=now(),ended_by=auth.uid() WHERE id=p_emergency_id;
  PERFORM public.broadcast_global_alert(v.classroom_id,'EMERGENCY',format('✅ 비상사태 해제: %s',v.emergency_type),'✅',NULL,'EMERGENCY',p_emergency_id,24);
END $$;

-- 만료된 비상사태 자동 종료용 내부 함수. 브라우저에서는 실행할 수 없다.
CREATE OR REPLACE FUNCTION public.process_expired_emergencies()
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE e record; v_count integer:=0;
BEGIN
  FOR e IN
    SELECT id,classroom_id,emergency_type
      FROM public.emergencies
     WHERE status='ACTIVE' AND scheduled_end_at IS NOT NULL AND scheduled_end_at<=now()
     ORDER BY id
     FOR UPDATE SKIP LOCKED
  LOOP
    UPDATE public.emergencies
       SET status='AUTO_TERMINATED',actual_end_at=now(),ended_by=NULL
     WHERE id=e.id AND status='ACTIVE';
    IF FOUND THEN
      v_count:=v_count+1;
      PERFORM public.broadcast_global_alert(e.classroom_id,'EMERGENCY',format('✅ 비상사태 자동 해제: %s',e.emergency_type),'✅',NULL,'EMERGENCY',e.id,24);
    END IF;
  END LOOP;
  RETURN v_count;
END $$;
REVOKE ALL ON FUNCTION public.process_expired_emergencies() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.process_expired_emergencies() TO service_role;

-- 로그인한 학급 구성원이 자기 학급의 '이미 만료된' 비상사태만 정리할 수 있는 안전한 외부 래퍼.
-- pg_cron이 잠시 멈춰도 학생/교사 대시보드 진입 시 상태가 스스로 정합화된다.
CREATE OR REPLACE FUNCTION public.finalize_expired_emergencies_for_classroom(p_classroom_id integer)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE e record; v_count integer:=0;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_classroom_member(p_classroom_id) THEN
    RAISE EXCEPTION '[F4B] classroom membership required' USING ERRCODE='P4B14';
  END IF;
  FOR e IN
    SELECT id,emergency_type FROM public.emergencies
     WHERE classroom_id=p_classroom_id AND status='ACTIVE'
       AND scheduled_end_at IS NOT NULL AND scheduled_end_at<=now()
     ORDER BY id FOR UPDATE SKIP LOCKED
  LOOP
    UPDATE public.emergencies SET status='AUTO_TERMINATED',actual_end_at=now(),ended_by=NULL
     WHERE id=e.id AND status='ACTIVE';
    IF FOUND THEN
      v_count:=v_count+1;
      PERFORM public.broadcast_global_alert(p_classroom_id,'EMERGENCY',format('✅ 비상사태 자동 해제: %s',e.emergency_type),'✅',NULL,'EMERGENCY',e.id,24);
    END IF;
  END LOOP;
  RETURN v_count;
END $$;

-- pg_cron이 활성화된 환경에서는 1분마다 만료 상태를 정리한다.
-- cron 권한/확장이 없더라도 Feature4 전체 설치를 실패시키지 않고 NOTICE만 남긴다.
DO $$
BEGIN
  IF EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_cron') THEN
    IF NOT EXISTS(SELECT 1 FROM cron.job WHERE jobname='brand_feature4_expired_emergencies') THEN
      PERFORM cron.schedule('brand_feature4_expired_emergencies','* * * * *','SELECT public.process_expired_emergencies();');
    END IF;
  ELSE
    RAISE NOTICE '[F4B] pg_cron not enabled; expired emergency auto-close job skipped';
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE '[F4B] pg_cron scheduling skipped: %',SQLERRM;
END $$;

CREATE TABLE IF NOT EXISTS public.emergency_quests(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 title varchar(120) NOT NULL,
 description text NOT NULL,
 reward_gold integer NOT NULL DEFAULT 0 CHECK(reward_gold BETWEEN 0 AND 10000),
 reward_bv integer NOT NULL DEFAULT 0 CHECK(reward_bv BETWEEN 0 AND 10000),
 starts_at timestamptz NOT NULL DEFAULT now(),
 expires_at timestamptz NOT NULL,
 status varchar(12) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','CLOSED')),
 created_by uuid,
 closed_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(expires_at>starts_at)
);
CREATE TABLE IF NOT EXISTS public.emergency_quest_completions(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 quest_id bigint NOT NULL REFERENCES public.emergency_quests(id) ON DELETE CASCADE,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 student_id integer NOT NULL REFERENCES public.students(id),
 gold_transaction_id bigint REFERENCES public.transactions(id),
 bv_transaction_id bigint REFERENCES public.transactions(id),
 completed_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(quest_id,student_id)
);
CREATE INDEX IF NOT EXISTS idx_emergency_quests_active ON public.emergency_quests(classroom_id,expires_at) WHERE status='ACTIVE';
CREATE INDEX IF NOT EXISTS idx_emergency_quest_completion_student ON public.emergency_quest_completions(student_id,completed_at DESC);
ALTER TABLE public.emergency_quests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emergency_quest_completions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='emergency_quests' AND policyname='emergency_quests_select_class') THEN
  CREATE POLICY emergency_quests_select_class ON public.emergency_quests FOR SELECT TO authenticated USING(public.is_classroom_member(classroom_id)); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='emergency_quest_completions' AND policyname='emergency_quest_completions_select') THEN
  CREATE POLICY emergency_quest_completions_select ON public.emergency_quest_completions FOR SELECT TO authenticated
   USING(student_id=public.current_student_id() OR public.is_teacher_or_admin()); END IF;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_create_emergency_quest(
 p_classroom_id integer,p_title text,p_description text,p_reward_gold integer,p_reward_bv integer,p_duration_minutes integer
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id bigint; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
 IF char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 120 THEN RAISE EXCEPTION '[F4B] quest title invalid' USING ERRCODE='P4B20'; END IF;
 IF char_length(btrim(coalesce(p_description,''))) NOT BETWEEN 1 AND 2000 THEN RAISE EXCEPTION '[F4B] quest description invalid' USING ERRCODE='P4B21'; END IF;
 IF p_reward_gold NOT BETWEEN 0 AND 10000 OR p_reward_bv NOT BETWEEN 0 AND 10000 OR (p_reward_gold=0 AND p_reward_bv=0) THEN RAISE EXCEPTION '[F4B] quest reward invalid' USING ERRCODE='P4B22'; END IF;
 IF p_duration_minutes NOT BETWEEN 1 AND 1440 THEN RAISE EXCEPTION '[F4B] quest duration invalid' USING ERRCODE='P4B23'; END IF;
 INSERT INTO public.emergency_quests(classroom_id,title,description,reward_gold,reward_bv,expires_at,created_by)
 VALUES(p_classroom_id,btrim(p_title),btrim(p_description),p_reward_gold,p_reward_bv,now()+make_interval(mins=>p_duration_minutes),auth.uid()) RETURNING id INTO v_id;
 PERFORM public.broadcast_global_alert(p_classroom_id,'GENERAL',format('⚡ 돌발 퀘스트: %s',btrim(p_title)),'⚡',NULL,'EMERGENCY_QUEST',v_id,least(24,ceil(p_duration_minutes/60.0)::int+1));
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_close_emergency_quest(p_quest_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_classroom integer; BEGIN
 PERFORM public.ensure_teacher_role();
 SELECT classroom_id INTO v_classroom FROM public.emergency_quests WHERE id=p_quest_id FOR UPDATE;
 IF v_classroom IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
 IF NOT public.is_classroom_member(v_classroom) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
 UPDATE public.emergency_quests SET status='CLOSED',closed_at=now() WHERE id=p_quest_id AND status='ACTIVE';
END $$;

CREATE OR REPLACE FUNCTION public.complete_emergency_quest(p_student_id integer,p_quest_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE q public.emergency_quests%ROWTYPE; v_class integer; v_completion bigint; v_gold bigint; v_bv bigint;
BEGIN
 PERFORM public.ensure_self_or_teacher(p_student_id);
 SELECT classroom_id INTO v_class FROM public.students WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4B] active student not found' USING ERRCODE='P4B25'; END IF;
 SELECT * INTO q FROM public.emergency_quests WHERE id=p_quest_id FOR UPDATE;
 IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
 IF q.classroom_id<>v_class THEN RAISE EXCEPTION '[F4B] quest belongs to another classroom' USING ERRCODE='P4B26'; END IF;
 IF q.status<>'ACTIVE' OR now()<q.starts_at OR now()>=q.expires_at THEN RAISE EXCEPTION '[F4B] quest is not completable' USING ERRCODE='P4B27'; END IF;
 INSERT INTO public.emergency_quest_completions(quest_id,classroom_id,student_id) VALUES(q.id,v_class,p_student_id)
 RETURNING id INTO v_completion;
 IF q.reward_gold>0 THEN v_gold:=public.create_transaction(p_student_id,'GOLD',q.reward_gold,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트] %s',q.title)); END IF;
 IF q.reward_bv>0 THEN v_bv:=public.create_transaction(p_student_id,'BV',q.reward_bv,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트 명예] %s',q.title)); END IF;
 UPDATE public.emergency_quest_completions SET gold_transaction_id=v_gold,bv_transaction_id=v_bv WHERE id=v_completion;
 PERFORM public.send_mail(p_student_id,'SYSTEM',NULL,NULL,'⚡ 돌발 퀘스트 완료',format('"%s" 완료 보상이 지급되었습니다.',q.title),'REWARD','DAILY_QUEST',v_completion);
 PERFORM public.push_activity_feed(v_class,'OTHER',p_student_id,jsonb_build_object('message','돌발 퀘스트 완료','quest_title',q.title),'PUBLIC');
 RETURN v_completion;
EXCEPTION WHEN unique_violation THEN
 RAISE EXCEPTION '[F4B] quest already completed' USING ERRCODE='P4B28';
END $$;

CREATE OR REPLACE FUNCTION public.teacher_appoint_guard(
 p_classroom_id integer,p_student_id integer,p_role_type public.guard_role_type,p_start_date date,p_end_date date,p_note text DEFAULT NULL
) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id integer; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
 IF p_start_date>p_end_date THEN RAISE EXCEPTION '[F4B] guard period invalid' USING ERRCODE='P4B30'; END IF;
 IF char_length(coalesce(p_note,''))>500 THEN RAISE EXCEPTION '[F4B] guard note too long' USING ERRCODE='P4B34'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.students WHERE id=p_student_id AND classroom_id=p_classroom_id AND transferred_at IS NULL AND role='STUDENT') THEN RAISE EXCEPTION '[F4B] guard student invalid' USING ERRCODE='P4B31'; END IF;
 IF EXISTS(SELECT 1 FROM public.guard_terms WHERE student_id=p_student_id AND is_active AND daterange(start_date,end_date,'[]') && daterange(p_start_date,p_end_date,'[]')) THEN
  RAISE EXCEPTION '[F4B] overlapping guard term exists' USING ERRCODE='P4B32'; END IF;
 INSERT INTO public.guard_terms(classroom_id,student_id,role_type,start_date,end_date,is_active,appointed_by,note)
 VALUES(p_classroom_id,p_student_id,p_role_type,p_start_date,p_end_date,true,auth.uid(),nullif(btrim(coalesce(p_note,'')),'')) RETURNING id INTO v_id;
 PERFORM public.send_mail(p_student_id,'TEACHER',NULL,auth.uid(),'🛡️ 경제수호대 임명',format('%s부터 %s까지 경제수호대 %s으로 임명되었습니다.',p_start_date,p_end_date,CASE WHEN p_role_type='CHIEF' THEN '대장' ELSE '대원' END),'TEACHER_MESSAGE',NULL,NULL);
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_end_guard_term(p_term_id integer,p_end_date date DEFAULT CURRENT_DATE)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE g public.guard_terms%ROWTYPE; BEGIN
 PERFORM public.ensure_teacher_role(); SELECT * INTO g FROM public.guard_terms WHERE id=p_term_id FOR UPDATE;
 IF g.id IS NULL THEN RAISE EXCEPTION '[F4B] guard term not found' USING ERRCODE='P4B33'; END IF;
 IF NOT public.is_classroom_member(g.classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
 UPDATE public.guard_terms SET end_date=greatest(start_date,p_end_date),is_active=false WHERE id=p_term_id;
 PERFORM public.send_mail(g.student_id,'TEACHER',NULL,auth.uid(),'🛡️ 경제수호대 임기 종료',format('경제수호대 임기가 %s에 종료되었습니다.',greatest(g.start_date,p_end_date)),'TEACHER_MESSAGE',NULL,NULL);
END $$;

-- ACL: 정확한 외부 RPC 시그니처만 authenticated에 공개
REVOKE ALL ON FUNCTION public.activate_emergency(integer,public.emergency_type,text,timestamptz,jsonb,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.activate_emergency(integer,public.emergency_type,text,timestamptz,jsonb,uuid) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.terminate_emergency(integer,boolean,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.terminate_emergency(integer,boolean,uuid) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.finalize_expired_emergencies_for_classroom(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.finalize_expired_emergencies_for_classroom(integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_create_emergency_quest(integer,text,text,integer,integer,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_create_emergency_quest(integer,text,text,integer,integer,integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_close_emergency_quest(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_close_emergency_quest(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.complete_emergency_quest(integer,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.complete_emergency_quest(integer,bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_appoint_guard(integer,integer,public.guard_role_type,date,date,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_appoint_guard(integer,integer,public.guard_role_type,date,date,text) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_end_guard_term(integer,date) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_end_guard_term(integer,date) TO authenticated,service_role;
REVOKE ALL ON TABLE public.emergency_quests,public.emergency_quest_completions FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.emergency_quests,public.emergency_quest_completions FROM authenticated;
GRANT SELECT ON TABLE public.emergency_quests,public.emergency_quest_completions TO authenticated;
GRANT ALL ON TABLE public.emergency_quests,public.emergency_quest_completions TO service_role;
DO $$ DECLARE t text; BEGIN IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
 FOREACH t IN ARRAY ARRAY['emergencies','guard_terms','emergency_quests','emergency_quest_completions'] LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t); END IF;
 END LOOP; END IF; END $$;
DO $$ BEGIN RAISE NOTICE '[F4B] installed successfully'; END $$;
COMMIT;

-- =========================== F4B END ===========================

-- ========================== F4C START ==========================
-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4C: 출석 · 과제
-- Fault domain: F4C / SQLSTATE P4Cxx
-- ============================================================================
BEGIN;
DO $$ BEGIN
 RAISE NOTICE '[F4C] preflight: attendance + assignments';
 IF to_regclass('public.attendances') IS NULL OR to_regclass('public.assignments') IS NULL OR to_regclass('public.assignment_submissions') IS NULL OR to_regclass('public.assignment_gradings') IS NULL THEN
  RAISE EXCEPTION '[F4C] required learning tables missing' USING ERRCODE='P4C01'; END IF;
 IF to_regprocedure('public.record_attendance(integer,date,public.attendance_status)') IS NULL
    OR to_regprocedure('public.reverse_transaction(bigint,text)') IS NULL
    OR to_regprocedure('public.create_transaction(integer,public.value_token_type,bigint,public.transaction_source_type,bigint,bigint,text)') IS NULL
    OR to_regprocedure('public.ensure_teacher_role()') IS NULL
    OR to_regprocedure('public.ensure_self_or_teacher(integer)') IS NULL
    OR to_regprocedure('public.is_classroom_member(integer)') IS NULL THEN
  RAISE EXCEPTION '[F4C] Feature2 / attendance dependency missing' USING ERRCODE='P4C02'; END IF;
 IF to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)') IS NULL
    OR to_regprocedure('public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility)') IS NULL THEN
  RAISE EXCEPTION '[F4C] Feature4A communication helpers missing or mismatched' USING ERRCODE='P4C03'; END IF;
END $$;

-- 학생 제출: SECURITY DEFINER + 본인 검증으로 create_transaction 내부호출 보장
CREATE OR REPLACE FUNCTION public.submit_assignment(p_student_id integer,p_assignment_id integer,p_content_text text DEFAULT NULL,p_attachment_urls jsonb DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE a public.assignments%ROWTYPE; v_class integer; v_id bigint; v_late boolean; v_tx bigint;
BEGIN
 PERFORM public.ensure_self_or_teacher(p_student_id);
 SELECT * INTO a FROM public.assignments WHERE id=p_assignment_id AND status='PUBLISHED';
 IF a.id IS NULL THEN RAISE EXCEPTION '[F4C] assignment not published' USING ERRCODE='P4C10'; END IF;
 SELECT classroom_id INTO v_class FROM public.students WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
 IF v_class IS NULL OR v_class<>a.classroom_id THEN RAISE EXCEPTION '[F4C] assignment classroom mismatch' USING ERRCODE='P4C11'; END IF;
 IF EXISTS(SELECT 1 FROM public.assignment_submissions WHERE assignment_id=p_assignment_id AND student_id=p_student_id AND status<>'RETURNED') THEN
  RAISE EXCEPTION '[F4C] assignment already submitted' USING ERRCODE='P4C12'; END IF;
 IF char_length(coalesce(p_content_text,''))>5000 THEN RAISE EXCEPTION '[F4C] submission too long' USING ERRCODE='P4C13'; END IF;
 IF p_attachment_urls IS NOT NULL AND jsonb_typeof(p_attachment_urls)<>'array' THEN RAISE EXCEPTION '[F4C] attachments must be a JSON array' USING ERRCODE='P4C14'; END IF;
 IF nullif(btrim(coalesce(p_content_text,'')),'') IS NULL
    AND (p_attachment_urls IS NULL OR jsonb_array_length(p_attachment_urls)=0) THEN
  RAISE EXCEPTION '[F4C] submission content or attachment is required' USING ERRCODE='P4C15'; END IF;
 IF p_attachment_urls IS NOT NULL AND jsonb_array_length(p_attachment_urls)>5 THEN RAISE EXCEPTION '[F4C] at most 5 attachments are allowed' USING ERRCODE='P4C16'; END IF;
 IF p_attachment_urls IS NOT NULL AND EXISTS(
   SELECT 1 FROM jsonb_array_elements(p_attachment_urls) AS u
    WHERE jsonb_typeof(u)<>'string' OR char_length(u #>> '{}')>2000 OR (u #>> '{}') !~ '^https?://'
 ) THEN RAISE EXCEPTION '[F4C] attachment URLs must be http(s) strings up to 2000 chars' USING ERRCODE='P4C17'; END IF;
 v_late:=now()>a.due_at;
 INSERT INTO public.assignment_submissions(assignment_id,classroom_id,student_id,content_text,attachment_urls,is_late)
 VALUES(p_assignment_id,v_class,p_student_id,nullif(btrim(coalesce(p_content_text,'')),''),p_attachment_urls,v_late) RETURNING id INTO v_id;
 IF a.auto_reward_on_submit AND a.base_reward_gold>0
    AND NOT EXISTS(SELECT 1 FROM public.assignment_submissions WHERE assignment_id=p_assignment_id AND student_id=p_student_id AND base_reward_given) THEN
  v_tx:=public.create_transaction(p_student_id,'GOLD',a.base_reward_gold,'ASSIGNMENT_SUBMIT',v_id,0,format('[과제 제출] %s',a.title));
  UPDATE public.assignment_submissions SET base_reward_given=true,transaction_id_base=v_tx WHERE id=v_id;
 END IF;
 RETURN v_id;
END $$;

-- 교사 채점: 교사·학급 검증 + 원자적 보상
CREATE OR REPLACE FUNCTION public.grade_assignment(p_submission_id bigint,p_score integer,p_feedback text DEFAULT NULL,p_teacher_user_id uuid DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE s public.assignment_submissions%ROWTYPE; a public.assignments%ROWTYPE; v_id bigint; v_full boolean; v_tx bigint;
BEGIN
 PERFORM public.ensure_teacher_role();
 SELECT * INTO s FROM public.assignment_submissions WHERE id=p_submission_id FOR UPDATE;
 IF s.id IS NULL THEN RAISE EXCEPTION '[F4C] submission not found' USING ERRCODE='P4C20'; END IF;
 IF NOT public.is_classroom_member(s.classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF s.status='GRADED' OR EXISTS(SELECT 1 FROM public.assignment_gradings WHERE submission_id=p_submission_id AND NOT is_revoked) THEN
  RAISE EXCEPTION '[F4C] submission already graded' USING ERRCODE='P4C22'; END IF;
 SELECT * INTO a FROM public.assignments WHERE id=s.assignment_id;
 IF a.id IS NULL THEN RAISE EXCEPTION '[F4C] assignment not found for submission' USING ERRCODE='P4C24'; END IF;
 IF p_score<0 OR p_score>a.max_score THEN RAISE EXCEPTION '[F4C] score out of range' USING ERRCODE='P4C23'; END IF;
 IF char_length(coalesce(p_feedback,''))>5000 THEN RAISE EXCEPTION '[F4C] feedback too long' USING ERRCODE='P4C25'; END IF;
 v_full:=(p_score=a.max_score);
 INSERT INTO public.assignment_gradings(submission_id,score,is_full_score,feedback,grading_method,graded_by)
 VALUES(p_submission_id,p_score,v_full,nullif(btrim(coalesce(p_feedback,'')),''),'MANUAL',auth.uid()) RETURNING id INTO v_id;
 UPDATE public.assignment_submissions SET status='GRADED' WHERE id=p_submission_id;
 IF v_full AND a.full_score_reward_bv>0 THEN
  v_tx:=public.create_transaction(s.student_id,'BV',a.full_score_reward_bv,'ASSIGNMENT_EXCELLENCE',v_id,0,format('[과제 만점 명예] %s — BV %s',a.title,a.full_score_reward_bv));
  UPDATE public.assignment_gradings SET full_score_bonus_given=true,transaction_id_bonus=v_tx WHERE id=v_id;
  PERFORM public.send_mail(s.student_id,'TEACHER',NULL,auth.uid(),format('🎉 만점 축하! %s',a.title),format('과제 "%s"에서 만점을 받았습니다. BV %s가 추가되었습니다.',a.title,a.full_score_reward_bv),'REWARD','ASSIGNMENT_EXCELLENCE',v_id);
  PERFORM public.push_activity_feed(s.classroom_id,'ASSIGNMENT_GRADE',s.student_id,jsonb_build_object('assignment_title',a.title,'is_full_score',true),'PUBLIC');
 END IF;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_create_assignment(
 p_classroom_id integer,p_title text,p_description text,p_subject text,p_due_at timestamptz,p_max_score integer,p_base_reward_gold integer,p_full_score_reward_bv integer,p_publish_now boolean DEFAULT true
) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id integer; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION '[F4C] assignment title invalid' USING ERRCODE='P4C30'; END IF;
 IF char_length(coalesce(p_description,''))>5000 OR char_length(coalesce(p_subject,''))>50 THEN RAISE EXCEPTION '[F4C] assignment text fields too long' USING ERRCODE='P4C34'; END IF;
 IF p_due_at<=now() THEN RAISE EXCEPTION '[F4C] due date must be future' USING ERRCODE='P4C31'; END IF;
 IF p_max_score NOT BETWEEN 1 AND 1000 OR p_base_reward_gold NOT BETWEEN 0 AND 10000 OR p_full_score_reward_bv NOT BETWEEN 0 AND 10000 THEN RAISE EXCEPTION '[F4C] assignment numeric values invalid' USING ERRCODE='P4C32'; END IF;
 INSERT INTO public.assignments(classroom_id,title,description,subject,published_at,due_at,max_score,base_reward_gold,full_score_reward_bv,auto_reward_on_submit,status,created_by)
 VALUES(p_classroom_id,btrim(p_title),nullif(btrim(coalesce(p_description,'')),''),nullif(btrim(coalesce(p_subject,'')),''),CASE WHEN p_publish_now THEN now() ELSE NULL END,p_due_at,p_max_score,p_base_reward_gold,p_full_score_reward_bv,true,CASE WHEN p_publish_now THEN 'PUBLISHED'::public.assignment_status ELSE 'DRAFT'::public.assignment_status END,auth.uid()) RETURNING id INTO v_id;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_set_assignment_status(p_assignment_id integer,p_status public.assignment_status)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_class integer; BEGIN
 PERFORM public.ensure_teacher_role(); SELECT classroom_id INTO v_class FROM public.assignments WHERE id=p_assignment_id FOR UPDATE;
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4C] assignment not found' USING ERRCODE='P4C33'; END IF;
 IF NOT public.is_classroom_member(v_class) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF p_status='PUBLISHED'::public.assignment_status AND EXISTS(SELECT 1 FROM public.assignments WHERE id=p_assignment_id AND due_at<=now()) THEN
  RAISE EXCEPTION '[F4C] cannot publish an assignment whose due date has passed' USING ERRCODE='P4C35'; END IF;
 UPDATE public.assignments SET status=p_status,published_at=CASE WHEN p_status='PUBLISHED' AND published_at IS NULL THEN now() ELSE published_at END,updated_at=now() WHERE id=p_assignment_id;
END $$;

-- 오늘 출석 일괄 입력: 부분 성공 대신 유효한 입력 전체가 한 트랜잭션으로 처리됨
CREATE OR REPLACE FUNCTION public.teacher_record_attendance_bulk(p_classroom_id integer,p_attendance_date date,p_entries jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE e jsonb; v_student integer; v_status public.attendance_status; v_id bigint; v_recorded jsonb:='[]'::jsonb; v_skipped jsonb:='[]'::jsonb; v_today date:=timezone('Asia/Seoul',now())::date;
BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF p_attendance_date<>v_today THEN RAISE EXCEPTION '[F4C] bulk attendance is limited to today (KST) for safe streak accounting' USING ERRCODE='P4C40'; END IF;
 IF jsonb_typeof(p_entries)<>'array' OR jsonb_array_length(p_entries)<1 OR jsonb_array_length(p_entries)>100 THEN RAISE EXCEPTION '[F4C] attendance entries must contain 1-100 rows' USING ERRCODE='P4C41'; END IF;
 IF (SELECT count(*) FROM jsonb_array_elements(p_entries)) <>
    (SELECT count(DISTINCT (x->>'student_id')) FROM jsonb_array_elements(p_entries) AS x) THEN
  RAISE EXCEPTION '[F4C] duplicate students in attendance entries' USING ERRCODE='P4C47'; END IF;
 FOR e IN SELECT * FROM jsonb_array_elements(p_entries) LOOP
  BEGIN v_student:=(e->>'student_id')::integer; v_status:=(e->>'status')::public.attendance_status;
  EXCEPTION WHEN others THEN RAISE EXCEPTION '[F4C] invalid attendance entry: %',e USING ERRCODE='P4C42'; END;
  IF NOT EXISTS(SELECT 1 FROM public.students WHERE id=v_student AND classroom_id=p_classroom_id AND transferred_at IS NULL AND role='STUDENT') THEN RAISE EXCEPTION '[F4C] invalid attendance student %',v_student USING ERRCODE='P4C43'; END IF;
  IF EXISTS(SELECT 1 FROM public.attendances WHERE student_id=v_student AND attendance_date=p_attendance_date) THEN
    v_skipped:=v_skipped||jsonb_build_array(jsonb_build_object('student_id',v_student,'reason','already_recorded'));
  ELSE
    v_id:=public.record_attendance(v_student,p_attendance_date,v_status);
    v_recorded:=v_recorded||jsonb_build_array(jsonb_build_object('student_id',v_student,'attendance_id',v_id,'status',v_status));
  END IF;
 END LOOP;
 RETURN jsonb_build_object('recorded',v_recorded,'skipped',v_skipped);
END $$;

-- 같은 날만 안전 정정: 기존 보상/오늘 마일스톤을 역분개 후 재기록
CREATE OR REPLACE FUNCTION public.teacher_correct_today_attendance(p_attendance_id bigint,p_new_status public.attendance_status,p_reason text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE a public.attendances%ROWTYPE; m record; v_new bigint; v_reason text; v_today date:=timezone('Asia/Seoul',now())::date;
BEGIN
 PERFORM public.ensure_teacher_role();
 v_reason:=btrim(coalesce(p_reason,'')); IF char_length(v_reason)<2 OR char_length(v_reason)>200 THEN RAISE EXCEPTION '[F4C] correction reason must be 2-200 chars' USING ERRCODE='P4C44'; END IF;
 SELECT * INTO a FROM public.attendances WHERE id=p_attendance_id FOR UPDATE;
 IF a.id IS NULL THEN RAISE EXCEPTION '[F4C] attendance not found' USING ERRCODE='P4C45'; END IF;
 IF NOT public.is_classroom_member(a.classroom_id) THEN RAISE EXCEPTION '[F4C] teacher classroom denied' USING ERRCODE='P4C21'; END IF;
 IF a.attendance_date<>v_today THEN RAISE EXCEPTION '[F4C] only today attendance can be corrected automatically' USING ERRCODE='P4C46'; END IF;
 IF a.status=p_new_status THEN RETURN a.id; END IF;
 IF a.transaction_id IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=a.transaction_id AND NOT is_reversed) THEN PERFORM public.reverse_transaction(a.transaction_id,'출석 정정: '||v_reason); END IF;
 FOR m IN SELECT * FROM public.attendance_milestones WHERE student_id=a.student_id AND achieved_on=v_today FOR UPDATE LOOP
  IF m.transaction_id_gold IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_gold AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_gold,'출석 정정: '||v_reason); END IF;
  IF m.transaction_id_bv IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_bv AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_bv,'출석 정정: '||v_reason); END IF;
  IF m.transaction_id_crystal IS NOT NULL AND EXISTS(SELECT 1 FROM public.transactions WHERE id=m.transaction_id_crystal AND NOT is_reversed) THEN PERFORM public.reverse_transaction(m.transaction_id_crystal,'출석 정정: '||v_reason); END IF;
  DELETE FROM public.attendance_milestones WHERE id=m.id;
 END LOOP;
 DELETE FROM public.attendances WHERE id=a.id;
 v_new:=public.record_attendance(a.student_id,v_today,p_new_status);
 RETURN v_new;
END $$;

-- ACL: 정확한 시그니처만 공개. 같은 이름의 과거 오버로드가 있어도 자동 공개하지 않는다.
REVOKE ALL ON FUNCTION public.submit_assignment(integer,integer,text,jsonb) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.submit_assignment(integer,integer,text,jsonb) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.grade_assignment(bigint,integer,text,uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.grade_assignment(bigint,integer,text,uuid) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_create_assignment(integer,text,text,text,timestamptz,integer,integer,integer,boolean) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_create_assignment(integer,text,text,text,timestamptz,integer,integer,integer,boolean) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_set_assignment_status(integer,public.assignment_status) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_set_assignment_status(integer,public.assignment_status) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_record_attendance_bulk(integer,date,jsonb) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_record_attendance_bulk(integer,date,jsonb) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_correct_today_attendance(bigint,public.attendance_status,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_correct_today_attendance(bigint,public.attendance_status,text) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.record_attendance(integer,date,public.attendance_status) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.record_attendance(integer,date,public.attendance_status) TO authenticated,service_role;
DO $$ DECLARE t text; BEGIN IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
 FOREACH t IN ARRAY ARRAY['assignments','assignment_submissions','assignment_gradings','attendances','attendance_milestones'] LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t); END IF;
 END LOOP; END IF; END $$;
DO $$ BEGIN RAISE NOTICE '[F4C] installed successfully'; END $$;
COMMIT;

-- =========================== F4C END ===========================

-- ========================== F4D START ==========================
-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4D: 기록실 · 랭킹 · 분석 · 진단
-- Fault domain: F4D / SQLSTATE P4Dxx
-- ============================================================================
BEGIN;
DO $$ BEGIN
 RAISE NOTICE '[F4D] preflight: records + analytics';
 IF to_regclass('public.rankings') IS NULL OR to_regclass('public.daily_statistics') IS NULL THEN RAISE EXCEPTION '[F4D] ranking/stat tables missing' USING ERRCODE='P4D01'; END IF;
 IF to_regprocedure('public.calculate_daily_statistics(integer,date)') IS NULL OR to_regprocedure('public.calculate_rankings(integer,date)') IS NULL THEN RAISE EXCEPTION '[F4D] calculation functions missing' USING ERRCODE='P4D02'; END IF;
 IF to_regprocedure('public.ensure_teacher_role()') IS NULL OR to_regprocedure('public.is_classroom_member(integer)') IS NULL OR to_regprocedure('public.current_classroom_id()') IS NULL THEN RAISE EXCEPTION '[F4D] identity helpers missing' USING ERRCODE='P4D03'; END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.hall_of_fame_entries(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 category varchar(40) NOT NULL,
 period_label varchar(60),
 title varchar(160) NOT NULL,
 subtitle text,
 student_id integer REFERENCES public.students(id),
 guild_id integer REFERENCES public.guilds(id),
 rank_position integer,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 status varchar(12) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','ARCHIVED')),
 created_by uuid,
 created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(rank_position IS NULL OR rank_position>0)
);
CREATE INDEX IF NOT EXISTS idx_hof_classroom_recent ON public.hall_of_fame_entries(classroom_id,status,created_at DESC);
ALTER TABLE public.hall_of_fame_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='hall_of_fame_entries' AND policyname='hall_of_fame_select_class') THEN
 CREATE POLICY hall_of_fame_select_class ON public.hall_of_fame_entries FOR SELECT TO authenticated USING(public.is_classroom_member(classroom_id)); END IF; END $$;

CREATE OR REPLACE FUNCTION public.teacher_refresh_classroom_records(p_classroom_id integer,p_stat_date date DEFAULT CURRENT_DATE)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_stat integer; v_rank integer; BEGIN
 PERFORM public.ensure_teacher_role();
 IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 IF p_stat_date>(timezone('Asia/Seoul',now()))::date THEN RAISE EXCEPTION '[F4D] future statistics date not allowed' USING ERRCODE='P4D11'; END IF;
 v_stat:=public.calculate_daily_statistics(p_classroom_id,p_stat_date);
 v_rank:=public.calculate_rankings(p_classroom_id,p_stat_date);
 RETURN jsonb_build_object('statistics_id',v_stat,'ranking_rows_last_statement',v_rank,'stat_date',p_stat_date);
END $$;

CREATE OR REPLACE FUNCTION public.teacher_add_hall_of_fame_entry(
 p_classroom_id integer,p_category text,p_period_label text,p_title text,p_subtitle text DEFAULT NULL,p_student_id integer DEFAULT NULL,p_rank_position integer DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_id bigint; BEGIN
 PERFORM public.ensure_teacher_role(); IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 IF char_length(btrim(coalesce(p_category,''))) NOT BETWEEN 1 AND 40 OR char_length(btrim(coalesce(p_title,''))) NOT BETWEEN 1 AND 160 THEN RAISE EXCEPTION '[F4D] record category/title invalid' USING ERRCODE='P4D20'; END IF;
 IF p_student_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.students WHERE id=p_student_id AND classroom_id=p_classroom_id) THEN RAISE EXCEPTION '[F4D] record student mismatch' USING ERRCODE='P4D21'; END IF;
 INSERT INTO public.hall_of_fame_entries(classroom_id,category,period_label,title,subtitle,student_id,rank_position,created_by)
 VALUES(p_classroom_id,btrim(p_category),nullif(btrim(coalesce(p_period_label,'')),''),btrim(p_title),nullif(btrim(coalesce(p_subtitle,'')),''),p_student_id,p_rank_position,auth.uid()) RETURNING id INTO v_id;
 RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_archive_hall_of_fame_entry(p_entry_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$ DECLARE v_class integer; BEGIN
 PERFORM public.ensure_teacher_role(); SELECT classroom_id INTO v_class FROM public.hall_of_fame_entries WHERE id=p_entry_id FOR UPDATE;
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4D] record entry not found' USING ERRCODE='P4D22'; END IF;
 IF NOT public.is_classroom_member(v_class) THEN RAISE EXCEPTION '[F4D] teacher classroom denied' USING ERRCODE='P4D10'; END IF;
 UPDATE public.hall_of_fame_entries SET status='ARCHIVED' WHERE id=p_entry_id;
END $$;

-- Feature4 전체 설치 상태를 한 번에 진단. 오류 위치를 A/B/C/D로 분리해 반환.
CREATE OR REPLACE FUNCTION public.teacher_feature4_health_check()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE v_class integer; BEGIN
 PERFORM public.ensure_teacher_role(); v_class:=public.current_classroom_id();
 IF v_class IS NULL THEN RAISE EXCEPTION '[F4D] current classroom unavailable' USING ERRCODE='P4D30'; END IF;
 RETURN jsonb_build_object(
  'classroom_id',v_class,'checked_at',now(),
  'F4A',jsonb_build_object(
    'global_alert_reads',to_regclass('public.global_alert_reads') IS NOT NULL,
    'teacher_send_mail',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_send_mail'),
    'mark_global_alert_read',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='mark_global_alert_read'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type)'),'EXECUTE'),
    'mail_helper_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)'),'EXECUTE'),
    'mail_count',(SELECT count(*) FROM public.mail_messages WHERE classroom_id=v_class),
    'alert_count',(SELECT count(*) FROM public.global_alerts WHERE classroom_id=v_class)),
  'F4B',jsonb_build_object(
    'emergency_quests',to_regclass('public.emergency_quests') IS NOT NULL,
    'complete_quest',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='complete_emergency_quest'),
    'expiry_processor',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='process_expired_emergencies'),
    'expiry_classroom_rpc',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='finalize_expired_emergencies_for_classroom'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.finalize_expired_emergencies_for_classroom(integer)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.finalize_expired_emergencies_for_classroom(integer)'),'EXECUTE'),
    'processor_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.process_expired_emergencies()'),'EXECUTE'),
    'active_emergencies',(SELECT count(*) FROM public.emergencies WHERE classroom_id=v_class AND status='ACTIVE'),
    'active_guards',(SELECT count(*) FROM public.guard_terms WHERE classroom_id=v_class AND is_active)),
  'F4C',jsonb_build_object(
    'attendance_bulk',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_record_attendance_bulk'),
    'assignment_create',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_create_assignment'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.submit_assignment(integer,integer,text,jsonb)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.submit_assignment(integer,integer,text,jsonb)'),'EXECUTE'),
    'today_attendance',(SELECT count(*) FROM public.attendances WHERE classroom_id=v_class AND attendance_date=(timezone('Asia/Seoul',now()))::date),
    'assignments',(SELECT count(*) FROM public.assignments WHERE classroom_id=v_class)),
  'F4D',jsonb_build_object(
    'hall_of_fame',to_regclass('public.hall_of_fame_entries') IS NOT NULL,
    'refresh_records',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_refresh_classroom_records'),
    'external_acl',has_function_privilege('authenticated',to_regprocedure('public.teacher_refresh_classroom_records(integer,date)'),'EXECUTE') AND NOT has_function_privilege('anon',to_regprocedure('public.teacher_refresh_classroom_records(integer,date)'),'EXECUTE'),
    'calculators_internal',NOT has_function_privilege('authenticated',to_regprocedure('public.calculate_daily_statistics(integer,date)'),'EXECUTE') AND NOT has_function_privilege('authenticated',to_regprocedure('public.calculate_rankings(integer,date)'),'EXECUTE'),
    'statistics_rows',(SELECT count(*) FROM public.daily_statistics WHERE classroom_id=v_class),
    'ranking_rows',(SELECT count(*) FROM public.rankings WHERE classroom_id=v_class),
    'hall_rows',(SELECT count(*) FROM public.hall_of_fame_entries WHERE classroom_id=v_class)),
  'realtime',jsonb_build_object(
    'mail_messages',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='mail_messages'),
    'emergencies',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergencies'),
    'attendances',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='attendances'),
    'rankings',EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='rankings'))
 );
END $$;

-- 집계 함수는 직접 브라우저 호출을 막고 교사 wrapper/cron에서만 사용한다.
REVOKE ALL ON FUNCTION public.calculate_daily_statistics(integer,date) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_daily_statistics(integer,date) TO service_role;
REVOKE ALL ON FUNCTION public.calculate_rankings(integer,date) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_rankings(integer,date) TO service_role;

-- ACL: 교사용 외부 RPC의 정확한 시그니처만 authenticated에 공개
REVOKE ALL ON FUNCTION public.teacher_refresh_classroom_records(integer,date) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_refresh_classroom_records(integer,date) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_add_hall_of_fame_entry(integer,text,text,text,text,integer,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_add_hall_of_fame_entry(integer,text,text,text,text,integer,integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_archive_hall_of_fame_entry(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_archive_hall_of_fame_entry(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_feature4_health_check() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_feature4_health_check() TO authenticated,service_role;
REVOKE ALL ON TABLE public.hall_of_fame_entries FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.hall_of_fame_entries FROM authenticated;
GRANT SELECT ON TABLE public.hall_of_fame_entries TO authenticated;
GRANT ALL ON TABLE public.hall_of_fame_entries TO service_role;
DO $$ DECLARE t text; BEGIN IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
 FOREACH t IN ARRAY ARRAY['daily_statistics','rankings','hall_of_fame_entries'] LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t); END IF;
 END LOOP; END IF; END $$;
DO $$ BEGIN RAISE NOTICE '[F4D] installed successfully'; END $$;
COMMIT;

-- 최종 눈으로 확인할 수 있는 단일 결과표
SELECT 'F4A' module,to_regclass('public.global_alert_reads') IS NOT NULL installed
UNION ALL SELECT 'F4B',to_regclass('public.emergency_quests') IS NOT NULL
UNION ALL SELECT 'F4C',EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname='teacher_record_attendance_bulk')
UNION ALL SELECT 'F4D',to_regclass('public.hall_of_fame_entries') IS NOT NULL
ORDER BY module;

-- =========================== F4D END ===========================
