-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4A: 소통 (우편 · 전역 알림 · 활동 피드)
-- Fault domain: F4A / SQLSTATE P4Axx
-- ============================================================================
BEGIN;

DO $$
BEGIN
  RAISE NOTICE '[F4A] preflight: communications';
  IF to_regclass('public.mail_messages') IS NULL OR to_regclass('public.global_alerts') IS NULL
     OR to_regclass('public.activity_feed_items') IS NULL THEN
    RAISE EXCEPTION '[F4A] required communication tables missing' USING ERRCODE = 'P4A01';
  END IF;
  IF to_regprocedure('public.ensure_teacher_role()') IS NULL
     OR to_regprocedure('public.current_student_id()') IS NULL
     OR to_regprocedure('public.current_classroom_id()') IS NULL
     OR to_regprocedure('public.is_classroom_member(integer)') IS NULL
     OR to_regprocedure('public.is_teacher_or_admin()') IS NULL THEN
    RAISE EXCEPTION '[F4A] required identity helpers missing' USING ERRCODE = 'P4A02';
  END IF;
  IF to_regprocedure('public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint)') IS NULL
     OR to_regprocedure('public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer)') IS NULL
     OR to_regprocedure('public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility)') IS NULL THEN
    RAISE EXCEPTION '[F4A] communication helpers have an unexpected signature' USING ERRCODE = 'P4A03';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.global_alert_reads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alert_id bigint NOT NULL REFERENCES public.global_alerts(id) ON DELETE CASCADE,
  student_id integer NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  read_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(alert_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_global_alert_reads_student ON public.global_alert_reads(student_id, read_at DESC);
ALTER TABLE public.global_alert_reads ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='global_alert_reads' AND policyname='global_alert_reads_select_own') THEN
    CREATE POLICY global_alert_reads_select_own ON public.global_alert_reads FOR SELECT TO authenticated
      USING (student_id = public.current_student_id() OR public.is_teacher_or_admin());
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.mark_mail_read(p_message_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  UPDATE public.mail_messages SET is_read=true, read_at=coalesce(read_at, now())
   WHERE id=p_message_id AND recipient_id=v_student_id;
  IF NOT FOUND THEN RAISE EXCEPTION '[F4A] mail not found or not yours' USING ERRCODE='P4A11'; END IF;
END $$;

CREATE OR REPLACE FUNCTION public.mark_global_alert_read(p_alert_id bigint)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer; v_classroom_id integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  SELECT classroom_id INTO v_classroom_id FROM public.global_alerts WHERE id=p_alert_id;
  IF v_classroom_id IS NULL THEN RAISE EXCEPTION '[F4A] alert not found' USING ERRCODE='P4A12'; END IF;
  IF NOT public.is_classroom_member(v_classroom_id) THEN RAISE EXCEPTION '[F4A] alert belongs to another classroom' USING ERRCODE='P4A13'; END IF;
  INSERT INTO public.global_alert_reads(alert_id,student_id) VALUES(p_alert_id,v_student_id)
    ON CONFLICT(alert_id,student_id) DO UPDATE SET read_at=excluded.read_at;
END $$;

CREATE OR REPLACE FUNCTION public.mark_all_global_alerts_read(p_classroom_id integer)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_student_id integer; v_count integer;
BEGIN
  v_student_id := public.current_student_id();
  IF v_student_id IS NULL THEN RAISE EXCEPTION '[F4A] student login required' USING ERRCODE='P4A10'; END IF;
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] classroom access denied' USING ERRCODE='P4A13'; END IF;
  INSERT INTO public.global_alert_reads(alert_id,student_id)
  SELECT a.id,v_student_id FROM public.global_alerts a
   WHERE a.classroom_id=p_classroom_id AND a.status='ACTIVE'
     AND (a.expires_at IS NULL OR a.expires_at>now())
  ON CONFLICT(alert_id,student_id) DO NOTHING;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_send_mail(
  p_classroom_id integer, p_recipient_ids integer[], p_title text, p_body text,
  p_message_type public.mail_message_type DEFAULT 'TEACHER_MESSAGE'::public.mail_message_type
) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_id integer; v_count integer:=0; v_title text; v_body text;
BEGIN
  PERFORM public.ensure_teacher_role();
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] teacher classroom denied' USING ERRCODE='P4A20'; END IF;
  IF p_recipient_ids IS NULL OR cardinality(p_recipient_ids)=0 OR cardinality(p_recipient_ids)>100 THEN
    RAISE EXCEPTION '[F4A] select 1-100 recipients' USING ERRCODE='P4A21';
  END IF;
  IF cardinality(p_recipient_ids) <> (SELECT count(DISTINCT x) FROM unnest(p_recipient_ids) AS x) THEN
    RAISE EXCEPTION '[F4A] duplicate recipients are not allowed' USING ERRCODE='P4A27';
  END IF;
  v_title:=btrim(coalesce(p_title,'')); v_body:=btrim(coalesce(p_body,''));
  IF char_length(v_title)<1 OR char_length(v_title)>200 THEN RAISE EXCEPTION '[F4A] title must be 1-200 chars' USING ERRCODE='P4A22'; END IF;
  IF char_length(v_body)<1 OR char_length(v_body)>5000 THEN RAISE EXCEPTION '[F4A] body must be 1-5000 chars' USING ERRCODE='P4A23'; END IF;
  FOREACH v_id IN ARRAY p_recipient_ids LOOP
    IF NOT EXISTS(SELECT 1 FROM public.students WHERE id=v_id AND classroom_id=p_classroom_id AND transferred_at IS NULL AND role='STUDENT') THEN
      RAISE EXCEPTION '[F4A] invalid recipient student_id=%',v_id USING ERRCODE='P4A24';
    END IF;
    INSERT INTO public.mail_messages(message_uid,classroom_id,recipient_id,sender_type,sender_user_id,title,body,message_type)
    VALUES('F4MAIL_'||extract(epoch from clock_timestamp())::bigint||'_'||v_id||'_'||substr(md5(random()::text),1,5),
      p_classroom_id,v_id,'TEACHER',auth.uid(),v_title,v_body,p_message_type);
    v_count:=v_count+1;
  END LOOP;
  RETURN v_count;
END $$;

CREATE OR REPLACE FUNCTION public.teacher_broadcast_alert(
  p_classroom_id integer, p_message text, p_emoji varchar DEFAULT '📢', p_expires_in_hours integer DEFAULT 48
) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_id bigint; v_message text;
BEGIN
  PERFORM public.ensure_teacher_role();
  IF NOT public.is_classroom_member(p_classroom_id) THEN RAISE EXCEPTION '[F4A] teacher classroom denied' USING ERRCODE='P4A20'; END IF;
  v_message:=btrim(coalesce(p_message,''));
  IF char_length(v_message)<1 OR char_length(v_message)>1000 THEN RAISE EXCEPTION '[F4A] alert must be 1-1000 chars' USING ERRCODE='P4A25'; END IF;
  IF p_expires_in_hours<1 OR p_expires_in_hours>168 THEN RAISE EXCEPTION '[F4A] expiry must be 1-168 hours' USING ERRCODE='P4A26'; END IF;
  INSERT INTO public.global_alerts(alert_uid,classroom_id,category,message,emoji,status,expires_at)
  VALUES('F4ALERT_'||extract(epoch from clock_timestamp())::bigint||'_'||substr(md5(random()::text),1,5),
    p_classroom_id,'GENERAL',v_message,left(coalesce(p_emoji,'📢'),10),'ACTIVE',now()+make_interval(hours=>p_expires_in_hours))
  RETURNING id INTO v_id;
  RETURN v_id;
END $$;

-- 기존 내부 통신 헬퍼는 상위 SECURITY DEFINER 함수에서만 사용한다.
REVOKE ALL ON FUNCTION public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.send_mail(integer,public.mail_sender_type,integer,uuid,character varying,text,public.mail_message_type,public.transaction_source_type,bigint) TO service_role;
REVOKE ALL ON FUNCTION public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.broadcast_global_alert(integer,public.global_alert_category,text,character varying,integer,character varying,bigint,integer) TO service_role;
REVOKE ALL ON FUNCTION public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.push_activity_feed(integer,public.activity_feed_type,integer,jsonb,public.activity_visibility) TO service_role;

-- ACL: Feature4A 외부 RPC만 authenticated에 공개 (정확한 시그니처만 허용)
REVOKE ALL ON FUNCTION public.mark_mail_read(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_mail_read(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.mark_global_alert_read(bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_global_alert_read(bigint) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.mark_all_global_alerts_read(integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.mark_all_global_alerts_read(integer) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_send_mail(integer,integer[],text,text,public.mail_message_type) TO authenticated,service_role;
REVOKE ALL ON FUNCTION public.teacher_broadcast_alert(integer,text,character varying,integer) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_broadcast_alert(integer,text,character varying,integer) TO authenticated,service_role;
REVOKE ALL ON TABLE public.global_alert_reads FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.global_alert_reads FROM authenticated;
GRANT SELECT ON TABLE public.global_alert_reads TO authenticated;
GRANT ALL ON TABLE public.global_alert_reads TO service_role;

DO $$ DECLARE t text; BEGIN
  IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['mail_messages','global_alerts','activity_feed_items','global_alert_reads'] LOOP
      IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
      END IF;
    END LOOP;
  END IF;
END $$;

DO $$ BEGIN RAISE NOTICE '[F4A] installed successfully'; END $$;
COMMIT;
