-- ============================================================================
-- B.R.A.N.D 2.0 — Feature 4.1.1 UI / Realtime / 운영 안정화 Hotfix
-- 2026-08-08
--
-- 목적
-- 1) Feature 4.1 완료요청 테이블을 다시 보장하고 PostgREST schema cache 갱신
-- 2) 완료요청/과제 Realtime publication 보강
-- 3) 교사 BV + GOLD 동시 지급을 단일 DB 트랜잭션으로 제공
-- ============================================================================
BEGIN;

-- --------------------------------------------------------------------------
-- F4B. 완료요청 테이블 / ACL 재보장
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.emergency_quest_requests(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 quest_id bigint NOT NULL REFERENCES public.emergency_quests(id) ON DELETE CASCADE,
 classroom_id integer NOT NULL REFERENCES public.classrooms(id),
 student_id integer NOT NULL REFERENCES public.students(id),
 status varchar(12) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED')),
 note text,
 requested_at timestamptz NOT NULL DEFAULT now(),
 reviewed_at timestamptz,
 reviewed_by uuid,
 UNIQUE(quest_id,student_id)
);
CREATE INDEX IF NOT EXISTS idx_emergency_quest_requests_pending
 ON public.emergency_quest_requests(classroom_id,status,requested_at);
ALTER TABLE public.emergency_quest_requests ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
 IF NOT EXISTS(
   SELECT 1 FROM pg_policies
   WHERE schemaname='public'
     AND tablename='emergency_quest_requests'
     AND policyname='emergency_quest_requests_select'
 ) THEN
  CREATE POLICY emergency_quest_requests_select
   ON public.emergency_quest_requests
   FOR SELECT TO authenticated
   USING(student_id=public.current_student_id() OR public.is_teacher_or_admin());
 END IF;
END $$;
REVOKE ALL ON TABLE public.emergency_quest_requests FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER
 ON TABLE public.emergency_quest_requests FROM authenticated;
GRANT SELECT ON TABLE public.emergency_quest_requests TO authenticated;
GRANT ALL ON TABLE public.emergency_quest_requests TO service_role;

-- 완료요청 RPC가 없는 상태라면 4.1 migration이 적용되지 않은 것이므로 조용히 잘못 동작하지 않게 명확히 실패시킨다.
DO $$
BEGIN
 IF to_regprocedure('public.request_emergency_quest_completion(integer,bigint)') IS NULL
    OR to_regprocedure('public.teacher_review_emergency_quest_request(bigint,boolean,text)') IS NULL THEN
  RAISE EXCEPTION '[F4.1.1] Feature 4.1 DB 함수가 없습니다. 20260808_01_feature4_1_stabilization.sql을 먼저 적용한 뒤 이 migration을 다시 실행하세요.';
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- Feature 1 보강. BV + GOLD 동시 지급
-- 반드시 하나의 SECURITY DEFINER 함수/트랜잭션 안에서 처리한다.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_grant_student_assets_combined(
  p_student_ids integer[],
  p_bv_amount bigint,
  p_gold_amount bigint,
  p_reason text
)
RETURNS TABLE(
  student_id integer,
  bv_transaction_id bigint,
  gold_transaction_id bigint,
  new_bv bigint,
  new_gold bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_teacher_classroom_id integer;
  v_requested_count integer;
  v_unique_count integer;
  v_valid_count integer;
  v_student_id integer;
  v_bv_tx bigint;
  v_gold_tx bigint;
  v_new_bv bigint;
  v_new_gold bigint;
  v_reason text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.' USING ERRCODE='P0610';
  END IF;
  PERFORM public.ensure_teacher_role();

  v_requested_count := cardinality(p_student_ids);
  IF p_student_ids IS NULL OR v_requested_count IS NULL OR v_requested_count < 1 THEN
    RAISE EXCEPTION '대상 학생을 한 명 이상 선택해주세요.' USING ERRCODE='P0611';
  END IF;
  IF v_requested_count > 100 THEN
    RAISE EXCEPTION '한 번에 처리할 수 있는 학생은 최대 100명입니다.' USING ERRCODE='P0612';
  END IF;
  IF EXISTS (SELECT 1 FROM unnest(p_student_ids) AS x(id) WHERE x.id IS NULL) THEN
    RAISE EXCEPTION '학생 목록에 잘못된 값이 포함되어 있습니다.' USING ERRCODE='P0613';
  END IF;
  SELECT count(DISTINCT x.id) INTO v_unique_count FROM unnest(p_student_ids) AS x(id);
  IF v_unique_count <> v_requested_count THEN
    RAISE EXCEPTION '같은 학생이 중복 선택되어 있습니다.' USING ERRCODE='P0613';
  END IF;

  IF p_bv_amount IS NULL OR p_gold_amount IS NULL
     OR p_bv_amount < 0 OR p_gold_amount < 0
     OR p_bv_amount > 10000000 OR p_gold_amount > 10000000
     OR (p_bv_amount = 0 AND p_gold_amount = 0) THEN
    RAISE EXCEPTION 'BV/골드는 각각 0~10,000,000 정수이며 둘 중 하나 이상은 1 이상이어야 합니다.' USING ERRCODE='P0614';
  END IF;

  v_reason := btrim(coalesce(p_reason,''));
  IF char_length(v_reason) < 2 OR char_length(v_reason) > 200 THEN
    RAISE EXCEPTION '사유는 2자 이상 200자 이하로 입력해주세요.' USING ERRCODE='P0615';
  END IF;

  SELECT s.classroom_id
    INTO v_teacher_classroom_id
    FROM public.students AS s
   WHERE s.user_id = auth.uid()
     AND s.transferred_at IS NULL
     AND s.role IN ('TEACHER','ADMIN')
   ORDER BY CASE WHEN s.role='TEACHER' THEN 0 ELSE 1 END, s.id
   LIMIT 1;

  IF v_teacher_classroom_id IS NULL THEN
    SELECT c.id INTO v_teacher_classroom_id
      FROM public.classrooms AS c
     WHERE c.teacher_user_id=auth.uid() AND c.is_active=true
     ORDER BY c.id LIMIT 1;
  END IF;
  IF v_teacher_classroom_id IS NULL THEN
    RAISE EXCEPTION '담당 학급을 확인할 수 없습니다.' USING ERRCODE='P0616';
  END IF;

  SELECT count(*) INTO v_valid_count
    FROM public.students AS s
   WHERE s.id = ANY(p_student_ids)
     AND s.classroom_id = v_teacher_classroom_id
     AND s.transferred_at IS NULL
     AND s.role IN ('STUDENT','STUDENT_LEADER','GUARD');
  IF v_valid_count <> v_requested_count THEN
    RAISE EXCEPTION '선택한 학생 중 담당 학급의 활성 학생이 아닌 대상이 있습니다.' USING ERRCODE='P0617';
  END IF;

  FOR v_student_id IN SELECT x.id FROM unnest(p_student_ids) AS x(id) ORDER BY x.id LOOP
    v_bv_tx := NULL;
    v_gold_tx := NULL;

    IF p_bv_amount > 0 THEN
      v_bv_tx := public.create_transaction(
        v_student_id,
        'BV'::public.value_token_type,
        p_bv_amount,
        'TEACHER_GRANT'::public.transaction_source_type,
        NULL,
        0,
        '[교사 BV+골드 동시 지급/BV] ' || v_reason
      );
    END IF;

    IF p_gold_amount > 0 THEN
      v_gold_tx := public.create_transaction(
        v_student_id,
        'GOLD'::public.value_token_type,
        p_gold_amount,
        'TEACHER_GRANT'::public.transaction_source_type,
        NULL,
        0,
        '[교사 BV+골드 동시 지급/GOLD] ' || v_reason
      );
    END IF;

    SELECT w.bv,w.gold INTO v_new_bv,v_new_gold
      FROM public.wallets AS w WHERE w.student_id=v_student_id;

    student_id := v_student_id;
    bv_transaction_id := v_bv_tx;
    gold_transaction_id := v_gold_tx;
    new_bv := v_new_bv;
    new_gold := v_new_gold;
    RETURN NEXT;
  END LOOP;
END;
$$;

COMMENT ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text)
IS '교사 전용 BV+GOLD 동시 지급. 두 자산 지급을 하나의 PostgreSQL 트랜잭션에서 원자적으로 처리한다.';
REVOKE ALL ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text) TO authenticated,service_role;

-- --------------------------------------------------------------------------
-- Realtime publication 보강
-- --------------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
 IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
  FOREACH t IN ARRAY ARRAY['mail_messages','global_alerts','global_alert_reads','emergencies','emergency_quests','emergency_quest_completions','emergency_quest_requests','assignments'] LOOP
   IF to_regclass(format('public.%I',t)) IS NOT NULL
      AND NOT EXISTS(
        SELECT 1 FROM pg_publication_tables
         WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=t
      ) THEN
    EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',t);
   END IF;
  END LOOP;
 END IF;
END $$;

-- --------------------------------------------------------------------------
-- Feature 4.1.1 진단
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.teacher_feature4_1_1_health_check()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=public,pg_temp
AS $$
DECLARE v_base jsonb;
BEGIN
  PERFORM public.ensure_teacher_role();
  v_base := public.teacher_feature4_1_health_check();
  RETURN v_base || jsonb_build_object('F4.1.1', jsonb_build_object(
    'quest_request_table', to_regclass('public.emergency_quest_requests') IS NOT NULL,
    'combined_asset_grant_rpc', to_regprocedure('public.teacher_grant_student_assets_combined(integer[],bigint,bigint,text)') IS NOT NULL,
    'mail_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='mail_messages'),
    'alerts_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='global_alerts'),
    'emergency_quests_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergency_quests'),
    'quest_requests_realtime', EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='emergency_quest_requests'),
    'auction_create_rpc', to_regprocedure('public.teacher_create_live_auction(integer,integer,integer,date,integer,integer)') IS NOT NULL,
    'auction_start_rpc', to_regprocedure('public.teacher_start_live_auction(integer)') IS NOT NULL
  ));
END $$;
REVOKE ALL ON FUNCTION public.teacher_feature4_1_1_health_check() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_feature4_1_1_health_check() TO authenticated,service_role;

-- PostgREST가 방금 생성/교체한 테이블·RPC를 즉시 인식하도록 요청.
NOTIFY pgrst, 'reload schema';

COMMIT;
