-- B.R.A.N.D 2.0 Fragment Expedition E2
-- Core DRY_RUN schema. Incremental on top of E1 profile/specialty baseline.

do $preflight$
begin
  if to_regclass('public.character_element_profiles') is null
     or to_regclass('public.character_expedition_profiles') is null
     or to_regclass('public.expedition_specialties') is null then
    raise exception 'EXPEDITION_E2_REQUIRES_E1_BASELINE' using errcode='P0E20';
  end if;
  if (select count(*) from public.character_element_profiles) <> 79
     or (select count(*) from public.character_expedition_profiles where profile_status='ACTIVE') <> 79 then
    raise exception 'EXPEDITION_E2_E1_COVERAGE_INVALID' using errcode='P0E21';
  end if;
end
$preflight$;

create or replace function public.expedition_set_updated_at()
returns trigger language plpgsql set search_path=public,pg_temp as $function$
begin new.updated_at := now(); return new; end;
$function$;
revoke all on function public.expedition_set_updated_at() from public,anon,authenticated;
grant execute on function public.expedition_set_updated_at() to service_role;

create or replace function public.expedition_reject_history_mutation()
returns trigger language plpgsql set search_path=public,pg_temp as $function$
begin raise exception 'EXPEDITION_HISTORY_IMMUTABLE' using errcode='P0E22'; end;
$function$;
revoke all on function public.expedition_reject_history_mutation() from public,anon,authenticated;
grant execute on function public.expedition_reject_history_mutation() to service_role;

create table public.expedition_settings (
  classroom_id integer primary key references public.classrooms(id) on delete cascade,
  schema_version text not null default 'EXPEDITION_V1_4',
  is_core_enabled boolean not null default false,
  is_student_ui_enabled boolean not null default false,
  is_scheduler_enabled boolean not null default false,
  is_reward_grant_enabled boolean not null default false,
  publish_weekday smallint not null default 5,
  publish_time_kst time not null default time '17:00',
  sat_open_time_kst time not null default time '00:00',
  sun_open_time_kst time not null default time '00:00',
  settle_time_kst time not null default time '00:05',
  world_effect_start_time_kst time not null default time '06:00',
  world_effect_duration_hours smallint not null default 168,
  world_trace_lv1 smallint not null default 12,
  world_trace_lv2 smallint not null default 24,
  world_trace_lv3 smallint not null default 40,
  map_mastery_threshold smallint not null default 24,
  story_trace_faint smallint not null default 1,
  story_trace_discovery smallint not null default 5,
  story_trace_active smallint not null default 10,
  story_trace_breakthrough smallint not null default 18,
  reward_config jsonb not null default '{}'::jsonb,
  world_effect_config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_settings_publish_weekday_chk check (publish_weekday between 1 and 7),
  constraint expedition_settings_world_duration_chk check (world_effect_duration_hours = 168),
  constraint expedition_settings_world_threshold_chk check (world_trace_lv1>0 and world_trace_lv1<world_trace_lv2 and world_trace_lv2<world_trace_lv3),
  constraint expedition_settings_story_threshold_chk check (story_trace_faint>0 and story_trace_faint<story_trace_discovery and story_trace_discovery<story_trace_active and story_trace_active<story_trace_breakthrough)
);
comment on table public.expedition_settings is 'Per-classroom Fragment Expedition config and staged cutover flags. All flags default OFF.';
comment on column public.expedition_settings.world_effect_duration_hours is 'Confirmed fixed world-effect duration: Monday 06:00 KST to next Monday 06:00 KST = 168 hours.';
create trigger expedition_settings_set_updated_at before update on public.expedition_settings for each row execute function public.expedition_set_updated_at();

create table public.expedition_seasons (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  season_code text not null, name_ko text not null, starts_on date not null, ends_on date not null,
  status text not null default 'DRAFT', config_version text not null default 'EXPEDITION_V1_4',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_seasons_code_chk check (btrim(season_code)<>''),
  constraint expedition_seasons_name_chk check (btrim(name_ko)<>''),
  constraint expedition_seasons_dates_chk check (ends_on>=starts_on),
  constraint expedition_seasons_status_chk check (status in ('DRAFT','ACTIVE','CLOSED')),
  unique(classroom_id,season_code)
);
create unique index expedition_seasons_one_active_per_classroom on public.expedition_seasons(classroom_id) where status='ACTIVE';
create trigger expedition_seasons_set_updated_at before update on public.expedition_seasons for each row execute function public.expedition_set_updated_at();

create table public.expedition_sites (
  id bigint generated by default as identity primary key,
  site_code text not null unique, name_ko text not null,
  specialty_code text not null references public.expedition_specialties(specialty_code) on update cascade on delete restrict,
  core_reward_code text not null, world_effect_code text not null,
  sort_order smallint not null unique, is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_sites_code_chk check (btrim(site_code)<>''),
  constraint expedition_sites_name_chk check (btrim(name_ko)<>''),
  constraint expedition_sites_reward_chk check (core_reward_code in ('EXPEDITION_BOX','GOLD','FRAGMENT')),
  constraint expedition_sites_world_effect_chk check (world_effect_code in ('RESTORE','SHOP','SUPPLY','RECORD','COSMETIC')),
  constraint expedition_sites_sort_chk check (sort_order between 1 and 15)
);
create index expedition_sites_specialty_idx on public.expedition_sites(specialty_code,sort_order);
create trigger expedition_sites_set_updated_at before update on public.expedition_sites for each row execute function public.expedition_set_updated_at();

create table public.expedition_environment_templates (
  id bigint generated by default as identity primary key,
  environment_code text not null unique, label_ko text not null,
  major_element text not null, minor_element text not null,
  config_version text not null default 'ENV_V1', sort_order smallint not null unique,
  is_active boolean not null default true, metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_environment_code_chk check (btrim(environment_code)<>''),
  constraint expedition_environment_label_chk check (btrim(label_ko)<>''),
  constraint expedition_environment_major_chk check (major_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_environment_minor_chk check (minor_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_environment_pair_chk check (major_element<>minor_element),
  constraint expedition_environment_sort_chk check (sort_order between 1 and 12)
);
create trigger expedition_environment_templates_set_updated_at before update on public.expedition_environment_templates for each row execute function public.expedition_set_updated_at();

create table public.expedition_weeks (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.expedition_seasons(id) on delete restrict,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  week_index integer not null, week_start_date date not null, generation_no integer not null default 1,
  week_seed text not null, status text not null default 'DRAFT', reward_mode text not null default 'DRY_RUN',
  publish_at timestamptz not null, sat_open_at timestamptz not null, sun_open_at timestamptz not null,
  sun_close_at timestamptz not null, settle_at timestamptz not null,
  fit_formula_version text not null default 'ELEM_70_30_V1',
  config_snapshot jsonb not null default '{}'::jsonb, reward_pool_snapshot jsonb not null default '{}'::jsonb,
  dominant_week_site_id bigint null, world_effect_level smallint null,
  published_at timestamptz null, resolved_at timestamptz null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_weeks_index_chk check (week_index>=1),
  constraint expedition_weeks_generation_chk check (generation_no>=1),
  constraint expedition_weeks_seed_chk check (btrim(week_seed)<>''),
  constraint expedition_weeks_status_chk check (status in ('DRAFT','PUBLISHED','SETTLED','CANCELLED')),
  constraint expedition_weeks_reward_mode_chk check (reward_mode in ('DRY_RUN','LIVE')),
  constraint expedition_weeks_formula_chk check (fit_formula_version='ELEM_70_30_V1'),
  constraint expedition_weeks_window_order_chk check (publish_at<sat_open_at and sat_open_at<sun_open_at and sun_open_at<sun_close_at and sun_close_at<=settle_at),
  constraint expedition_weeks_effect_level_chk check (world_effect_level is null or world_effect_level between 0 and 3),
  unique(classroom_id,week_start_date)
);
create index expedition_weeks_classroom_status_idx on public.expedition_weeks(classroom_id,status,week_start_date desc);
create trigger expedition_weeks_set_updated_at before update on public.expedition_weeks for each row execute function public.expedition_set_updated_at();

create table public.expedition_week_sites (
  id bigint generated by default as identity primary key,
  week_id bigint not null references public.expedition_weeks(id) on delete cascade,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  slot smallint not null, site_id bigint not null references public.expedition_sites(id) on delete restrict,
  site_code_snapshot text not null, site_name_snapshot text not null, specialty_code_snapshot text not null,
  core_reward_code_snapshot text not null, world_effect_code_snapshot text not null,
  environment_template_id bigint not null references public.expedition_environment_templates(id) on delete restrict,
  environment_code_snapshot text not null, environment_label_snapshot text not null, environment_config_version text not null,
  saturday_major_element text not null, saturday_minor_element text not null,
  sunday_major_element text not null, sunday_minor_element text not null,
  sunday_event_title text null, sunday_event_text text null, sunday_event_applied boolean not null default false,
  resolved_saturday_trace integer not null default 0, resolved_saturday_participant_count integer not null default 0,
  resolved_total_trace integer not null default 0, resolved_final_participant_count integer not null default 0,
  final_level smallint null, mastery_advanced boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expedition_week_sites_slot_chk check (slot between 1 and 3),
  constraint expedition_week_sites_specialty_chk check (specialty_code_snapshot in ('RUINS','NATURE','SANCTUARY')),
  constraint expedition_week_sites_reward_chk check (core_reward_code_snapshot in ('EXPEDITION_BOX','GOLD','FRAGMENT')),
  constraint expedition_week_sites_world_effect_chk check (world_effect_code_snapshot in ('RESTORE','SHOP','SUPPLY','RECORD','COSMETIC')),
  constraint expedition_week_sites_sat_major_chk check (saturday_major_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_sites_sat_minor_chk check (saturday_minor_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_sites_sun_major_chk check (sunday_major_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_sites_sun_minor_chk check (sunday_minor_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_sites_sat_pair_chk check (saturday_major_element<>saturday_minor_element),
  constraint expedition_week_sites_sun_pair_chk check (sunday_major_element<>sunday_minor_element),
  constraint expedition_week_sites_level_chk check (final_level is null or final_level between 0 and 3),
  unique(week_id,slot), unique(week_id,site_id)
);
create index expedition_week_sites_classroom_week_idx on public.expedition_week_sites(classroom_id,week_id,slot);
create trigger expedition_week_sites_set_updated_at before update on public.expedition_week_sites for each row execute function public.expedition_set_updated_at();
alter table public.expedition_weeks add constraint expedition_weeks_dominant_week_site_fkey foreign key(dominant_week_site_id) references public.expedition_week_sites(id) on delete set null;

create table public.expedition_week_character_profiles (
  week_id bigint not null references public.expedition_weeks(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete restrict,
  character_uid_snapshot text not null, character_name_snapshot text not null,
  element_budget smallint not null, primary_element text not null, primary_points smallint not null,
  secondary_element text null, secondary_points smallint not null default 0,
  specialty_code text not null, source_element_updated_at timestamptz null, source_expedition_updated_at timestamptz null,
  profile_version text not null, snapshotted_at timestamptz not null default now(),
  primary key(week_id,character_id),
  constraint expedition_week_profile_budget_chk check (element_budget in (8,9,10)),
  constraint expedition_week_profile_primary_chk check (primary_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_profile_secondary_chk check (secondary_element is null or secondary_element in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_week_profile_pair_chk check (secondary_element is null or primary_element<>secondary_element),
  constraint expedition_week_profile_points_chk check (primary_points>0 and secondary_points>=0 and primary_points+secondary_points=element_budget and ((secondary_element is null and secondary_points=0) or (secondary_element is not null and secondary_points>0))),
  constraint expedition_week_profile_specialty_chk check (specialty_code in ('RUINS','NATURE','SANCTUARY'))
);
create index expedition_week_character_profiles_character_idx on public.expedition_week_character_profiles(character_id,week_id);

create table public.expedition_runs (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  student_id integer not null references public.students(id) on delete restrict,
  week_id bigint not null references public.expedition_weeks(id) on delete restrict,
  week_site_id bigint not null references public.expedition_week_sites(id) on delete restrict,
  phase text not null, fit_formula_version text not null default 'ELEM_70_30_V1', fit_percent smallint not null,
  fit_grade text not null, trace_contribution smallint not null, counts_for_world boolean not null,
  client_request_id uuid not null, submitted_at timestamptz not null default now(), created_at timestamptz not null default now(),
  constraint expedition_runs_phase_chk check (phase in ('SAT','SUN')),
  constraint expedition_runs_formula_chk check (fit_formula_version='ELEM_70_30_V1'),
  constraint expedition_runs_fit_chk check (fit_percent between 0 and 130),
  constraint expedition_runs_grade_chk check (fit_grade in ('VULNERABLE','NORMAL','STABLE','STRONG')),
  constraint expedition_runs_trace_chk check (trace_contribution in (1,2,3)),
  unique(student_id,week_id,phase), unique(student_id,client_request_id)
);
create index expedition_runs_week_site_phase_idx on public.expedition_runs(week_id,week_site_id,phase,counts_for_world);
create index expedition_runs_classroom_week_idx on public.expedition_runs(classroom_id,week_id,student_id);

create table public.expedition_run_members (
  run_id bigint not null references public.expedition_runs(id) on delete restrict,
  slot smallint not null, character_id bigint not null references public.characters(id) on delete restrict,
  character_uid_snapshot text not null, character_name_snapshot text not null,
  element_budget_snapshot smallint not null, primary_element_snapshot text not null, primary_points_snapshot smallint not null,
  secondary_element_snapshot text null, secondary_points_snapshot smallint not null default 0,
  specialty_code_snapshot text not null, specialty_matched boolean not null,
  major_points_contribution smallint not null default 0, minor_points_contribution smallint not null default 0,
  created_at timestamptz not null default now(), primary key(run_id,slot), unique(run_id,character_id),
  constraint expedition_run_members_slot_chk check (slot between 1 and 3),
  constraint expedition_run_members_budget_chk check (element_budget_snapshot in (8,9,10)),
  constraint expedition_run_members_primary_chk check (primary_element_snapshot in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_run_members_secondary_chk check (secondary_element_snapshot is null or secondary_element_snapshot in ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')),
  constraint expedition_run_members_points_chk check (primary_points_snapshot>0 and secondary_points_snapshot>=0 and primary_points_snapshot+secondary_points_snapshot=element_budget_snapshot),
  constraint expedition_run_members_specialty_chk check (specialty_code_snapshot in ('RUINS','NATURE','SANCTUARY')),
  constraint expedition_run_members_major_points_chk check (major_points_contribution>=0),
  constraint expedition_run_members_minor_points_chk check (minor_points_contribution>=0)
);
create index expedition_run_members_character_idx on public.expedition_run_members(character_id,run_id);
create trigger expedition_runs_immutable before update or delete on public.expedition_runs for each row execute function public.expedition_reject_history_mutation();
create trigger expedition_run_members_immutable before update or delete on public.expedition_run_members for each row execute function public.expedition_reject_history_mutation();

alter table public.expedition_settings enable row level security;
alter table public.expedition_seasons enable row level security;
alter table public.expedition_sites enable row level security;
alter table public.expedition_environment_templates enable row level security;
alter table public.expedition_weeks enable row level security;
alter table public.expedition_week_sites enable row level security;
alter table public.expedition_week_character_profiles enable row level security;
alter table public.expedition_runs enable row level security;
alter table public.expedition_run_members enable row level security;

revoke all on table public.expedition_settings,public.expedition_seasons,public.expedition_sites,public.expedition_environment_templates,public.expedition_weeks,public.expedition_week_sites,public.expedition_week_character_profiles,public.expedition_runs,public.expedition_run_members from public,anon,authenticated;
grant all on table public.expedition_settings,public.expedition_seasons,public.expedition_sites,public.expedition_environment_templates,public.expedition_weeks,public.expedition_week_sites,public.expedition_week_character_profiles,public.expedition_runs,public.expedition_run_members to service_role;
grant usage,select on all sequences in schema public to service_role;
grant select on table public.expedition_sites,public.expedition_environment_templates to authenticated;
create policy expedition_sites_select_authenticated on public.expedition_sites for select to authenticated using (is_active=true or public.is_teacher_or_admin());
create policy expedition_environment_templates_select_authenticated on public.expedition_environment_templates for select to authenticated using (is_active=true or public.is_teacher_or_admin());

comment on table public.expedition_weeks is 'Immutable published weekly expedition configuration. reward_mode is DRY_RUN for E2.';
comment on table public.expedition_week_character_profiles is 'Publish-time snapshot of all active character element/specialty profiles.';
comment on table public.expedition_runs is 'Append-only student SAT/SUN expedition run snapshot. One run per student/week/phase.';
comment on table public.expedition_run_members is 'Append-only 3-member party snapshot. Sunday reuse of Saturday members is server-rejected by submit RPC.';
