-- 1. TABLES
-- ============================================================================

CREATE TABLE public.raids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id INTEGER NOT NULL REFERENCES public.classrooms(id) ON DELETE RESTRICT,

  title TEXT NOT NULL,
  boss_name TEXT NOT NULL,
  boss_description TEXT,
  boss_element TEXT NOT NULL,

  status TEXT NOT NULL DEFAULT 'DRAFT',

  max_hp BIGINT NOT NULL,
  current_hp BIGINT NOT NULL,

  lobby_open_at TIMESTAMPTZ,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,

  damage_coefficient NUMERIC(14,6) NOT NULL DEFAULT 0.020000,
  variance_min NUMERIC(8,5) NOT NULL DEFAULT 0.90000,
  variance_max NUMERIC(8,5) NOT NULL DEFAULT 1.10000,
  crit_multiplier NUMERIC(8,4) NOT NULL DEFAULT 2.0000,
  tap_rate_limit_per_second SMALLINT NOT NULL DEFAULT 10,

  chat_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  chat_slow_mode_seconds SMALLINT NOT NULL DEFAULT 2,
  include_test_accounts BOOLEAN NOT NULL DEFAULT FALSE,

  reward_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raids_title_nonblank CHECK (btrim(title) <> ''),
  CONSTRAINT raids_boss_name_nonblank CHECK (btrim(boss_name) <> ''),
  CONSTRAINT raids_boss_element_chk CHECK (
    boss_element IN ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')
  ),
  CONSTRAINT raids_status_chk CHECK (
    status IN ('DRAFT','LOBBY_OPEN','ACTIVE','PAUSED','COMPLETED','FAILED','ARCHIVED')
  ),
  CONSTRAINT raids_hp_chk CHECK (
    max_hp > 0 AND current_hp >= 0 AND current_hp <= max_hp
  ),
  CONSTRAINT raids_damage_coefficient_chk CHECK (damage_coefficient > 0),
  CONSTRAINT raids_variance_chk CHECK (
    variance_min > 0 AND variance_max >= variance_min
  ),
  CONSTRAINT raids_crit_multiplier_chk CHECK (crit_multiplier >= 1),
  CONSTRAINT raids_tap_rate_chk CHECK (
    tap_rate_limit_per_second BETWEEN 1 AND 30
  ),
  CONSTRAINT raids_chat_slow_mode_chk CHECK (
    chat_slow_mode_seconds BETWEEN 0 AND 60
  ),
  CONSTRAINT raids_time_chk CHECK (
    ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at
  )
);

CREATE UNIQUE INDEX uq_raids_one_live_per_classroom
  ON public.raids(classroom_id)
  WHERE status IN ('LOBBY_OPEN','ACTIVE','PAUSED');

CREATE INDEX ix_raids_classroom_status
  ON public.raids(classroom_id, status, created_at DESC);

CREATE TABLE public.raid_phases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_id BIGINT NOT NULL REFERENCES public.raids(id) ON DELETE RESTRICT,
  phase_no SMALLINT NOT NULL,

  hp_from_ratio NUMERIC(7,6) NOT NULL,
  hp_to_ratio NUMERIC(7,6) NOT NULL,

  boss_element TEXT,
  image_url TEXT,
  loop_video_url TEXT,

  damage_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_phases_phase_no_chk CHECK (phase_no >= 1),
  CONSTRAINT raid_phases_ratio_chk CHECK (
    hp_from_ratio > 0
    AND hp_from_ratio <= 1
    AND hp_to_ratio >= 0
    AND hp_to_ratio < hp_from_ratio
  ),
  CONSTRAINT raid_phases_element_chk CHECK (
    boss_element IS NULL OR boss_element IN ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')
  ),
  CONSTRAINT uq_raid_phases_raid_phase UNIQUE (raid_id, phase_no)
);

CREATE INDEX ix_raid_phases_raid
  ON public.raid_phases(raid_id, phase_no);

CREATE TABLE public.raid_hit_zones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_phase_id BIGINT NOT NULL REFERENCES public.raid_phases(id) ON DELETE RESTRICT,

  zone_key TEXT NOT NULL,
  name TEXT NOT NULL,
  shape TEXT NOT NULL DEFAULT 'RECT',

  x NUMERIC(9,8) NOT NULL,
  y NUMERIC(9,8) NOT NULL,
  width NUMERIC(9,8) NOT NULL,
  height NUMERIC(9,8) NOT NULL,

  damage_multiplier NUMERIC(8,4) NOT NULL DEFAULT 1.0000,

  weak_element TEXT,
  element_multiplier NUMERIC(8,4) NOT NULL DEFAULT 1.0000,

  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_visible_to_student BOOLEAN NOT NULL DEFAULT FALSE,
  priority INTEGER NOT NULL DEFAULT 0,

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_hit_zones_key_nonblank CHECK (btrim(zone_key) <> ''),
  CONSTRAINT raid_hit_zones_name_nonblank CHECK (btrim(name) <> ''),
  CONSTRAINT raid_hit_zones_shape_chk CHECK (shape IN ('RECT','CIRCLE')),
  CONSTRAINT raid_hit_zones_coords_chk CHECK (
    x >= 0 AND x <= 1
    AND y >= 0 AND y <= 1
    AND width > 0 AND width <= 1
    AND height > 0 AND height <= 1
    AND x + width <= 1
    AND y + height <= 1
  ),
  CONSTRAINT raid_hit_zones_damage_multiplier_chk CHECK (damage_multiplier > 0),
  CONSTRAINT raid_hit_zones_weak_element_chk CHECK (
    weak_element IS NULL OR weak_element IN ('WATER','FIRE','WIND','EARTH','LIGHT','DARK')
  ),
  CONSTRAINT raid_hit_zones_element_multiplier_chk CHECK (element_multiplier > 0),
  CONSTRAINT uq_raid_hit_zones_phase_key UNIQUE (raid_phase_id, zone_key)
);

CREATE INDEX ix_raid_hit_zones_phase_active
  ON public.raid_hit_zones(raid_phase_id, is_active, priority DESC);

CREATE TABLE public.raid_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_id BIGINT NOT NULL REFERENCES public.raids(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,

  snapshot_student_name TEXT NOT NULL,
  snapshot_brand_name TEXT,

  snapshot_equipped_character_id BIGINT REFERENCES public.characters(id) ON DELETE RESTRICT,
  snapshot_equipped_character_name TEXT,
  snapshot_equipped_character_image_url TEXT,

  snapshot_guild_id INTEGER REFERENCES public.guilds(id) ON DELETE RESTRICT,
  snapshot_guild_name TEXT,
  snapshot_guild_logo_url TEXT,

  snapshot_owned_shard_count INTEGER NOT NULL,
  snapshot_raid_power BIGINT NOT NULL,

  snapshot_base_crit_bp INTEGER NOT NULL,
  snapshot_shard_crit_bp BIGINT NOT NULL,
  snapshot_collection_crit_bp INTEGER NOT NULL,
  snapshot_final_crit_bp INTEGER NOT NULL,

  snapshot_element_power JSONB NOT NULL,

  accepted_tap_count BIGINT NOT NULL DEFAULT 0,
  rejected_tap_count BIGINT NOT NULL DEFAULT 0,
  crit_count BIGINT NOT NULL DEFAULT 0,
  total_damage BIGINT NOT NULL DEFAULT 0,

  average_damage NUMERIC(20,4)
    GENERATED ALWAYS AS (
      CASE
        WHEN accepted_tap_count > 0
          THEN total_damage::numeric / accepted_tap_count::numeric
        ELSE 0::numeric
      END
    ) STORED,

  joined_lobby_at TIMESTAMPTZ,
  first_attack_at TIMESTAMPTZ,
  last_attack_at TIMESTAMPTZ,

  attack_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  attack_block_reason TEXT,

  final_rank INTEGER,
  reward_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_participants_owned_count_chk CHECK (snapshot_owned_shard_count >= 0),
  CONSTRAINT raid_participants_power_chk CHECK (snapshot_raid_power >= 0),
  CONSTRAINT raid_participants_base_crit_chk CHECK (
    snapshot_base_crit_bp BETWEEN 0 AND 10000
  ),
  CONSTRAINT raid_participants_shard_crit_chk CHECK (snapshot_shard_crit_bp >= 0),
  CONSTRAINT raid_participants_collection_crit_chk CHECK (snapshot_collection_crit_bp >= 0),
  CONSTRAINT raid_participants_final_crit_chk CHECK (
    snapshot_final_crit_bp BETWEEN 0 AND 10000
  ),
  CONSTRAINT raid_participants_counts_chk CHECK (
    accepted_tap_count >= 0
    AND rejected_tap_count >= 0
    AND crit_count >= 0
    AND crit_count <= accepted_tap_count
    AND total_damage >= 0
  ),
  CONSTRAINT raid_participants_rank_chk CHECK (final_rank IS NULL OR final_rank >= 1),
  CONSTRAINT uq_raid_participants_raid_student UNIQUE (raid_id, student_id)
);

CREATE INDEX ix_raid_participants_raid_damage
  ON public.raid_participants(raid_id, total_damage DESC, student_id);

CREATE INDEX ix_raid_participants_student
  ON public.raid_participants(student_id, raid_id DESC);

CREATE TABLE public.raid_attack_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_id BIGINT NOT NULL REFERENCES public.raids(id) ON DELETE RESTRICT,
  participant_id BIGINT NOT NULL REFERENCES public.raid_participants(id) ON DELETE RESTRICT,
  client_batch_id UUID NOT NULL,

  requested_taps INTEGER NOT NULL,
  accepted_taps INTEGER NOT NULL,
  rejected_taps INTEGER NOT NULL,

  total_damage BIGINT NOT NULL,
  crit_count INTEGER NOT NULL,

  zone_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  damage_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_payload JSONB NOT NULL,

  raid_hp_before BIGINT NOT NULL,
  raid_hp_after BIGINT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_attack_batches_taps_chk CHECK (
    requested_taps >= 1
    AND accepted_taps >= 0
    AND rejected_taps >= 0
    AND accepted_taps + rejected_taps = requested_taps
  ),
  CONSTRAINT raid_attack_batches_damage_chk CHECK (
    total_damage >= 0
    AND crit_count >= 0
    AND crit_count <= accepted_taps
  ),
  CONSTRAINT raid_attack_batches_hp_chk CHECK (
    raid_hp_before >= 0
    AND raid_hp_after >= 0
    AND raid_hp_after <= raid_hp_before
  ),
  CONSTRAINT uq_raid_attack_batches_idempotency UNIQUE (participant_id, client_batch_id)
);

CREATE INDEX ix_raid_attack_batches_raid_created
  ON public.raid_attack_batches(raid_id, created_at);

CREATE INDEX ix_raid_attack_batches_participant_created
  ON public.raid_attack_batches(participant_id, created_at DESC);

CREATE TABLE public.raid_lobby_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_id BIGINT NOT NULL REFERENCES public.raids(id) ON DELETE RESTRICT,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,

  message TEXT NOT NULL,

  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_by UUID,
  deleted_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_lobby_messages_message_chk CHECK (
    char_length(btrim(message)) BETWEEN 1 AND 60
  )
);

CREATE INDEX ix_raid_lobby_messages_raid_created
  ON public.raid_lobby_messages(raid_id, created_at DESC, id DESC);

CREATE INDEX ix_raid_lobby_messages_student_created
  ON public.raid_lobby_messages(student_id, created_at DESC);

CREATE TABLE public.raid_balance_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raid_id BIGINT NOT NULL REFERENCES public.raids(id) ON DELETE RESTRICT,
  algorithm_version TEXT NOT NULL,

  summary_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  distribution_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  crit_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  element_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  concentration_metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  hp_recommendation_basis JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT raid_balance_reports_version_nonblank CHECK (
    btrim(algorithm_version) <> ''
  ),
  CONSTRAINT uq_raid_balance_reports_version UNIQUE (raid_id, algorithm_version)
);

CREATE INDEX ix_raid_balance_reports_raid
  ON public.raid_balance_reports(raid_id, created_at DESC);

-- ============================================================================
-- 2. RLS / DIRECT TABLE ACCESS
-- ============================================================================

ALTER TABLE public.raids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_phases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_hit_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_attack_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_lobby_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.raid_balance_reports ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.raids,
  public.raid_phases,
  public.raid_hit_zones,
  public.raid_participants,
  public.raid_attack_batches,
  public.raid_lobby_messages,
  public.raid_balance_reports
FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE
  public.raids,
  public.raid_phases,
  public.raid_hit_zones,
  public.raid_participants,
  public.raid_attack_batches,
  public.raid_lobby_messages,
  public.raid_balance_reports
TO service_role;

REVOKE ALL ON SEQUENCE
  public.raids_id_seq,
  public.raid_phases_id_seq,
  public.raid_hit_zones_id_seq,
  public.raid_participants_id_seq,
  public.raid_attack_batches_id_seq,
  public.raid_lobby_messages_id_seq,
  public.raid_balance_reports_id_seq
FROM PUBLIC, anon, authenticated;

GRANT ALL ON SEQUENCE
  public.raids_id_seq,
  public.raid_phases_id_seq,
  public.raid_hit_zones_id_seq,
  public.raid_participants_id_seq,
  public.raid_attack_batches_id_seq,
  public.raid_lobby_messages_id_seq,
  public.raid_balance_reports_id_seq
TO service_role;

-- ============================================================================
