-- B.R.A.N.D 2.0 F4B — restore the current request -> teacher approval workflow only.
-- This intentionally does not apply unrelated Feature 4.1 changes.

CREATE TABLE IF NOT EXISTS public.emergency_quest_requests(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quest_id bigint NOT NULL REFERENCES public.emergency_quests(id) ON DELETE CASCADE,
  classroom_id integer NOT NULL REFERENCES public.classrooms(id),
  student_id integer NOT NULL REFERENCES public.students(id),
  status varchar(12) NOT NULL DEFAULT 'PENDING' CHECK(status IN('PENDING','APPROVED','REJECTED')),
  note text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by uuid,
  UNIQUE(quest_id,student_id)
);

CREATE INDEX IF NOT EXISTS idx_emergency_quest_requests_pending
  ON public.emergency_quest_requests(classroom_id,status,requested_at);

ALTER TABLE public.emergency_quest_requests ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS(
    SELECT 1 FROM pg_policies
    WHERE schemaname='public'
      AND tablename='emergency_quest_requests'
      AND policyname='emergency_quest_requests_select'
  ) THEN
    CREATE POLICY emergency_quest_requests_select
      ON public.emergency_quest_requests
      FOR SELECT TO authenticated
      USING(student_id=public.current_student_id() OR public.is_teacher_or_admin());
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.request_emergency_quest_completion(p_student_id integer,p_quest_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE
  q public.emergency_quests%ROWTYPE;
  v_class integer;
  v_id bigint;
  v_status text;
BEGIN
  PERFORM public.ensure_self_or_teacher(p_student_id);
  SELECT classroom_id INTO v_class
  FROM public.students
  WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
  IF v_class IS NULL THEN RAISE EXCEPTION '[F4B] active student not found' USING ERRCODE='P4B25'; END IF;

  SELECT * INTO q FROM public.emergency_quests WHERE id=p_quest_id;
  IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
  IF q.classroom_id<>v_class THEN RAISE EXCEPTION '[F4B] quest belongs to another classroom' USING ERRCODE='P4B26'; END IF;
  IF q.status<>'ACTIVE' OR now()<q.starts_at OR now()>=q.expires_at THEN
    RAISE EXCEPTION '[F4B] quest is not requestable' USING ERRCODE='P4B27';
  END IF;

  IF EXISTS(
    SELECT 1 FROM public.emergency_quest_completions
    WHERE quest_id=p_quest_id AND student_id=p_student_id
  ) THEN
    RAISE EXCEPTION '[F4B] quest already completed' USING ERRCODE='P4B28';
  END IF;

  SELECT status,id INTO v_status,v_id
  FROM public.emergency_quest_requests
  WHERE quest_id=p_quest_id AND student_id=p_student_id
  FOR UPDATE;

  IF v_id IS NULL THEN
    INSERT INTO public.emergency_quest_requests(quest_id,classroom_id,student_id)
    VALUES(p_quest_id,v_class,p_student_id)
    RETURNING id INTO v_id;
  ELSIF v_status='PENDING' THEN
    RETURN v_id;
  ELSIF v_status='APPROVED' THEN
    RAISE EXCEPTION '[F4B] quest already approved' USING ERRCODE='P4B28';
  ELSE
    UPDATE public.emergency_quest_requests
    SET status='PENDING',note=NULL,requested_at=now(),reviewed_at=NULL,reviewed_by=NULL
    WHERE id=v_id;
  END IF;

  RETURN v_id;
END $$;

CREATE OR REPLACE FUNCTION public._grant_emergency_quest_after_approval(p_student_id integer,p_quest_id bigint)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE
  q public.emergency_quests%ROWTYPE;
  v_class integer;
  v_completion bigint;
  v_gold bigint;
  v_bv bigint;
  v_crystal bigint;
BEGIN
  SELECT classroom_id INTO v_class
  FROM public.students
  WHERE id=p_student_id AND transferred_at IS NULL AND role='STUDENT';
  IF v_class IS NULL THEN RAISE EXCEPTION '[F4B] active student not found' USING ERRCODE='P4B25'; END IF;

  SELECT * INTO q FROM public.emergency_quests WHERE id=p_quest_id FOR UPDATE;
  IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;
  IF q.classroom_id<>v_class THEN RAISE EXCEPTION '[F4B] quest belongs to another classroom' USING ERRCODE='P4B26'; END IF;

  INSERT INTO public.emergency_quest_completions(quest_id,classroom_id,student_id)
  VALUES(q.id,v_class,p_student_id)
  RETURNING id INTO v_completion;

  IF q.reward_gold>0 THEN
    v_gold:=public.create_transaction(p_student_id,'GOLD',q.reward_gold,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트] %s',q.title));
  END IF;
  IF q.reward_bv>0 THEN
    v_bv:=public.create_transaction(p_student_id,'BV',q.reward_bv,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트 명예] %s',q.title));
  END IF;
  IF q.reward_crystal>0 THEN
    v_crystal:=public.create_transaction(p_student_id,'CRYSTAL',q.reward_crystal,'DAILY_QUEST',v_completion,0,format('[돌발 퀘스트 크리스탈] %s',q.title));
  END IF;

  UPDATE public.emergency_quest_completions
  SET gold_transaction_id=v_gold,
      bv_transaction_id=v_bv,
      crystal_transaction_id=v_crystal
  WHERE id=v_completion;

  PERFORM public.send_mail(
    p_student_id,'SYSTEM',NULL,NULL,'⚡ 돌발 퀘스트 완료',
    format('"%s" 완료 요청이 승인되어 보상이 지급되었습니다.',q.title),'REWARD','DAILY_QUEST',v_completion
  );
  PERFORM public.push_activity_feed(
    v_class,'OTHER',p_student_id,
    jsonb_build_object('message','돌발 퀘스트 완료 승인','quest_title',q.title),'PUBLIC'
  );
  RETURN v_completion;
EXCEPTION WHEN unique_violation THEN
  RAISE EXCEPTION '[F4B] quest already completed' USING ERRCODE='P4B28';
END $$;

CREATE OR REPLACE FUNCTION public.teacher_review_emergency_quest_request(
  p_request_id bigint,
  p_approve boolean,
  p_note text DEFAULT NULL
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp
AS $$
DECLARE
  r public.emergency_quest_requests%ROWTYPE;
  q public.emergency_quests%ROWTYPE;
  v_completion bigint;
BEGIN
  PERFORM public.ensure_teacher_role();

  SELECT * INTO r
  FROM public.emergency_quest_requests
  WHERE id=p_request_id
  FOR UPDATE;
  IF r.id IS NULL THEN RAISE EXCEPTION '[F4B] quest request not found' USING ERRCODE='P4B29'; END IF;
  IF NOT public.is_classroom_member(r.classroom_id) THEN RAISE EXCEPTION '[F4B] teacher classroom denied' USING ERRCODE='P4B10'; END IF;
  IF r.status<>'PENDING' THEN RAISE EXCEPTION '[F4B] quest request already reviewed' USING ERRCODE='P4B29'; END IF;

  SELECT * INTO q FROM public.emergency_quests WHERE id=r.quest_id FOR UPDATE;
  IF q.id IS NULL THEN RAISE EXCEPTION '[F4B] quest not found' USING ERRCODE='P4B24'; END IF;

  -- A teacher may approve later as long as the student's request was made while the quest was valid.
  IF r.requested_at<q.starts_at OR r.requested_at>=q.expires_at THEN
    RAISE EXCEPTION '[F4B] completion request was outside quest window' USING ERRCODE='P4B27';
  END IF;

  IF p_approve THEN
    v_completion:=public._grant_emergency_quest_after_approval(r.student_id,r.quest_id);
    UPDATE public.emergency_quest_requests
    SET status='APPROVED',note=nullif(btrim(coalesce(p_note,'')),''),reviewed_at=now(),reviewed_by=auth.uid()
    WHERE id=r.id;
  ELSE
    UPDATE public.emergency_quest_requests
    SET status='REJECTED',note=nullif(btrim(coalesce(p_note,'')),''),reviewed_at=now(),reviewed_by=auth.uid()
    WHERE id=r.id;
    v_completion:=0;
  END IF;

  RETURN v_completion;
END $$;

-- Current UI requires teacher approval. Prevent authenticated clients from bypassing it.
REVOKE ALL ON FUNCTION public.complete_emergency_quest(integer,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.complete_emergency_quest(integer,bigint) TO service_role;

REVOKE ALL ON FUNCTION public._grant_emergency_quest_after_approval(integer,bigint) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public._grant_emergency_quest_after_approval(integer,bigint) TO service_role;

REVOKE ALL ON FUNCTION public.request_emergency_quest_completion(integer,bigint) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.request_emergency_quest_completion(integer,bigint) TO authenticated,service_role;

REVOKE ALL ON FUNCTION public.teacher_review_emergency_quest_request(bigint,boolean,text) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.teacher_review_emergency_quest_request(bigint,boolean,text) TO authenticated,service_role;

REVOKE ALL ON TABLE public.emergency_quest_requests FROM anon;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON TABLE public.emergency_quest_requests FROM authenticated;
GRANT SELECT ON TABLE public.emergency_quest_requests TO authenticated;
GRANT ALL ON TABLE public.emergency_quest_requests TO service_role;