-- B.R.A.N.D 2.0 — App Access Event History V2
-- IMPORTANT: run PREFLIGHT_APP_ACCESS_EVENTS_V2.sql against production first.

create table if not exists public.app_access_events (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id) on delete restrict,
  student_id integer not null references public.students(id) on delete restrict,
  auth_user_id uuid not null,
  occurred_at timestamptz not null default clock_timestamp(),
  access_date date not null,
  source text not null,
  is_visit_start boolean not null default false,
  device_type text,
  browser text,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default clock_timestamp(),
  constraint app_access_events_source_len_chk check (char_length(source) between 1 and 40),
  constraint app_access_events_device_len_chk check (device_type is null or char_length(device_type)<=40),
  constraint app_access_events_browser_len_chk check (browser is null or char_length(browser)<=80)
);

comment on table public.app_access_events is
'Append-only direct B.R.A.N.D app access signals. Canonical access count is count(*) where is_visit_start=true.';
comment on column public.app_access_events.is_visit_start is
'True when this direct signal begins a new visit after at least 30 minutes of inactivity.';

create index if not exists app_access_events_classroom_time_idx on public.app_access_events(classroom_id,occurred_at desc,id desc);
create index if not exists app_access_events_student_time_idx on public.app_access_events(student_id,occurred_at desc,id desc);
create index if not exists app_access_events_date_idx on public.app_access_events(classroom_id,access_date desc,student_id,occurred_at desc);
create index if not exists app_access_events_visit_start_idx on public.app_access_events(student_id,occurred_at desc) where is_visit_start;

alter table public.app_access_events enable row level security;
revoke all on table public.app_access_events from public,anon,authenticated;

create or replace function public.record_app_access_event(
  p_source text default 'APP_OPEN',
  p_device_type text default null,
  p_browser text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_student_id integer;
  v_classroom_id integer;
  v_now timestamptz:=clock_timestamp();
  v_previous_at timestamptz;
  v_source text;
  v_is_visit_start boolean;
  v_event_id bigint;
begin
  if v_uid is null then raise exception 'Authentication required' using errcode='P0510'; end if;

  select s.id,s.classroom_id into v_student_id,v_classroom_id
  from public.students s
  where s.user_id=v_uid and s.transferred_at is null
    and not coalesce(s.is_test_account,false)
    and s.role::text in ('STUDENT','STUDENT_LEADER','GUARD')
  order by s.id limit 1;

  if v_student_id is null then
    return jsonb_build_object('recorded',false,'reason','NOT_TRACKED_STUDENT');
  end if;

  v_source:=case upper(coalesce(btrim(p_source),''))
    when 'EXPLICIT_LOGIN' then 'EXPLICIT_LOGIN'
    when 'SESSION_RESTORE' then 'SESSION_RESTORE'
    when 'APP_RESUME' then 'APP_RESUME'
    else 'APP_OPEN' end;

  perform pg_advisory_xact_lock(702026,v_student_id);
  select e.occurred_at into v_previous_at
  from public.app_access_events e
  where e.student_id=v_student_id
  order by e.occurred_at desc,e.id desc limit 1;

  v_is_visit_start:=v_previous_at is null or v_previous_at<=v_now-interval '30 minutes';

  insert into public.app_access_events(
    classroom_id,student_id,auth_user_id,occurred_at,access_date,source,is_visit_start,device_type,browser
  ) values(
    v_classroom_id,v_student_id,v_uid,v_now,(v_now at time zone 'Asia/Seoul')::date,v_source,v_is_visit_start,
    left(nullif(btrim(p_device_type),''),40),left(nullif(btrim(p_browser),''),80)
  ) returning id into v_event_id;

  insert into public.app_access_daily(
    classroom_id,student_id,auth_user_id,access_date,first_seen_at,last_seen_at,signal_count,evidence_sources,
    has_direct_app_signal,has_backfill_signal,last_device_type,last_browser,metadata
  ) values(
    v_classroom_id,v_student_id,v_uid,(v_now at time zone 'Asia/Seoul')::date,v_now,v_now,1,array[v_source],
    true,false,left(nullif(btrim(p_device_type),''),40),left(nullif(btrim(p_browser),''),80),jsonb_build_object('access_v2',true)
  )
  on conflict(student_id,access_date) do update set
    first_seen_at=least(public.app_access_daily.first_seen_at,excluded.first_seen_at),
    last_seen_at=greatest(public.app_access_daily.last_seen_at,excluded.last_seen_at),
    signal_count=public.app_access_daily.signal_count+1,
    evidence_sources=(select coalesce(array_agg(distinct x order by x),'{}'::text[]) from unnest(public.app_access_daily.evidence_sources||excluded.evidence_sources) u(x)),
    has_direct_app_signal=true,
    last_device_type=coalesce(excluded.last_device_type,public.app_access_daily.last_device_type),
    last_browser=coalesce(excluded.last_browser,public.app_access_daily.last_browser),
    metadata=public.app_access_daily.metadata||excluded.metadata,
    updated_at=v_now;

  -- Preserve the production weekend-attendance behavior already used by
  -- record_app_access(): an exact weekend app access immediately creates
  -- PRESENT attendance through the existing reconciled helper.
  if extract(isodow from (v_now at time zone 'Asia/Seoul')::date)::integer in (6,7) then
    perform public._ensure_weekend_app_attendance(
      v_student_id,
      (v_now at time zone 'Asia/Seoul')::date,
      v_uid
    );
  end if;

  return jsonb_build_object('recorded',true,'event_id',v_event_id,'occurred_at',v_now,
    'is_visit_start',v_is_visit_start,'visit_inactivity_minutes',30);
end $$;

revoke all on function public.record_app_access_event(text,text,text) from public,anon;
grant execute on function public.record_app_access_event(text,text,text) to authenticated;

create or replace function public.teacher_get_app_access_history(
  p_classroom_id integer,
  p_limit integer default 100,
  p_offset integer default 0,
  p_student_id integer default null,
  p_date_from date default null,
  p_date_to date default null
)
returns jsonb
language plpgsql stable security definer set search_path=public,pg_temp
as $$
declare
  v_limit integer:=least(greatest(coalesce(p_limit,100),1),500);
  v_offset integer:=greatest(coalesce(p_offset,0),0);
  v_total bigint;
  v_summary jsonb;
  v_students jsonb;
  v_rows jsonb;
  v_tracking_start timestamptz;
  v_legacy_start date;
begin
  perform public.ensure_teacher_role();
  if p_classroom_id is null or p_classroom_id<>public.current_classroom_id() then
    raise exception 'Permission denied: classroom mismatch' using errcode='P0511';
  end if;
  if p_date_from is not null and p_date_to is not null and p_date_from>p_date_to then
    raise exception 'p_date_from must be on or before p_date_to' using errcode='22023';
  end if;

  select min(occurred_at) into v_tracking_start from public.app_access_events where classroom_id=p_classroom_id;
  select min(access_date) into v_legacy_start from public.app_access_daily where classroom_id=p_classroom_id;

  with f as (
    select e.* from public.app_access_events e
    where e.classroom_id=p_classroom_id and (p_student_id is null or e.student_id=p_student_id)
      and (p_date_from is null or e.access_date>=p_date_from) and (p_date_to is null or e.access_date<=p_date_to)
  )
  select count(*)::bigint,
    jsonb_build_object('raw_event_count',count(*)::bigint,
      'access_count',count(*) filter(where is_visit_start)::bigint,
      'access_student_days',count(distinct (student_id,access_date))::bigint,
      'distinct_students',count(distinct student_id)::bigint,
      'first_access_at',min(occurred_at),'last_access_at',max(occurred_at))
  into v_total,v_summary from f;

  with subjects as (
    select s.id,s.name from public.students s
    where s.classroom_id=p_classroom_id and s.transferred_at is null and not coalesce(s.is_test_account,false)
      and s.role::text in ('STUDENT','STUDENT_LEADER','GUARD') and (p_student_id is null or s.id=p_student_id)
  ), f as (
    select e.* from public.app_access_events e
    where e.classroom_id=p_classroom_id and (p_student_id is null or e.student_id=p_student_id)
      and (p_date_from is null or e.access_date>=p_date_from) and (p_date_to is null or e.access_date<=p_date_to)
  ), a as (
    select student_id,count(*)::bigint raw_event_count,
      count(*) filter(where is_visit_start)::bigint total_access_count,
      count(distinct access_date)::bigint total_access_days,
      count(*) filter(where is_visit_start and access_date=(now() at time zone 'Asia/Seoul')::date)::bigint today_access_count,
      min(occurred_at) first_access_at,max(occurred_at) last_access_at
    from f group by student_id
  )
  select coalesce(jsonb_agg(jsonb_build_object('student_id',s.id,'student_name',s.name,
    'raw_event_count',coalesce(a.raw_event_count,0),'total_access_count',coalesce(a.total_access_count,0),
    'total_access_days',coalesce(a.total_access_days,0),'today_access_count',coalesce(a.today_access_count,0),
    'first_access_at',a.first_access_at,'last_access_at',a.last_access_at) order by s.name),'[]'::jsonb)
  into v_students from subjects s left join a on a.student_id=s.id;

  with f as (
    select e.*,s.name student_name from public.app_access_events e join public.students s on s.id=e.student_id
    where e.classroom_id=p_classroom_id and (p_student_id is null or e.student_id=p_student_id)
      and (p_date_from is null or e.access_date>=p_date_from) and (p_date_to is null or e.access_date<=p_date_to)
    order by e.occurred_at desc,e.id desc limit v_limit offset v_offset
  )
  select coalesce(jsonb_agg(jsonb_build_object('id',id,'student_id',student_id,'student_name',student_name,
    'occurred_at',occurred_at,'access_date',access_date,'source',source,'is_visit_start',is_visit_start,
    'device_type',device_type,'browser',browser) order by occurred_at desc,id desc),'[]'::jsonb)
  into v_rows from f;

  return jsonb_build_object('tracking_start_at',v_tracking_start,'legacy_daily_tracking_start_date',v_legacy_start,
    'visit_inactivity_minutes',30,'total_count',coalesce(v_total,0),'limit',v_limit,'offset',v_offset,
    'summary',coalesce(v_summary,'{}'::jsonb),'student_summaries',v_students,'rows',v_rows);
end $$;

revoke all on function public.teacher_get_app_access_history(integer,integer,integer,integer,date,date) from public,anon;
grant execute on function public.teacher_get_app_access_history(integer,integer,integer,integer,date,date) to authenticated;

create or replace function public.my_app_access_footprint()
returns jsonb language plpgsql stable security definer set search_path=public,pg_temp
as $$
declare v_uid uuid:=auth.uid(); v_student_id integer; v_classroom_id integer; v_result jsonb;
begin
  if v_uid is null then raise exception 'Authentication required' using errcode='P0510'; end if;
  select id,classroom_id into v_student_id,v_classroom_id from public.students
  where user_id=v_uid and transferred_at is null and not coalesce(is_test_account,false)
    and role::text in ('STUDENT','STUDENT_LEADER','GUARD') order by id limit 1;
  if v_student_id is null then return jsonb_build_object('tracked',false); end if;
  select jsonb_build_object('tracked',true,'student_id',v_student_id,'classroom_id',v_classroom_id,
    'access_count',count(*) filter(where is_visit_start)::bigint,'raw_event_count',count(*)::bigint,
    'access_days',count(distinct access_date)::bigint,'first_access_at',min(occurred_at),'last_access_at',max(occurred_at),
    'tracking_start_at',(select min(occurred_at) from public.app_access_events where classroom_id=v_classroom_id),
    'visit_inactivity_minutes',30) into v_result from public.app_access_events where student_id=v_student_id;
  return v_result;
end $$;
revoke all on function public.my_app_access_footprint() from public,anon;
grant execute on function public.my_app_access_footprint() to authenticated;
