-- B.R.A.N.D. 2.0 — Newbie Support private foundation
-- v1.2 FINAL AUDIT

CREATE SCHEMA IF NOT EXISTS private;

REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA private TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA private REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA private REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA private REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;

CREATE TABLE private.newbie_support_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  version integer NOT NULL,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  regular_percent smallint NOT NULL DEFAULT 80,
  completion_percent smallint NOT NULL DEFAULT 20,
  mentor_min_count smallint NOT NULL DEFAULT 2,
  mentor_max_count smallint NOT NULL DEFAULT 3,
  mentor_min_valid_help smallint NOT NULL DEFAULT 3,
  mentor_base_reward_crystal bigint NOT NULL DEFAULT 2000,
  best_mentor_bonus_crystal bigint NOT NULL DEFAULT 1000,
  mentor_p2p_cap smallint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newbie_support_templates_code_version_uq UNIQUE (code, version),
  CONSTRAINT newbie_support_templates_regular_pct_ck CHECK (regular_percent BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_templates_completion_pct_ck CHECK (completion_percent BETWEEN 0 AND 99),
  CONSTRAINT newbie_support_templates_pct_sum_ck CHECK (regular_percent + completion_percent = 100),
  CONSTRAINT newbie_support_templates_mentor_min_ck CHECK (mentor_min_count BETWEEN 1 AND 10),
  CONSTRAINT newbie_support_templates_mentor_max_ck CHECK (mentor_max_count BETWEEN mentor_min_count AND 10),
  CONSTRAINT newbie_support_templates_help_min_ck CHECK (mentor_min_valid_help BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_templates_base_reward_ck CHECK (mentor_base_reward_crystal BETWEEN 0 AND 10000000),
  CONSTRAINT newbie_support_templates_best_reward_ck CHECK (best_mentor_bonus_crystal BETWEEN 0 AND 10000000),
  CONSTRAINT newbie_support_templates_p2p_cap_ck CHECK (mentor_p2p_cap BETWEEN 0 AND 100)
);

CREATE TABLE private.newbie_support_template_quests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id bigint NOT NULL REFERENCES private.newbie_support_templates(id) ON DELETE RESTRICT,
  quest_code text NOT NULL,
  title text NOT NULL,
  description text,
  target_count smallint NOT NULL,
  weight_per_completion smallint NOT NULL,
  verification_type text NOT NULL,
  sort_order integer NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT newbie_support_template_quests_code_uq UNIQUE (template_id, quest_code),
  CONSTRAINT newbie_support_template_quests_sort_uq UNIQUE (template_id, sort_order),
  CONSTRAINT newbie_support_template_quests_target_ck CHECK (target_count BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_template_quests_weight_ck CHECK (weight_per_completion BETWEEN 1 AND 1000),
  CONSTRAINT newbie_support_template_quests_sort_ck CHECK (sort_order > 0),
  CONSTRAINT newbie_support_template_quests_config_ck CHECK (jsonb_typeof(config)='object'),
  CONSTRAINT newbie_support_template_quests_code_ck CHECK (quest_code IN (
    'P2P_SELL_REVIEW','P2P_BUY_REVIEW','COLLECTION_FIRST','COLLECTION_SECOND',
    'PUBLIC_REQUEST_DELIVERY','CLASS_HELP_BONUS_300','ARCADE_FOCUS_50000'
  )),
  CONSTRAINT newbie_support_template_quests_verification_ck CHECK (verification_type IN (
    'P2P_SELL_REVIEW','P2P_BUY_REVIEW','COLLECTION_FIRST','COLLECTION_SECOND',
    'PUBLIC_REQUEST_DELIVERY','CLASS_HELP_BONUS_300','ARCADE_FOCUS_50000'
  )),
  CONSTRAINT newbie_support_template_quests_mapping_ck CHECK (verification_type = quest_code)
);

CREATE TABLE private.newbie_support_programs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id integer NOT NULL REFERENCES public.classrooms(id) ON DELETE RESTRICT,
  student_id integer NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
  template_id bigint NOT NULL REFERENCES private.newbie_support_templates(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'DRAFT',
  missed_opportunities integer NOT NULL,
  bv_per_opportunity bigint NOT NULL,
  total_restorable_bv bigint NOT NULL,
  regular_percent smallint NOT NULL,
  completion_percent smallint NOT NULL,
  regular_quest_pool_bv bigint NOT NULL,
  completion_bonus_bv bigint NOT NULL,
  total_quest_weight integer NOT NULL,
  start_on date NOT NULL,
  end_on date NOT NULL,
  mentor_min_count smallint NOT NULL,
  mentor_max_count smallint NOT NULL,
  mentor_min_valid_help smallint NOT NULL,
  mentor_base_reward_crystal bigint NOT NULL,
  best_mentor_bonus_crystal bigint NOT NULL,
  mentor_p2p_cap smallint NOT NULL,
  completion_requested_at timestamptz,
  best_mentor_assignment_id bigint,
  completion_bonus_transaction_id bigint REFERENCES public.transactions(id) ON DELETE RESTRICT,
  activated_at timestamptz,
  completed_at timestamptz,
  expired_at timestamptz,
  cancelled_at timestamptz,
  cancel_reason text,
  created_by uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newbie_support_programs_status_ck CHECK (status IN ('DRAFT','ACTIVE','COMPLETED','EXPIRED','CANCELLED')),
  CONSTRAINT newbie_support_programs_missed_ck CHECK (missed_opportunities BETWEEN 1 AND 1000),
  CONSTRAINT newbie_support_programs_bv_per_ck CHECK (bv_per_opportunity BETWEEN 1 AND 10000),
  CONSTRAINT newbie_support_programs_total_bv_ck CHECK (total_restorable_bv BETWEEN 1 AND 10000000),
  CONSTRAINT newbie_support_programs_regular_pct_ck CHECK (regular_percent BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_programs_completion_pct_ck CHECK (completion_percent BETWEEN 0 AND 99),
  CONSTRAINT newbie_support_programs_pct_sum_ck CHECK (regular_percent + completion_percent = 100),
  CONSTRAINT newbie_support_programs_date_ck CHECK (start_on <= end_on),
  CONSTRAINT newbie_support_programs_mentor_min_ck CHECK (mentor_min_count BETWEEN 1 AND 10),
  CONSTRAINT newbie_support_programs_mentor_max_ck CHECK (mentor_max_count BETWEEN mentor_min_count AND 10),
  CONSTRAINT newbie_support_programs_help_min_ck CHECK (mentor_min_valid_help BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_programs_base_reward_ck CHECK (mentor_base_reward_crystal BETWEEN 0 AND 10000000),
  CONSTRAINT newbie_support_programs_best_reward_ck CHECK (best_mentor_bonus_crystal BETWEEN 0 AND 10000000),
  CONSTRAINT newbie_support_programs_p2p_cap_ck CHECK (mentor_p2p_cap BETWEEN 0 AND 100),
  CONSTRAINT newbie_support_programs_math_total_ck CHECK (total_restorable_bv = missed_opportunities::bigint * bv_per_opportunity),
  CONSTRAINT newbie_support_programs_math_regular_ck CHECK (regular_quest_pool_bv = (total_restorable_bv * regular_percent) / 100),
  CONSTRAINT newbie_support_programs_math_completion_ck CHECK (completion_bonus_bv = total_restorable_bv - regular_quest_pool_bv),
  CONSTRAINT newbie_support_programs_pool_nonneg_ck CHECK (regular_quest_pool_bv >= 0 AND completion_bonus_bv >= 0),
  CONSTRAINT newbie_support_programs_weight_ck CHECK (total_quest_weight > 0)
);
CREATE UNIQUE INDEX newbie_support_one_active_program_uq
  ON private.newbie_support_programs(classroom_id,student_id) WHERE status='ACTIVE';
CREATE UNIQUE INDEX newbie_support_completion_tx_uq
  ON private.newbie_support_programs(completion_bonus_transaction_id) WHERE completion_bonus_transaction_id IS NOT NULL;

CREATE TABLE private.newbie_support_program_quests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL REFERENCES private.newbie_support_programs(id) ON DELETE CASCADE,
  quest_code text NOT NULL,
  title text NOT NULL,
  description text,
  target_count smallint NOT NULL,
  weight_per_completion smallint NOT NULL,
  verification_type text NOT NULL,
  sort_order integer NOT NULL,
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT newbie_support_program_quests_program_id_uq UNIQUE (program_id,id),
  CONSTRAINT newbie_support_program_quests_code_uq UNIQUE (program_id,quest_code),
  CONSTRAINT newbie_support_program_quests_sort_uq UNIQUE (program_id,sort_order),
  CONSTRAINT newbie_support_program_quests_target_ck CHECK (target_count BETWEEN 1 AND 100),
  CONSTRAINT newbie_support_program_quests_weight_ck CHECK (weight_per_completion BETWEEN 1 AND 1000),
  CONSTRAINT newbie_support_program_quests_sort_ck CHECK (sort_order > 0),
  CONSTRAINT newbie_support_program_quests_config_ck CHECK (jsonb_typeof(config)='object'),
  CONSTRAINT newbie_support_program_quests_code_ck CHECK (quest_code IN (
    'P2P_SELL_REVIEW','P2P_BUY_REVIEW','COLLECTION_FIRST','COLLECTION_SECOND',
    'PUBLIC_REQUEST_DELIVERY','CLASS_HELP_BONUS_300','ARCADE_FOCUS_50000'
  )),
  CONSTRAINT newbie_support_program_quests_verification_ck CHECK (verification_type IN (
    'P2P_SELL_REVIEW','P2P_BUY_REVIEW','COLLECTION_FIRST','COLLECTION_SECOND',
    'PUBLIC_REQUEST_DELIVERY','CLASS_HELP_BONUS_300','ARCADE_FOCUS_50000'
  )),
  CONSTRAINT newbie_support_program_quests_mapping_ck CHECK (verification_type = quest_code)
);

CREATE TABLE private.newbie_support_program_public_requests (
  program_id bigint NOT NULL REFERENCES private.newbie_support_programs(id) ON DELETE CASCADE,
  request_id bigint NOT NULL REFERENCES public.secondary_job_public_requests(id) ON DELETE RESTRICT,
  PRIMARY KEY(program_id,request_id)
);

CREATE TABLE private.newbie_support_program_mentors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL REFERENCES private.newbie_support_programs(id) ON DELETE CASCADE,
  mentor_student_id integer NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
  base_reward_transaction_id bigint REFERENCES public.transactions(id) ON DELETE RESTRICT,
  best_reward_transaction_id bigint REFERENCES public.transactions(id) ON DELETE RESTRICT,
  base_reward_outcome text,
  best_reward_outcome text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newbie_support_program_mentors_program_id_uq UNIQUE(program_id,id),
  CONSTRAINT newbie_support_program_mentors_student_uq UNIQUE(program_id,mentor_student_id),
  CONSTRAINT newbie_support_program_mentors_base_outcome_ck CHECK (base_reward_outcome IS NULL OR base_reward_outcome IN ('PAID','INELIGIBLE','SKIPPED_INACTIVE')),
  CONSTRAINT newbie_support_program_mentors_best_outcome_ck CHECK (best_reward_outcome IS NULL OR best_reward_outcome IN ('PAID','NOT_SELECTED','SKIPPED_INACTIVE'))
);
CREATE UNIQUE INDEX newbie_support_mentor_base_tx_uq
  ON private.newbie_support_program_mentors(base_reward_transaction_id) WHERE base_reward_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX newbie_support_mentor_best_tx_uq
  ON private.newbie_support_program_mentors(best_reward_transaction_id) WHERE best_reward_transaction_id IS NOT NULL;

ALTER TABLE private.newbie_support_programs
  ADD CONSTRAINT newbie_support_programs_best_mentor_fk
  FOREIGN KEY(id, best_mentor_assignment_id)
  REFERENCES private.newbie_support_program_mentors(program_id,id)
  DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE private.newbie_support_program_quest_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL,
  program_quest_id bigint NOT NULL,
  occurrence_no smallint NOT NULL,
  reward_bv bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT newbie_support_slots_program_id_uq UNIQUE(program_id,id),
  CONSTRAINT newbie_support_slots_occurrence_uq UNIQUE(program_quest_id,occurrence_no),
  CONSTRAINT newbie_support_slots_program_quest_fk FOREIGN KEY(program_id,program_quest_id)
    REFERENCES private.newbie_support_program_quests(program_id,id) ON DELETE CASCADE,
  CONSTRAINT newbie_support_slots_occurrence_ck CHECK (occurrence_no > 0),
  CONSTRAINT newbie_support_slots_reward_ck CHECK (reward_bv > 0)
);

CREATE TABLE private.newbie_support_program_collection_baseline (
  program_id bigint NOT NULL REFERENCES private.newbie_support_programs(id) ON DELETE CASCADE,
  collection_id bigint NOT NULL REFERENCES public.character_collections(id) ON DELETE RESTRICT,
  captured_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(program_id,collection_id)
);

CREATE TABLE private.newbie_support_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL,
  slot_id bigint NOT NULL,
  status text NOT NULL DEFAULT 'PENDING',
  evidence_type text NOT NULL,
  evidence_ref_id bigint NOT NULL,
  evidence_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  student_note text,
  requested_at timestamptz NOT NULL DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamptz,
  review_note text,
  reward_bv bigint,
  reward_transaction_id bigint REFERENCES public.transactions(id) ON DELETE RESTRICT,
  reversal_transaction_id bigint REFERENCES public.transactions(id) ON DELETE RESTRICT,
  CONSTRAINT newbie_support_claims_program_id_uq UNIQUE(program_id,id),
  CONSTRAINT newbie_support_claims_slot_fk FOREIGN KEY(program_id,slot_id)
    REFERENCES private.newbie_support_program_quest_slots(program_id,id) ON DELETE RESTRICT,
  CONSTRAINT newbie_support_claims_status_ck CHECK (status IN ('PENDING','APPROVED','REJECTED','REVOKED','CANCELLED')),
  CONSTRAINT newbie_support_claims_evidence_ck CHECK (evidence_type IN (
    'P2P_SELL_REVIEW','P2P_BUY_REVIEW','COLLECTION_FIRST','COLLECTION_SECOND',
    'PUBLIC_REQUEST_DELIVERY','CLASS_HELP_BONUS_300','ARCADE_FOCUS_50000'
  )),
  CONSTRAINT newbie_support_claims_payload_ck CHECK (jsonb_typeof(evidence_payload)='object'),
  CONSTRAINT newbie_support_claims_note_ck CHECK (student_note IS NULL OR char_length(student_note) <= 500),
  CONSTRAINT newbie_support_claims_review_note_ck CHECK (review_note IS NULL OR char_length(review_note) <= 1000),
  CONSTRAINT newbie_support_claims_state_ck CHECK (
    (status='PENDING' AND reward_transaction_id IS NULL AND reversal_transaction_id IS NULL)
    OR (status='APPROVED' AND reward_bv IS NOT NULL AND reward_transaction_id IS NOT NULL AND reviewed_at IS NOT NULL AND reversal_transaction_id IS NULL)
    OR (status='REJECTED' AND reward_transaction_id IS NULL AND reversal_transaction_id IS NULL AND reviewed_at IS NOT NULL)
    OR (status='REVOKED' AND reward_bv IS NOT NULL AND reward_transaction_id IS NOT NULL AND reversal_transaction_id IS NOT NULL AND reviewed_at IS NOT NULL)
    OR (status='CANCELLED' AND reward_transaction_id IS NULL AND reversal_transaction_id IS NULL)
  )
);
CREATE UNIQUE INDEX newbie_support_claim_open_slot_uq
  ON private.newbie_support_claims(slot_id) WHERE status IN ('PENDING','APPROVED');
CREATE UNIQUE INDEX newbie_support_claim_open_evidence_uq
  ON private.newbie_support_claims(program_id,evidence_type,evidence_ref_id) WHERE status IN ('PENDING','APPROVED');
CREATE UNIQUE INDEX newbie_support_claim_reward_tx_uq
  ON private.newbie_support_claims(reward_transaction_id) WHERE reward_transaction_id IS NOT NULL;
CREATE UNIQUE INDEX newbie_support_claim_reversal_tx_uq
  ON private.newbie_support_claims(reversal_transaction_id) WHERE reversal_transaction_id IS NOT NULL;

CREATE TABLE private.newbie_support_claim_mentor_help (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint NOT NULL,
  claim_id bigint NOT NULL,
  mentor_assignment_id bigint NOT NULL,
  help_type text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now(),
  validated_at timestamptz,
  CONSTRAINT newbie_support_claim_help_claim_fk FOREIGN KEY(program_id,claim_id)
    REFERENCES private.newbie_support_claims(program_id,id) ON DELETE CASCADE,
  CONSTRAINT newbie_support_claim_help_mentor_fk FOREIGN KEY(program_id,mentor_assignment_id)
    REFERENCES private.newbie_support_program_mentors(program_id,id) ON DELETE RESTRICT,
  CONSTRAINT newbie_support_claim_help_uq UNIQUE(claim_id,mentor_assignment_id),
  CONSTRAINT newbie_support_claim_help_type_ck CHECK (help_type IN ('EXPLANATION','COACHING','CHECKING','TRANSACTION','OTHER')),
  CONSTRAINT newbie_support_claim_help_status_ck CHECK (status IN ('PENDING','VALID','INVALID'))
);

CREATE TABLE private.transaction_record_exclusions (
  transaction_id bigint NOT NULL REFERENCES public.transactions(id) ON DELETE CASCADE,
  record_scope text NOT NULL,
  reason_code text NOT NULL,
  source_entity_type text,
  source_entity_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(transaction_id,record_scope),
  CONSTRAINT transaction_record_exclusions_scope_ck CHECK (record_scope IN ('MONTHLY_BV_GAIN')),
  CONSTRAINT transaction_record_exclusions_reason_ck CHECK (reason_code IN ('NEWBIE_SETTLEMENT_RESTORATION'))
);

CREATE INDEX newbie_support_programs_class_status_dates_idx ON private.newbie_support_programs(classroom_id,status,start_on,end_on);
CREATE INDEX newbie_support_programs_student_status_idx ON private.newbie_support_programs(student_id,status);
CREATE INDEX newbie_support_program_quests_sort_idx ON private.newbie_support_program_quests(program_id,sort_order);
CREATE INDEX newbie_support_slots_lookup_idx ON private.newbie_support_program_quest_slots(program_id,program_quest_id,occurrence_no);
CREATE INDEX newbie_support_mentors_student_idx ON private.newbie_support_program_mentors(mentor_student_id,program_id);
CREATE INDEX newbie_support_claims_status_idx ON private.newbie_support_claims(program_id,status,requested_at);
CREATE INDEX newbie_support_claims_evidence_idx ON private.newbie_support_claims(evidence_type,evidence_ref_id);
CREATE INDEX newbie_support_claim_help_mentor_idx ON private.newbie_support_claim_mentor_help(mentor_assignment_id,status);
CREATE INDEX newbie_support_claim_help_claim_idx ON private.newbie_support_claim_mentor_help(claim_id,status);

DO $do$
DECLARE r record;
BEGIN
  FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='private' LOOP
    EXECUTE format('ALTER TABLE private.%I ENABLE ROW LEVEL SECURITY', r.tablename);
    EXECUTE format('REVOKE ALL ON TABLE private.%I FROM PUBLIC, anon, authenticated', r.tablename);
  END LOOP;
END
$do$;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA private FROM PUBLIC, anon, authenticated;
