-- B.R.A.N.D 2.0
-- Teacher asset adjustment: combined deduct, configurable income tax, asset arrears.
-- Production Supabase was already updated directly on 2026-09-21.
-- This migration is included for source-control parity / future environments.

begin;

create table if not exists public.student_asset_arrears (
  id bigint generated by default as identity primary key,
  classroom_id integer not null references public.classrooms(id),
  student_id integer not null references public.students(id),
  value_token public.value_token_type not null,
  assessed_amount bigint not null check (assessed_amount > 0),
  paid_amount bigint not null default 0 check (paid_amount >= 0 and paid_amount <= assessed_amount),
  reason text not null check (char_length(btrim(reason)) between 2 and 200),
  status text not null default 'UNPAID'
    check (status in ('UNPAID','PARTIAL','PAID','WAIVED')),
  initial_transaction_id bigint references public.transactions(id),
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  settled_at timestamptz,
  waived_at timestamptz
);

create index if not exists idx_student_asset_arrears_student_open
  on public.student_asset_arrears(student_id, value_token, created_at, id)
  where status in ('UNPAID','PARTIAL');

create index if not exists idx_student_asset_arrears_classroom_open
  on public.student_asset_arrears(classroom_id, status, created_at, id);

alter table public.student_asset_arrears enable row level security;
revoke all on public.student_asset_arrears from public, anon, authenticated;

create or replace function public.teacher_get_asset_adjustment_config(p_classroom_id integer)
returns jsonb
language plpgsql
stable security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_setting jsonb;
  v_raw numeric;
  v_rate numeric;
begin
  perform public.ensure_teacher_role();

  if p_classroom_id is null
     or p_classroom_id is distinct from public.current_classroom_id() then
    raise exception '담당 학급의 자산 설정만 조회할 수 있습니다.' using errcode='P0630';
  end if;

  select cs.setting_value into v_setting
  from public.classroom_settings cs
  where cs.classroom_id=p_classroom_id
    and cs.setting_key='income_tax_rate';

  v_raw:=coalesce((v_setting)::text::numeric,0.10);
  if v_raw between 0 and 1 then
    v_rate:=v_raw*100;
  elsif v_raw>1 and v_raw<100 then
    v_rate:=v_raw;
  else
    v_rate:=10;
  end if;

  return jsonb_build_object(
    'classroom_id',p_classroom_id,
    'income_tax_rate_percent',round(v_rate,2)
  );
end;
$function$;

revoke all on function public.teacher_get_asset_adjustment_config(integer) from public,anon;
grant execute on function public.teacher_get_asset_adjustment_config(integer) to authenticated,service_role;

create or replace function public._teacher_set_income_tax_rate_percent(
  p_classroom_id integer,
  p_rate_percent numeric
)
returns numeric
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_rate numeric;
begin
  if p_rate_percent is null or p_rate_percent<0 or p_rate_percent>=100 then
    raise exception '소득세율은 0 이상 100 미만으로 입력해주세요.' using errcode='P0631';
  end if;

  v_rate:=round(p_rate_percent,2)/100;

  insert into public.classroom_settings(classroom_id,setting_key,setting_value)
  values (p_classroom_id,'income_tax_rate',to_jsonb(v_rate))
  on conflict (classroom_id,setting_key) do update
  set setting_value=excluded.setting_value,
      updated_at=now();

  return v_rate;
end;
$function$;

revoke all on function public._teacher_set_income_tax_rate_percent(integer,numeric)
from public,anon,authenticated;
grant execute on function public._teacher_set_income_tax_rate_percent(integer,numeric)
to service_role;

create or replace function public._teacher_grant_gold_with_tax(
  p_student_id integer,
  p_gross_amount bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_tax bigint;
  v_net bigint;
  v_tx_id bigint;
  v_new_gold bigint;
begin
  if p_gross_amount is null or p_gross_amount<=0 then
    return jsonb_build_object(
      'transaction_id',null,
      'gross_amount',0,
      'tax_amount',0,
      'net_amount',0,
      'new_balance',(select coalesce(w.gold,0) from public.wallets w where w.student_id=p_student_id)
    );
  end if;

  select s.classroom_id into v_classroom_id
  from public.students s
  where s.id=p_student_id and s.transferred_at is null;

  if v_classroom_id is null then
    raise exception '활성 학생을 찾을 수 없습니다.' using errcode='P0632';
  end if;

  v_tax:=public.calculate_income_tax_for_student(p_gross_amount,p_student_id);
  v_net:=p_gross_amount-v_tax;

  if v_net<=0 then
    raise exception '적용 세율로 인해 실수령 골드가 0 이하가 됩니다.' using errcode='P0633';
  end if;

  v_tx_id:=public.create_transaction(
    p_student_id,
    'GOLD'::public.value_token_type,
    v_net,
    'TEACHER_GRANT'::public.transaction_source_type,
    null,
    v_tax,
    format('[교사 지급] %s · 총 %s GOLD / 세금 %s / 실수령 %s',
      p_reason,p_gross_amount,v_tax,v_net)
  );

  if v_tax>0 then
    insert into public.classroom_settings(classroom_id,setting_key,setting_value)
    values (v_classroom_id,'welfare_balance',to_jsonb(v_tax))
    on conflict (classroom_id,setting_key) do update
    set setting_value=to_jsonb(
      coalesce((public.classroom_settings.setting_value)::text::bigint,0)+v_tax
    ),
    updated_at=now();
  end if;

  select w.gold into v_new_gold
  from public.wallets w
  where w.student_id=p_student_id;

  return jsonb_build_object(
    'transaction_id',v_tx_id,
    'gross_amount',p_gross_amount,
    'tax_amount',v_tax,
    'net_amount',v_net,
    'new_balance',v_new_gold
  );
end;
$function$;

revoke all on function public._teacher_grant_gold_with_tax(integer,bigint,text)
from public,anon,authenticated;
grant execute on function public._teacher_grant_gold_with_tax(integer,bigint,text)
to service_role;

create or replace function public._teacher_apply_asset_deduction(
  p_student_id integer,
  p_value_token public.value_token_type,
  p_requested_amount bigint,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_current bigint:=0;
  v_reserved_auction bigint:=0;
  v_equalization_debt bigint:=0;
  v_equalization_reserve bigint:=0;
  v_min_balance bigint:=0;
  v_available bigint:=0;
  v_collected bigint:=0;
  v_outstanding bigint:=0;
  v_tx_id bigint:=null;
  v_arrear_id bigint:=null;
  v_source public.transaction_source_type;
  v_new_balance bigint:=0;
begin
  if p_requested_amount is null or p_requested_amount<=0 then
    raise exception '차감 금액은 1 이상이어야 합니다.' using errcode='P0634';
  end if;

  select s.classroom_id into v_classroom_id
  from public.students s
  where s.id=p_student_id and s.transferred_at is null;

  if v_classroom_id is null then
    raise exception '활성 학생을 찾을 수 없습니다.' using errcode='P0632';
  end if;

  perform 1 from public.wallets w where w.student_id=p_student_id for update;

  select case p_value_token
    when 'BV'::public.value_token_type then w.bv
    when 'GOLD'::public.value_token_type then w.gold
    when 'CRYSTAL'::public.value_token_type then w.crystal
  end
  into v_current
  from public.wallets w
  where w.student_id=p_student_id;

  v_current:=coalesce(v_current,0);

  if p_value_token='GOLD'::public.value_token_type then
    select coalesce(max(b.bid_amount),0)::bigint
    into v_reserved_auction
    from public.auction_bids b
    join public.auction_items i on i.id=b.auction_item_id
    join public.auctions a on a.id=i.auction_id
    where b.student_id=p_student_id
      and b.is_winning=true
      and b.invalidated_at is null
      and i.final_status is null
      and a.status='IN_PROGRESS'
      and a.current_item_id=i.id;

    select coalesce(sum(ep.amount-ep.paid_amount),0)::bigint
    into v_equalization_debt
    from public.equalization_contribution_payments ep
    where ep.student_id=p_student_id
      and ep.paid_amount<ep.amount;

    v_equalization_reserve:=least(v_equalization_debt,v_current);
    v_min_balance:=greatest(v_reserved_auction,v_equalization_reserve);
  else
    v_min_balance:=0;
  end if;

  v_available:=greatest(v_current-v_min_balance,0);
  v_collected:=least(p_requested_amount,v_available);
  v_outstanding:=p_requested_amount-v_collected;

  if p_value_token='BV'::public.value_token_type then
    v_source:='BV_REVOKE'::public.transaction_source_type;
  else
    v_source:='TEACHER_DEDUCT'::public.transaction_source_type;
  end if;

  if v_collected>0 then
    v_tx_id:=public.create_transaction(
      p_student_id,
      p_value_token,
      -v_collected,
      v_source,
      null,
      0,
      case p_value_token
        when 'BV'::public.value_token_type then '[교사 BV 차감] '||p_reason
        when 'GOLD'::public.value_token_type then '[교사 골드 차감] '||p_reason
        else '[교사 크리스탈 차감] '||p_reason
      end
    );
  end if;

  if v_outstanding>0 then
    insert into public.student_asset_arrears(
      classroom_id,student_id,value_token,assessed_amount,paid_amount,
      reason,status,initial_transaction_id,created_by
    ) values (
      v_classroom_id,p_student_id,p_value_token,p_requested_amount,v_collected,
      p_reason,
      case when v_collected>0 then 'PARTIAL' else 'UNPAID' end,
      v_tx_id,auth.uid()
    )
    returning id into v_arrear_id;
  end if;

  select case p_value_token
    when 'BV'::public.value_token_type then w.bv
    when 'GOLD'::public.value_token_type then w.gold
    when 'CRYSTAL'::public.value_token_type then w.crystal
  end
  into v_new_balance
  from public.wallets w
  where w.student_id=p_student_id;

  return jsonb_build_object(
    'transaction_id',v_tx_id,
    'arrear_id',v_arrear_id,
    'requested_amount',p_requested_amount,
    'collected_amount',v_collected,
    'outstanding_amount',v_outstanding,
    'new_balance',coalesce(v_new_balance,0),
    'reserved_auction',v_reserved_auction,
    'equalization_reserve',v_equalization_reserve
  );
end;
$function$;

revoke all on function public._teacher_apply_asset_deduction(integer,public.value_token_type,bigint,text)
from public,anon,authenticated;
grant execute on function public._teacher_apply_asset_deduction(integer,public.value_token_type,bigint,text)
to service_role;

create or replace function public.teacher_adjust_student_assets_v2(
  p_student_ids integer[],
  p_value_token public.value_token_type,
  p_amount bigint,
  p_reason text,
  p_tax_rate_percent numeric default null
)
returns table(
  student_id integer,
  transaction_id bigint,
  new_balance bigint,
  tax_amount bigint,
  arrear_amount bigint
)
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_requested_count integer;
  v_valid_count integer;
  v_student_id integer;
  v_reason text;
  v_result jsonb;
  v_tx_id bigint;
  v_new_balance bigint;
  v_tax bigint;
  v_arrear bigint;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.' using errcode='P0600';
  end if;
  perform public.ensure_teacher_role();

  v_requested_count:=cardinality(p_student_ids);
  if p_student_ids is null or coalesce(v_requested_count,0)<1 then
    raise exception '대상 학생을 한 명 이상 선택해주세요.' using errcode='P0601';
  end if;
  if v_requested_count>100 then
    raise exception '한 번에 처리할 수 있는 학생은 최대 100명입니다.' using errcode='P0602';
  end if;
  if (select count(distinct x.id) from unnest(p_student_ids) x(id))<>v_requested_count
     or exists(select 1 from unnest(p_student_ids) x(id) where x.id is null) then
    raise exception '학생 목록에 중복 또는 잘못된 값이 있습니다.' using errcode='P0603';
  end if;

  if p_value_token is null or p_value_token not in (
    'BV'::public.value_token_type,
    'GOLD'::public.value_token_type,
    'CRYSTAL'::public.value_token_type
  ) then
    raise exception '교사 조정은 BV, GOLD 또는 CRYSTAL만 가능합니다.' using errcode='P0604';
  end if;

  if p_amount is null or p_amount=0 or abs(p_amount)>10000000 then
    raise exception '금액은 1 이상 10,000,000 이하이어야 합니다.' using errcode='P0605';
  end if;

  v_reason:=btrim(coalesce(p_reason,''));
  if char_length(v_reason)<2 or char_length(v_reason)>200 then
    raise exception '사유는 2자 이상 200자 이하로 입력해주세요.' using errcode='P0606';
  end if;

  v_classroom_id:=public.current_classroom_id();
  if v_classroom_id is null then
    raise exception '담당 학급을 확인할 수 없습니다.' using errcode='P0607';
  end if;

  select count(*) into v_valid_count
  from public.students s
  where s.id=any(p_student_ids)
    and s.classroom_id=v_classroom_id
    and s.transferred_at is null
    and s.role in ('STUDENT','STUDENT_LEADER','GUARD');

  if v_valid_count<>v_requested_count then
    raise exception '선택한 학생 중 담당 학급의 활성 학생이 아닌 대상이 있습니다.' using errcode='P0608';
  end if;

  if p_amount>0
     and p_value_token='GOLD'::public.value_token_type
     and p_tax_rate_percent is not null then
    perform public._teacher_set_income_tax_rate_percent(v_classroom_id,p_tax_rate_percent);
  end if;

  for v_student_id in
    select x.id from unnest(p_student_ids) x(id) order by x.id
  loop
    v_tx_id:=null;
    v_tax:=0;
    v_arrear:=0;

    if p_amount>0 then
      if p_value_token='GOLD'::public.value_token_type then
        v_result:=public._teacher_grant_gold_with_tax(v_student_id,p_amount,v_reason);
        v_tx_id:=nullif(v_result->>'transaction_id','')::bigint;
        v_new_balance:=coalesce((v_result->>'new_balance')::bigint,0);
        v_tax:=coalesce((v_result->>'tax_amount')::bigint,0);
      else
        v_tx_id:=public.create_transaction(
          v_student_id,
          p_value_token,
          p_amount,
          'TEACHER_GRANT'::public.transaction_source_type,
          null,
          0,
          case p_value_token
            when 'BV'::public.value_token_type then '[교사 BV 지급] '||v_reason
            else '[교사 크리스탈 지급] '||v_reason
          end
        );

        select case p_value_token
          when 'BV'::public.value_token_type then w.bv
          else w.crystal
        end
        into v_new_balance
        from public.wallets w
        where w.student_id=v_student_id;
      end if;
    else
      v_result:=public._teacher_apply_asset_deduction(
        v_student_id,p_value_token,abs(p_amount),v_reason
      );
      v_tx_id:=nullif(v_result->>'transaction_id','')::bigint;
      v_new_balance:=coalesce((v_result->>'new_balance')::bigint,0);
      v_arrear:=coalesce((v_result->>'outstanding_amount')::bigint,0);
    end if;

    student_id:=v_student_id;
    transaction_id:=v_tx_id;
    new_balance:=v_new_balance;
    tax_amount:=v_tax;
    arrear_amount:=v_arrear;
    return next;
  end loop;
end;
$function$;

revoke all on function public.teacher_adjust_student_assets_v2(
  integer[],public.value_token_type,bigint,text,numeric
) from public,anon;
grant execute on function public.teacher_adjust_student_assets_v2(
  integer[],public.value_token_type,bigint,text,numeric
) to authenticated,service_role;

create or replace function public.teacher_adjust_student_assets_combined(
  p_student_ids integer[],
  p_bv_amount bigint,
  p_gold_amount bigint,
  p_operation text,
  p_reason text,
  p_tax_rate_percent numeric default null
)
returns table(
  student_id integer,
  bv_transaction_id bigint,
  gold_transaction_id bigint,
  new_bv bigint,
  new_gold bigint,
  gold_tax_amount bigint,
  bv_arrear_amount bigint,
  gold_arrear_amount bigint
)
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_classroom_id integer;
  v_requested_count integer;
  v_valid_count integer;
  v_student_id integer;
  v_reason text;
  v_operation text;
  v_bv_result jsonb;
  v_gold_result jsonb;
  v_bv_tx bigint;
  v_gold_tx bigint;
  v_new_bv bigint;
  v_new_gold bigint;
  v_gold_tax bigint;
  v_bv_arrear bigint;
  v_gold_arrear bigint;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.' using errcode='P0600';
  end if;
  perform public.ensure_teacher_role();

  v_requested_count:=cardinality(p_student_ids);
  if p_student_ids is null or coalesce(v_requested_count,0)<1 then
    raise exception '대상 학생을 한 명 이상 선택해주세요.' using errcode='P0601';
  end if;
  if v_requested_count>100 then
    raise exception '한 번에 처리할 수 있는 학생은 최대 100명입니다.' using errcode='P0602';
  end if;
  if (select count(distinct x.id) from unnest(p_student_ids) x(id))<>v_requested_count
     or exists(select 1 from unnest(p_student_ids) x(id) where x.id is null) then
    raise exception '학생 목록에 중복 또는 잘못된 값이 있습니다.' using errcode='P0603';
  end if;

  p_bv_amount:=coalesce(p_bv_amount,0);
  p_gold_amount:=coalesce(p_gold_amount,0);
  if p_bv_amount<0 or p_gold_amount<0
     or p_bv_amount>10000000 or p_gold_amount>10000000
     or (p_bv_amount=0 and p_gold_amount=0) then
    raise exception 'BV와 GOLD는 0~10,000,000 정수이며 둘 중 하나 이상은 1 이상이어야 합니다.'
      using errcode='P0621';
  end if;

  v_operation:=upper(btrim(coalesce(p_operation,'')));
  if v_operation not in ('GRANT','DEDUCT') then
    raise exception '처리 방식은 GRANT 또는 DEDUCT여야 합니다.' using errcode='P0635';
  end if;

  v_reason:=btrim(coalesce(p_reason,''));
  if char_length(v_reason)<2 or char_length(v_reason)>200 then
    raise exception '사유는 2자 이상 200자 이하로 입력해주세요.' using errcode='P0606';
  end if;

  v_classroom_id:=public.current_classroom_id();
  if v_classroom_id is null then
    raise exception '담당 학급을 확인할 수 없습니다.' using errcode='P0607';
  end if;

  select count(*) into v_valid_count
  from public.students s
  where s.id=any(p_student_ids)
    and s.classroom_id=v_classroom_id
    and s.transferred_at is null
    and s.role in ('STUDENT','STUDENT_LEADER','GUARD');

  if v_valid_count<>v_requested_count then
    raise exception '선택한 학생 중 담당 학급의 활성 학생이 아닌 대상이 있습니다.' using errcode='P0608';
  end if;

  if v_operation='GRANT' and p_gold_amount>0 and p_tax_rate_percent is not null then
    perform public._teacher_set_income_tax_rate_percent(v_classroom_id,p_tax_rate_percent);
  end if;

  for v_student_id in
    select x.id from unnest(p_student_ids) x(id) order by x.id
  loop
    v_bv_tx:=null;
    v_gold_tx:=null;
    v_gold_tax:=0;
    v_bv_arrear:=0;
    v_gold_arrear:=0;

    if p_bv_amount>0 then
      if v_operation='GRANT' then
        v_bv_tx:=public.create_transaction(
          v_student_id,'BV'::public.value_token_type,p_bv_amount,
          'TEACHER_GRANT'::public.transaction_source_type,null,0,
          '[교사 BV+골드 동시 지급 / BV] '||v_reason
        );
      else
        v_bv_result:=public._teacher_apply_asset_deduction(
          v_student_id,'BV'::public.value_token_type,p_bv_amount,v_reason
        );
        v_bv_tx:=nullif(v_bv_result->>'transaction_id','')::bigint;
        v_bv_arrear:=coalesce((v_bv_result->>'outstanding_amount')::bigint,0);
      end if;
    end if;

    if p_gold_amount>0 then
      if v_operation='GRANT' then
        v_gold_result:=public._teacher_grant_gold_with_tax(
          v_student_id,p_gold_amount,v_reason
        );
        v_gold_tx:=nullif(v_gold_result->>'transaction_id','')::bigint;
        v_gold_tax:=coalesce((v_gold_result->>'tax_amount')::bigint,0);
      else
        v_gold_result:=public._teacher_apply_asset_deduction(
          v_student_id,'GOLD'::public.value_token_type,p_gold_amount,v_reason
        );
        v_gold_tx:=nullif(v_gold_result->>'transaction_id','')::bigint;
        v_gold_arrear:=coalesce((v_gold_result->>'outstanding_amount')::bigint,0);
      end if;
    end if;

    select w.bv,w.gold into v_new_bv,v_new_gold
    from public.wallets w where w.student_id=v_student_id;

    student_id:=v_student_id;
    bv_transaction_id:=v_bv_tx;
    gold_transaction_id:=v_gold_tx;
    new_bv:=coalesce(v_new_bv,0);
    new_gold:=coalesce(v_new_gold,0);
    gold_tax_amount:=v_gold_tax;
    bv_arrear_amount:=v_bv_arrear;
    gold_arrear_amount:=v_gold_arrear;
    return next;
  end loop;
end;
$function$;

revoke all on function public.teacher_adjust_student_assets_combined(
  integer[],bigint,bigint,text,text,numeric
) from public,anon;
grant execute on function public.teacher_adjust_student_assets_combined(
  integer[],bigint,bigint,text,text,numeric
) to authenticated,service_role;

create or replace function public.teacher_adjust_student_assets(
  p_student_ids integer[],
  p_value_token public.value_token_type,
  p_amount bigint,
  p_reason text
)
returns table(student_id integer,transaction_id bigint,new_balance bigint)
language sql
security definer
set search_path to 'public','pg_temp'
as $function$
  select x.student_id,x.transaction_id,x.new_balance
  from public.teacher_adjust_student_assets_v2(
    p_student_ids,p_value_token,p_amount,p_reason,null
  ) x;
$function$;

revoke all on function public.teacher_adjust_student_assets(
  integer[],public.value_token_type,bigint,text
) from public,anon;
grant execute on function public.teacher_adjust_student_assets(
  integer[],public.value_token_type,bigint,text
) to authenticated,service_role;

create or replace function public.teacher_grant_student_assets_combined(
  p_student_ids integer[],
  p_bv_amount bigint,
  p_gold_amount bigint,
  p_reason text
)
returns table(
  student_id integer,
  bv_transaction_id bigint,
  gold_transaction_id bigint,
  new_bv bigint,
  new_gold bigint
)
language sql
security definer
set search_path to 'public','pg_temp'
as $function$
  select
    x.student_id,x.bv_transaction_id,x.gold_transaction_id,x.new_bv,x.new_gold
  from public.teacher_adjust_student_assets_combined(
    p_student_ids,p_bv_amount,p_gold_amount,'GRANT',p_reason,null
  ) x;
$function$;

revoke all on function public.teacher_grant_student_assets_combined(
  integer[],bigint,bigint,text
) from public,anon;
grant execute on function public.teacher_grant_student_assets_combined(
  integer[],bigint,bigint,text
) to authenticated,service_role;

create or replace function public.student_get_my_asset_arrears()
returns jsonb
language plpgsql
stable security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_student_id integer:=public.current_student_id();
  v_classroom_id integer:=public.current_classroom_id();
  v_result jsonb;
begin
  if v_student_id is null or v_classroom_id is null then
    raise exception '학생 정보를 확인할 수 없습니다.' using errcode='P0636';
  end if;

  select jsonb_build_object(
    'student_id',v_student_id,
    'classroom_id',v_classroom_id,
    'total_items',count(*) filter(where a.status in ('UNPAID','PARTIAL')),
    'totals',jsonb_build_object(
      'BV',coalesce(sum(a.assessed_amount-a.paid_amount)
        filter(where a.status in ('UNPAID','PARTIAL') and a.value_token='BV'),0),
      'GOLD',coalesce(sum(a.assessed_amount-a.paid_amount)
        filter(where a.status in ('UNPAID','PARTIAL') and a.value_token='GOLD'),0),
      'CRYSTAL',coalesce(sum(a.assessed_amount-a.paid_amount)
        filter(where a.status in ('UNPAID','PARTIAL') and a.value_token='CRYSTAL'),0)
    ),
    'entries',coalesce(jsonb_agg(
      jsonb_build_object(
        'id',a.id,
        'value_token',a.value_token::text,
        'assessed_amount',a.assessed_amount,
        'paid_amount',a.paid_amount,
        'outstanding_amount',a.assessed_amount-a.paid_amount,
        'reason',a.reason,
        'status',a.status,
        'created_at',a.created_at
      ) order by a.created_at desc,a.id desc
    ) filter(where a.status in ('UNPAID','PARTIAL')),'[]'::jsonb)
  )
  into v_result
  from public.student_asset_arrears a
  where a.student_id=v_student_id
    and a.classroom_id=v_classroom_id;

  return coalesce(v_result,jsonb_build_object(
    'student_id',v_student_id,
    'classroom_id',v_classroom_id,
    'total_items',0,
    'totals',jsonb_build_object('BV',0,'GOLD',0,'CRYSTAL',0),
    'entries','[]'::jsonb
  ));
end;
$function$;

revoke all on function public.student_get_my_asset_arrears() from public,anon;
grant execute on function public.student_get_my_asset_arrears() to authenticated,service_role;

create or replace function public.reverse_transaction(
  p_original_tx_id bigint,
  p_reason text
)
returns bigint
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
  v_original public.transactions%rowtype;
  v_reversal_tx_id bigint;
  v_reason text;
  v_welfare_balance bigint:=0;
begin
  v_reason:=btrim(coalesce(p_reason,''));
  if char_length(v_reason)<2 or char_length(v_reason)>200 then
    raise exception '취소 사유는 2자 이상 200자 이하로 입력해주세요.' using errcode='P0624';
  end if;

  select * into v_original
  from public.transactions
  where id=p_original_tx_id
  for update;

  if v_original.id is null then
    raise exception '원본 거래를 찾을 수 없습니다.' using errcode='P0030';
  end if;
  if v_original.is_reversed then
    raise exception '이미 취소된 거래입니다.' using errcode='P0031';
  end if;
  if v_original.source_type='REVERSAL'::public.transaction_source_type then
    raise exception '취소 거래 자체는 다시 취소할 수 없습니다.' using errcode='P0623';
  end if;

  if v_original.source_type='TEACHER_GRANT'::public.transaction_source_type
     and v_original.value_token='GOLD'::public.value_token_type
     and coalesce(v_original.tax_amount,0)>0 then
    select coalesce((cs.setting_value)::text::bigint,0)
    into v_welfare_balance
    from public.classroom_settings cs
    where cs.classroom_id=v_original.classroom_id
      and cs.setting_key='welfare_balance'
    for update;

    if coalesce(v_welfare_balance,0)<v_original.tax_amount then
      raise exception '이 지급의 세금이 이미 복지기금에서 사용되어 현재 잔액으로는 거래를 취소할 수 없습니다.'
        using errcode='P0637';
    end if;
  end if;

  v_reversal_tx_id:=public.create_transaction(
    v_original.student_id,
    v_original.value_token,
    -v_original.amount,
    'REVERSAL',
    p_original_tx_id,
    0,
    format('[거래 취소] %s · 사유: %s',
      coalesce(v_original.memo,'거래 #'||v_original.id::text),v_reason)
  );

  update public.transactions
  set is_reversed=true,
      reversed_by_transaction_id=v_reversal_tx_id,
      reversed_at=now(),
      reversal_reason=v_reason
  where id=p_original_tx_id;

  if v_original.source_type='TEACHER_GRANT'::public.transaction_source_type
     and v_original.value_token='GOLD'::public.value_token_type
     and coalesce(v_original.tax_amount,0)>0 then
    update public.classroom_settings
    set setting_value=to_jsonb(v_welfare_balance-v_original.tax_amount),
        updated_at=now()
    where classroom_id=v_original.classroom_id
      and setting_key='welfare_balance';
  end if;

  update public.student_asset_arrears
  set status='WAIVED',
      waived_at=now(),
      settled_at=now(),
      updated_at=now()
  where initial_transaction_id=p_original_tx_id
    and status in ('UNPAID','PARTIAL');

  return v_reversal_tx_id;
end;
$function$;

revoke all on function public.reverse_transaction(bigint,text) from public,anon,authenticated;
grant execute on function public.reverse_transaction(bigint,text) to service_role;

commit;
