import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { TeacherShell } from '@/components/teacher/TeacherShell';
import { EmptyState, LoadingSpinner, Modal, useRpcCall } from '@/components/shared/components';
import { supabase } from '@/lib/supabase/client';
import { newbieSupportRpc, type TeacherNewbieBoard } from '@/lib/rpc/newbie_support_rpc';
import { formatNumber } from '@/lib/utils/format';
import { cn } from '@/lib/utils/cn';

const STATUS_LABEL: Record<string,string> = {
  DRAFT:'초안', ACTIVE:'진행 중', SCHEDULED:'시작 대기', IN_PROGRESS:'진행 중', REVIEWING:'기간 종료 · 검토 중', READY_TO_COMPLETE:'전체 승인 완료', COMPLETION_PENDING:'최종 정산 대기', COMPLETED:'완료', EXPIRED:'기간 종료', CANCELLED:'취소',
  PENDING:'검토 대기', APPROVED:'승인', REJECTED:'반려', REVOKED:'승인 회수',
};
const HELP_LABEL:Record<string,string>={EXPLANATION:'방법 설명',COACHING:'코칭·조언',CHECKING:'함께 확인',TRANSACTION:'거래 참여',OTHER:'기타'};

type ProgramForm={programId:number|null;studentId:number|null;missed:number;bvPer:number;startOn:string;endOn:string;mentorIds:number[];requestIds:number[]};
type ReviewState={claim:any;validMentorIds:number[];note:string;decision:'APPROVE'|'REJECT'};

function kstDate(offsetDays=0){const d=new Date(Date.now()+offsetDays*86400000);return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
const EMPTY_FORM=():ProgramForm=>({programId:null,studentId:null,missed:49,bvPer:400,startOn:kstDate(),endOn:kstDate(30),mentorIds:[],requestIds:[]});

export default function NewbieSupportAdmin(){
  const qc=useQueryClient(); const {call,isLoading}=useRpcCall();
  const [form,setForm]=useState<ProgramForm|null>(null); const [preview,setPreview]=useState<any|null>(null); const [review,setReview]=useState<ReviewState|null>(null);
  const board=useQuery<TeacherNewbieBoard>({queryKey:['teacher-newbie-support-board'],queryFn:async()=>{const r=await newbieSupportRpc.teacherBoard(supabase);if(r.success === false)throw new Error(r.error);return r.data;},staleTime:5000});
  const data=board.data; const programs=data?.programs??[]; const claims=data?.claims??[]; const students=data?.students??[]; const publicRequests=data?.public_requests??[];
  const refresh=()=>{void board.refetch();void qc.invalidateQueries({queryKey:['newbie-support-student-board']});void qc.invalidateQueries({queryKey:['newbie-support-mentor-board']});void qc.invalidateQueries({queryKey:['newbie-support-summary']});void qc.invalidateQueries({queryKey:['dashboard']});void qc.invalidateQueries({queryKey:['wallet']});};
  const selectedStudent=students.find(s=>s.student_id===form?.studentId);
  const formTotal=(form?.missed??0)*(form?.bvPer??0); const formValid=!!form&&!!form.studentId&&form.missed>0&&form.bvPer>0&&form.startOn<=form.endOn&&form.mentorIds.length>=2&&form.mentorIds.length<=3&&form.requestIds.length>=1&&!form.mentorIds.includes(form.studentId!);

  const save=async()=>{if(!form||!formValid)return; if(form.programId){await call(()=>newbieSupportRpc.updateProgram(supabase,{p_program_id:form.programId,p_missed_opportunities:form.missed,p_bv_per_opportunity:form.bvPer,p_start_on:form.startOn,p_end_on:form.endOn,p_mentor_student_ids:form.mentorIds,p_public_request_ids:form.requestIds}),{successTitle:'정착 지원 초안을 수정했어요',onSuccess:()=>{setForm(null);refresh();}});}else{await call(()=>newbieSupportRpc.createProgram(supabase,{p_student_id:form.studentId!,p_template_code:'NEWBIE_SETTLEMENT',p_template_version:1,p_missed_opportunities:form.missed,p_bv_per_opportunity:form.bvPer,p_start_on:form.startOn,p_end_on:form.endOn,p_mentor_student_ids:form.mentorIds,p_public_request_ids:form.requestIds}),{successTitle:'정착 지원 초안을 만들었어요',successDescription:'활성화 검토 후 시작해야 학생에게 공개됩니다.',onSuccess:()=>{setForm(null);refresh();}});}};
  const edit=(p:any)=>setForm({programId:p.program_id,studentId:p.student_id,missed:p.missed_opportunities,bvPer:p.bv_per_opportunity,startOn:p.start_on,endOn:p.end_on,mentorIds:(p.mentor_ids??[]).map(Number),requestIds:(p.public_request_ids??[]).map(Number).filter((id:number)=>publicRequests.some(r=>Number(r.request_id)===id))});
  const doPreview=async(id:number)=>{const x=await call(()=>newbieSupportRpc.previewActivation(supabase,id),{silent:true});if(x)setPreview(x);};
  const activate=async()=>{if(!preview?.program_id)return;await call(()=>newbieSupportRpc.activateProgram(supabase,preview.program_id),{successTitle:'🌱 정착 지원을 시작했어요',onSuccess:()=>{setPreview(null);refresh();}});};
  const cancel=async(p:any)=>{const reason=window.prompt('취소 사유를 2자 이상 입력하세요.');if(!reason)return;await call(()=>newbieSupportRpc.cancelProgram(supabase,{p_program_id:p.program_id,p_reason:reason}),{successTitle:'정착 지원을 취소했어요',onSuccess:refresh});};
  const extend=async(p:any)=>{const end=window.prompt('새 종료일 (YYYY-MM-DD)',p.end_on);if(!end||end<=p.end_on)return;const reason=window.prompt('연장 사유를 2자 이상 입력하세요.');if(!reason)return;await call(()=>newbieSupportRpc.extendDeadline(supabase,{p_program_id:p.program_id,p_new_end_on:end,p_reason:reason}),{successTitle:'정착 기간을 연장했어요',onSuccess:refresh});};
  const finalize=async(p:any)=>{
    let skipBest=false; let overrideReason:string|null=null;
    if(!p.best_mentor_assignment_id){
      if(!window.confirm('Best Mentor가 선택되지 않았습니다. Best Mentor 추가 보상 없이 최종 정산할까요?'))return;
      const reason=window.prompt('Best Mentor 없이 정산하는 사유를 2자 이상 입력하세요.');
      if(!reason||reason.trim().length<2)return;
      skipBest=true; overrideReason=reason.trim();
    } else if(!window.confirm('최종 정산하면 완료 보너스와 자격을 충족한 멘토 보상이 즉시 지급됩니다. 계속할까요?'))return;
    await call(()=>newbieSupportRpc.finalizeProgram(supabase,{p_program_id:p.program_id,p_skip_best_mentor:skipBest,p_override_reason:overrideReason}),{successTitle:'🎉 정착 프로그램 최종 정산 완료',onSuccess:refresh});
  };
  const revoke=async(c:any)=>{const reason=window.prompt('승인 회수 사유를 2자 이상 입력하세요.');if(!reason)return;await call(()=>newbieSupportRpc.revokeClaim(supabase,{p_claim_id:c.claim_id,p_reason:reason}),{successTitle:'정착 BV 승인을 회수했어요',onSuccess:refresh});};
  const openReview=(c:any)=>setReview({claim:c,validMentorIds:(c.mentor_help??[]).map((h:any)=>Number(h.mentor_assignment_id)),note:'',decision:'APPROVE'});
  const submitReview=async()=>{if(!review)return;await call(()=>newbieSupportRpc.reviewClaim(supabase,{p_claim_id:review.claim.claim_id,p_decision:review.decision,p_valid_mentor_assignment_ids:review.decision==='APPROVE'?review.validMentorIds:[],p_review_note:review.note.trim()||null}),{successTitle:review.decision==='APPROVE'?`✅ 승인 +${formatNumber(review.claim.reward_bv)} BV`:'완료 요청을 반려했어요',onSuccess:()=>{setReview(null);refresh();}});};

  if(board.isLoading)return <TeacherShell><div className="flex min-h-[520px] items-center justify-center"><LoadingSpinner size="lg"/></div></TeacherShell>;
  if(board.isError||!data)return <TeacherShell><EmptyState emoji="⚠️" title="뉴비 정착 지원 정보를 불러오지 못했습니다" description={board.error instanceof Error?board.error.message:'알 수 없는 오류'} action={<button className="btn-secondary" onClick={refresh}>다시 불러오기</button>}/></TeacherShell>;
  return <TeacherShell><div className="space-y-5 pb-10">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-display text-2xl text-brand-gradient">🌱 뉴비 정착 지원</h1><p className="mt-1 text-sm text-text-secondary">후발 합류자의 놓친 참여 기회를 별도 정착 퀘스트로 복원합니다. 일반 활동 보상 배율은 바꾸지 않습니다.</p></div><button className="btn-primary" onClick={()=>setForm(EMPTY_FORM())}>+ 정착 학생 등록</button></div>
    <div className="grid gap-3 sm:grid-cols-4"><Stat label="전체 프로그램" value={programs.length}/><Stat label="진행 중" value={programs.filter((p:any)=>p.status==='ACTIVE').length}/><Stat label="검토 대기" value={claims.filter((c:any)=>c.status==='PENDING').length}/><Stat label="완료" value={programs.filter((p:any)=>p.status==='COMPLETED').length}/></div>

    <section className="glass-card p-4"><h2 className="font-display text-lg">정착 프로그램</h2>{programs.length===0?<EmptyState emoji="🌱" title="등록된 정착 프로그램이 없습니다"/>:<div className="mt-3 space-y-3">{programs.map((p:any)=><div key={p.program_id} className="rounded-card-md border border-line bg-bg-deep p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black text-white">{p.student_brand_name||p.student_name}</div><div className="mt-1 text-xs text-text-secondary">놓친 기회 {p.missed_opportunities}회 × {formatNumber(p.bv_per_opportunity)} BV = <b>{formatNumber(p.total_restorable_bv)} BV</b></div><div className="mt-1 text-xs text-text-muted">퀘스트 {p.approved_count}/{p.total_count} 승인 · {p.pending_count}건 검토 대기 · {p.start_on} ~ {p.end_on}</div></div><span className="rounded-pill border border-line-brand px-3 py-1 text-xs font-black text-gold">{STATUS_LABEL[p.effective_status]??p.effective_status}</span></div><div className="mt-3 flex flex-wrap gap-2">{p.status==='DRAFT'&&<><button className="btn-secondary text-xs" onClick={()=>edit(p)}>설정 수정</button><button className="btn-primary text-xs" onClick={()=>void doPreview(p.program_id)}>활성화 검토</button></>}{p.status==='ACTIVE'&&<><button className="btn-secondary text-xs" onClick={()=>void extend(p)}>기간 연장</button>{Number(p.approved_count)===Number(p.total_count)&&Number(p.pending_count)===0&&<button className="btn-primary text-xs" onClick={()=>void finalize(p)}>{p.completion_requested_at?'최종 정산':'교사 최종 정산'}</button>}</>}{(p.status==='DRAFT'||(p.status==='ACTIVE'&&Number(p.approved_count)===0))&&<button className="btn-secondary text-xs" onClick={()=>void cancel(p)}>프로그램 취소</button>}</div>{(p.mentors??[]).length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-3">{p.mentors.map((m:any)=><div key={m.mentor_assignment_id} className="rounded-card-md border border-line px-3 py-2 text-xs"><div className="font-black text-white">{m.brand_name||m.name}{m.is_best?' ⭐':''}</div><div className="text-text-muted">유효 도움 {m.valid_help_count}회 · {m.base_reward_outcome}</div></div>)}</div>}</div>)}</div>}</section>

    <section className="glass-card p-4"><div className="flex items-center justify-between"><h2 className="font-display text-lg">완료 요청 검토</h2><span className="text-xs font-black text-warning">대기 {claims.filter((c:any)=>c.status==='PENDING').length}건</span></div><div className="mt-3 space-y-3">{claims.filter((c:any)=>['PENDING','APPROVED'].includes(c.status)).map((c:any)=><div key={c.claim_id} className={cn('rounded-card-md border p-4',c.status==='PENDING'?'border-warning/30 bg-warning-bg/30':'border-line bg-bg-deep')}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black text-white">{c.student_name} · {c.quest_title} {c.occurrence_no}회차</div><div className="mt-1 text-xs text-text-secondary">예정/지급 BV +{formatNumber(c.reward_bv)} · 근거 ID #{c.evidence_ref_id}</div><div className="mt-1 text-xs text-text-muted">{c.student_note||'학생 메모 없음'}</div></div><span className="text-xs font-black text-gold">{STATUS_LABEL[c.status]??c.status}</span></div>{c.evidence&&<div className="mt-3 rounded-card-md border border-line bg-bg-base/40 p-3 text-xs text-text-secondary"><Evidence evidence={c.evidence}/></div>}{(c.mentor_help??[]).length>0&&<div className="mt-2 text-xs text-text-muted">멘토 도움: {(c.mentor_help??[]).map((h:any)=>`${h.mentor_name}(${HELP_LABEL[h.help_type]??h.help_type})`).join(', ')}</div>}<div className="mt-3 flex gap-2">{c.status==='PENDING'&&<button className="btn-primary text-xs" onClick={()=>openReview(c)}>검토하기</button>}{c.status==='APPROVED'&&<button className="btn-secondary text-xs" onClick={()=>void revoke(c)}>승인 회수</button>}</div></div>)}{claims.filter((c:any)=>['PENDING','APPROVED'].includes(c.status)).length===0&&<EmptyState emoji="✅" title="검토할 요청이 없습니다"/>}</div></section>

    <ProgramModal form={form} setForm={setForm} students={students} publicRequests={publicRequests} selectedStudent={selectedStudent} total={formTotal} valid={formValid} loading={isLoading} onSave={()=>void save()}/>
    <PreviewModal preview={preview} loading={isLoading} onClose={()=>setPreview(null)} onActivate={()=>void activate()}/>
    <ReviewModal state={review} setState={setReview} loading={isLoading} onSubmit={()=>void submitReview()}/>
  </div></TeacherShell>;
}

function Stat({label,value}:{label:string;value:number}){return <div className="glass-card p-4"><div className="text-xs font-black text-text-muted">{label}</div><div className="mt-1 font-display text-2xl text-white">{value}</div></div>}
function Evidence({evidence}:{evidence:any}){if(!evidence)return null;return <div className="space-y-1"><div className="font-black text-white">{evidence.primary_label||evidence.type||'검증 근거'}</div>{evidence.secondary_label&&<div>{evidence.secondary_label}</div>}{evidence.summary&&<div>{evidence.summary}</div>}{evidence.rating!==undefined&&<div>평점: {evidence.rating}/10</div>}{evidence.review_text&&<div className="break-words">후기: {evidence.review_text}</div>}{evidence.memo&&<div>메모: {evidence.memo}</div>}<details className="mt-2"><summary className="cursor-pointer text-[10px] text-text-muted">원본 검증 데이터</summary><pre className="mt-1 overflow-auto whitespace-pre-wrap text-[10px]">{JSON.stringify(evidence,null,2)}</pre></details></div>}

function ProgramModal({form,setForm,students,publicRequests,selectedStudent,total,valid,loading,onSave}:{form:ProgramForm|null;setForm:(v:ProgramForm|null)=>void;students:any[];publicRequests:any[];selectedStudent:any;total:number;valid:boolean;loading:boolean;onSave:()=>void}){
 if(!form)return null; const mentorOptions=students.filter(s=>s.student_id!==form.studentId);
 const toggle=(arr:number[],id:number)=>arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];
 return <Modal isOpen onClose={()=>setForm(null)} title={form.programId?'정착 지원 설정 수정':'정착 학생 등록'} emoji="🌱" size="lg"><div className="space-y-4"><div><label className="text-xs font-black text-text-secondary">대상 학생</label><select disabled={!!form.programId} className="input-field mt-1 w-full" value={form.studentId??''} onChange={e=>setForm({...form,studentId:e.target.value?Number(e.target.value):null,mentorIds:form.mentorIds.filter(x=>x!==Number(e.target.value))})}><option value="">학생 선택</option>{students.map(s=><option key={s.student_id} value={s.student_id}>{s.name}{s.brand_name?` (${s.brand_name})`:''}</option>)}</select></div>
 <div className="grid grid-cols-2 gap-3"><Field label="놓친 기회(회)" value={form.missed} onChange={v=>setForm({...form,missed:Number(v)})}/><Field label="기회당 기준 BV" value={form.bvPer} onChange={v=>setForm({...form,bvPer:Number(v)})}/><DateField label="시작일" value={form.startOn} onChange={v=>setForm({...form,startOn:v})}/><DateField label="종료일" value={form.endOn} onChange={v=>setForm({...form,endOn:v})}/></div>
 <div className="rounded-card-md border border-line-brand bg-brand-primary/10 p-3 text-sm"><b>{selectedStudent?.name??'대상 학생'}</b> 총 복원 가능 BV: <b className="text-bv">{formatNumber(total)}</b> · 일반 정착 퀘스트 80% + 전체 완료 20%</div>
 <div><div className="mb-2 text-xs font-black text-text-secondary">멘토 2~3명 선택</div><div className="grid max-h-44 grid-cols-2 gap-2 overflow-y-auto">{mentorOptions.map(s=><label key={s.student_id} className="flex items-center gap-2 rounded-card-md border border-line bg-bg-deep p-2 text-xs"><input type="checkbox" checked={form.mentorIds.includes(s.student_id)} disabled={!form.mentorIds.includes(s.student_id)&&form.mentorIds.length>=3} onChange={()=>setForm({...form,mentorIds:toggle(form.mentorIds,s.student_id)})}/><span>{s.brand_name||s.name}</span></label>)}</div></div>
 <div><div className="mb-2 text-xs font-black text-text-secondary">정착 퀘스트에 인정할 공공의뢰</div><div className="space-y-2">{publicRequests.map(r=><label key={r.request_id} className="flex items-center gap-2 rounded-card-md border border-line bg-bg-deep p-2 text-xs"><input type="checkbox" checked={form.requestIds.includes(r.request_id)} onChange={()=>setForm({...form,requestIds:toggle(form.requestIds,r.request_id)})}/><span>{r.title} · 마감 {new Date(r.due_at).toLocaleString('ko-KR')}</span></label>)}</div></div>
 <div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setForm(null)}>취소</button><button className="btn-primary" disabled={!valid||loading} onClick={onSave}>{form.programId?'수정 저장':'초안 생성'}</button></div></div></Modal>;
}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:string)=>void}){return <label className="text-xs font-black text-text-secondary">{label}<input className="input-field mt-1 w-full" type="number" min={1} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs font-black text-text-secondary">{label}<input className="input-field mt-1 w-full" type="date" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function PreviewModal({preview,loading,onClose,onActivate}:{preview:any|null;loading:boolean;onClose:()=>void;onActivate:()=>void}){return <Modal isOpen={!!preview} onClose={onClose} title="활성화 최종 검토" emoji="🔎" size="lg">{preview&&<div className="space-y-4"><div className={cn('rounded-card-md border p-3 text-sm',preview.ok?'border-success/30 bg-success-bg':'border-danger/30 bg-danger-bg')}><b>{preview.ok?'활성화 가능':'활성화 불가'}</b></div><div className="grid grid-cols-2 gap-2"><StatLine label="퀘스트 완료 횟수" value={`${preview.completion_count}회`}/><StatLine label="총 가중치" value={String(preview.total_weight)}/><StatLine label="일반 복원 풀" value={`${formatNumber(preview.regular_pool)} BV`}/><StatLine label="전체 완료 보너스" value={`${formatNumber(preview.completion_bonus)} BV`}/><StatLine label="슬롯 보상 합" value={`${formatNumber(preview.slot_reward_sum)} BV`}/><StatLine label="기존 완성 컬렉션 baseline" value={`${preview.collection_baseline_count_if_activated}종`}/></div>{(preview.blocking_errors??[]).length>0&&<div><div className="text-xs font-black text-danger">차단 오류</div>{preview.blocking_errors.map((x:string,i:number)=><div key={i} className="mt-1 text-xs text-danger">• {x}</div>)}</div>}{(preview.warnings??[]).length>0&&<div><div className="text-xs font-black text-warning">주의</div>{preview.warnings.map((x:string,i:number)=><div key={i} className="mt-1 text-xs text-warning">• {x}</div>)}</div>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>닫기</button><button className="btn-primary" disabled={!preview.ok||loading} onClick={onActivate}>정착 지원 시작</button></div></div>}</Modal>}
function StatLine({label,value}:{label:string;value:string}){return <div className="rounded-card-md border border-line bg-bg-deep p-3"><div className="text-[10px] text-text-muted">{label}</div><div className="mt-1 text-sm font-black text-white">{value}</div></div>}
function ReviewModal({state,setState,loading,onSubmit}:{state:ReviewState|null;setState:(v:ReviewState|null)=>void;loading:boolean;onSubmit:()=>void}){if(!state)return null;const helps=state.claim.mentor_help??[];return <Modal isOpen onClose={()=>setState(null)} title="정착 퀘스트 완료 요청 검토" emoji="✅" size="lg"><div className="space-y-4"><div className="rounded-card-md border border-line bg-bg-deep p-3"><div className="font-black text-white">{state.claim.student_name} · {state.claim.quest_title}</div><div className="mt-1 text-xs text-bv">승인 시 +{formatNumber(state.claim.reward_bv)} BV</div></div><Evidence evidence={state.claim.evidence}/>{helps.length>0&&<div><div className="mb-2 text-xs font-black text-text-secondary">유효 도움으로 인정할 멘토</div>{helps.map((h:any)=><label key={h.mentor_assignment_id} className="mb-2 flex items-center gap-2 rounded-card-md border border-line bg-bg-deep p-2 text-xs"><input type="checkbox" checked={state.validMentorIds.includes(Number(h.mentor_assignment_id))} onChange={()=>{const id=Number(h.mentor_assignment_id);setState({...state,validMentorIds:state.validMentorIds.includes(id)?state.validMentorIds.filter(x=>x!==id):[...state.validMentorIds,id]});}}/><span>{h.mentor_name} · {HELP_LABEL[h.help_type]??h.help_type}</span></label>)}</div>}<div className="flex gap-2"><button className={cn('flex-1 rounded-card-md border p-2 text-sm font-black',state.decision==='APPROVE'?'border-success bg-success-bg text-success':'border-line text-text-secondary')} onClick={()=>setState({...state,decision:'APPROVE'})}>승인</button><button className={cn('flex-1 rounded-card-md border p-2 text-sm font-black',state.decision==='REJECT'?'border-danger bg-danger-bg text-danger':'border-line text-text-secondary')} onClick={()=>setState({...state,decision:'REJECT'})}>반려</button></div><textarea className="input-field min-h-20 w-full" placeholder="검토 메모 (선택)" maxLength={500} value={state.note} onChange={e=>setState({...state,note:e.target.value})}/><div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setState(null)}>취소</button><button className="btn-primary" disabled={loading} onClick={onSubmit}>검토 확정</button></div></div></Modal>}
